-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_pii].[VwBORROWER]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[FNAME],
      x.[MNAME],
      x.[LNAME],
      x.[SSNBR],
      x.[AGE],
      x.[YRSSCHL],
      x.[S_MARITL],
      A0.[Descript] AS [S_MARITL_X],
      x.[FRNINFO],
      x.[GENDER],
      A1.[Descript] AS [GENDER_X],
      x.[NUMDEP],
      x.[DEPAGES],
      x.[ADDR1],
      x.[ADDR2],
      x.[CITY],
      x.[STATE],
      x.[ZIP],
      x.[YRSPADDR],
      x.[HPHONE],
      x.[PRIMARYB],
      x.[APPNUMB],
      x.[FIRSTBUY],
      x.[S_OWNSHP],
      A2.[Descript] AS [S_OWNSHP_X],
      x.[VOR_ACCT],
      x.[VOR_NAME],
      x.[OTHINCM],
      x.[COMMUNTY],
      x.[JOINTLY],
      x.[DOB],
      x.[S_BORTYP],
      A3.[Descript] AS [S_BORTYP_X],
      x.[ALIASES],
      x.[S_VESTNG],
      A4.[Descript] AS [S_VESTNG_X],
      x.[PRTENTTL],
      x.[PARTNOTE],
      x.[COUNTY],
      x.[CITYFLAG],
      x.[MARBOR],
      x.[COUNTRY],
      x.[RACEDESC],
      x.[CAIVR1],
      x.[CAIVR2],
      x.[LDPGSA1],
      x.[LDPGSA2],
      x.[POAFLAG],
      x.[ALISDBID],
      x.[ALSERNUM],
      x.[WPHONE],
      x.[EMAIL],
      x.[FAXNUM],
      x.[CANADIAN_SSN],
      x.[NAME_SUFFIX],
      x.[B_1098_IDN],
      x.[QUAL_INCOME],
      x.[BOR_TIN],
      x.[UNPARSED_NAME],
      x.[AFFIL_SHARE_IND],
      x.[SSN_CERTIFICATION_IND],
      x.[PHONE_ALLOWED_IND],
      x.[EMAIL_ALLOWED_IND],
      x.[US_MAIL_ALLOWED_IND],
      x.[CARRIER_ROUTE],
      x.[OVERALL_CRED_SCORE],
      x.[OVERALL_CRED_SCORE_OVR],
      x.[CORP_SIGNATURE],
      x.[INCBASEEMPTOTAL],
      x.[INCSELFEMPTOTAL],
      x.[INCOVERTIMETOTAL],
      x.[INCBONUSTOTAL],
      x.[INCCOMMISTOTAL],
      x.[INCDIVDTOTAL],
      x.[INCNETRENTOTAL],
      x.[ATCASHDEPOSITTOTAL],
      x.[ATCHECKSAVINGSTOTAL],
      x.[ATSTOCKBONDTOTAL],
      x.[ATLIFEINSNETTOTAL],
      x.[ATOTHLIQUIDTOTAL],
      x.[ATREOTOTAL],
      x.[ATVESTEDINTTOTAL],
      x.[ATNETWORTHTOTAL],
      x.[ATAUTOMOBILE],
      x.[ATOTHNONLIQTOTAL],
      x.[INCOTHERTOTAL],
      x.[ATLIFEINSFACEAMTTOTAL],
      x.[ATASSETSTOTAL],
      x.[LTALIMONYCSSMPTOTAL],
      x.[LTJOBRELATEDEXPTOTAL],
      x.[LTLIABILITIESTOTAL],
      x.[LTMONTHLYPAYMNTTOTAL],
      x.[REOGROSSRENTINCTOTAL],
      x.[REOMORTANDLIENTOTAL],
      x.[REOMORTGAGEPAYMNTTOTAL],
      x.[REOTAXMAINTMISCTOTAL],
      x.[URLANETWORTH],
      x.[ELEC_DISC_CONSENT],
      x.[ELEC_DISC_WITHDRAW],
      x.[S_IVMETH],
      A5.[Descript] AS [S_IVMETH_X],
      x.[ATALLLIQUIDTOTAL],
      x.[ATGIFTTOTAL],
      x.[ATREONETPROCEEDSTOTAL],
      x.[BORROWED_DWNPMT_AMT],
      x.[LTNONSUBJDEBTMOTOTAL],
      x.[LTNONSUBJPAYOFFTOTAL],
      x.[S_CBSOURCE],
      A6.[Descript] AS [S_CBSOURCE_X],
      x.[VETERAN],
      x.[ENTITLEMENT],
      x.[LDP_NUMBER],
      x.[GSA_NUMBER],
      x.[FOREIGN_NATIONAL],
      x.[COUNTRY_OF_INCORP],
      x.[EIN],
      x.[NLR_NAME],
      x.[NLR_REL_DESC],
      x.[NLR_PHONE],
      x.[NLR_ADDR1],
      x.[NLR_ADDR2],
      x.[NLR_CITY],
      x.[NLR_STATE],
      x.[NLR_POSTALCODE],
      x.[EXEMPTSSN],
      x.[FHA_CLASSIFICATION],
      A7.[Descript] AS [FHA_CLASSIFICATION_X],
      x.[LDP_YN],
      x.[GSA_YN],
      x.[OVERALL_CS_SOURCE],
      x.[DISPLAY_NAME],
      x.[NON_INDIV_BORR_NAME],
      x.[S_LEGAL_ENTITY_TYPE],
      A8.[Descript] AS [S_LEGAL_ENTITY_TYPE_X],
      x.[S_LEGAL_ENTITY_TYP_OTH],
      A9.[Descript] AS [S_LEGAL_ENTITY_TYP_OTH_X],
      x.[ULDD_TAXPAYER_ID],
      x.[INCLUDE_IN_PROFORMA],
      x.[FADDR_INDICATOR],
      x.[DBA_NAME],
      x.[STATE_OF_INCORP],
      x.[INMILITARY],
      x.[BORRDISABLD],
      x.[RECORD_CREATED],
      x.[HUD_APPROVED],
      x.[VERIFYSSN],
      x.[BORR_CS_RANK_PERCENT],
      x.[YRS_AT_PRSNT],
      x.[MNTHS_AT_PRSNT],
      x.[BORR_COVERED],
      x.[S_COV_BORR_STATUS],
      A10.[Descript] AS [S_COV_BORR_STATUS_X],
      x.[BORR_VERBDISC],
      x.[MLACERTID],
      x.[S_BOR_UNIT_TYPE],
      A11.[Descript] AS [S_BOR_UNIT_TYPE_X],
      x.[BOR_UNIT_NUM],
      x.[BOR_COUNTRY],
      x.[BOR_COUNTRY_CODE],
      x.[BORR_QUAL_INC_SOURCE],
      x.[CREDIT_SCORE_MODEL],
      x.[CREDITSCORE_MODEL_OTHDESC],
      x.[BORR_FRAUD_SCORE],
      x.[FURNISH_GENDER_INFO_YN],
      x.[COLLD_BY_OBSRVTION_GENDER_YN],
      x.[COLLD_BY_OBSRVTION_RACE_YN],
      x.[COLLD_BY_OBSRVTION_ETH_YN],
      x.[SEX_MALE],
      x.[SEX_FEMALE],
      x.[COPIED_MAIL_ADDRESS],
      x.[CHECK_ALIAS],
      x.[S_PARTY_TYPE],
      A12.[Descript] AS [S_PARTY_TYPE_X],
      x.[S_CITIZENSHIP],
      A13.[Descript] AS [S_CITIZENSHIP_X],
      x.[S_UNMARRIED],
      A14.[Descript] AS [S_UNMARRIED_X],
      x.[ATTR_PORTAL_REG],
      x.[ATTR_COUNSELING_REQUIRED],
      x.[ATTR_CHILD_CARE],
      x.[ATTR_GUARANTOR],
      x.[ATTR_GUARDIANSHIP],
      x.[ATTR_SOLE_PROPRIETOR],
      x.[S_UNMARRIED_RLTNSHIP],
      A15.[Descript] AS [S_UNMARRIED_RLTNSHIP_X],
      x.[UNMARRIED_RLTNSHIP_STATE],
      x.[UNMARRIED_RLTNSHIP_OTHERDESC],
      x.[RETIRED_BORROWER],
      x.[BOR_STATE_FOREIGN],
      x.[BOR_POSTCODE],
      x.[COUNTRY_OF_INCORP_CODE],
      x.[EMAIL_CONSENT],
      x.[SMS_CONSENT],
      x.[OVERALL_CS_SOURCE_OVR],
      x.[IS_DEALER_EMPLOYEE],
      x.[LIVE_RENT_FREE_ENUMS],
      A16.[Descript] AS [LIVE_RENT_FREE_ENUMS_X]
   FROM [clt_NetO].[BORROWER] x
      LEFT JOIN [clt_NetO].[SymbolLookup] A0 on x.[S_MARITL] = A0.[DBSYMBOL] AND A0.[TableName] = 'BORROWER' and A0.[COLUMNNAME] = 'S_MARITL'
      LEFT JOIN [clt_NetO].[SymbolLookup] A1 on x.[GENDER] = A1.[DBSYMBOL] AND A1.[TableName] = 'BORROWER' and A1.[COLUMNNAME] = 'GENDER'
      LEFT JOIN [clt_NetO].[SymbolLookup] A2 on x.[S_OWNSHP] = A2.[DBSYMBOL] AND A2.[TableName] = 'BORROWER' and A2.[COLUMNNAME] = 'S_OWNSHP'
      LEFT JOIN [clt_NetO].[SymbolLookup] A3 on x.[S_BORTYP] = A3.[DBSYMBOL] AND A3.[TableName] = 'BORROWER' and A3.[COLUMNNAME] = 'S_BORTYP'
      LEFT JOIN [clt_NetO].[SymbolLookup] A4 on x.[S_VESTNG] = A4.[DBSYMBOL] AND A4.[TableName] = 'BORROWER' and A4.[COLUMNNAME] = 'S_VESTNG'
      LEFT JOIN [clt_NetO].[SymbolLookup] A5 on x.[S_IVMETH] = A5.[DBSYMBOL] AND A5.[TableName] = 'BORROWER' and A5.[COLUMNNAME] = 'S_IVMETH'
      LEFT JOIN [clt_NetO].[SymbolLookup] A6 on x.[S_CBSOURCE] = A6.[DBSYMBOL] AND A6.[TableName] = 'BORROWER' and A6.[COLUMNNAME] = 'S_CBSOURCE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A7 on x.[FHA_CLASSIFICATION] = A7.[DBSYMBOL] AND A7.[TableName] = 'BORROWER' and A7.[COLUMNNAME] = 'FHA_CLASSIFICATION'
      LEFT JOIN [clt_NetO].[SymbolLookup] A8 on x.[S_LEGAL_ENTITY_TYPE] = A8.[DBSYMBOL] AND A8.[TableName] = 'BORROWER' and A8.[COLUMNNAME] = 'S_LEGAL_ENTITY_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A9 on x.[S_LEGAL_ENTITY_TYP_OTH] = A9.[DBSYMBOL] AND A9.[TableName] = 'BORROWER' and A9.[COLUMNNAME] = 'S_LEGAL_ENTITY_TYP_OTH'
      LEFT JOIN [clt_NetO].[SymbolLookup] A10 on x.[S_COV_BORR_STATUS] = A10.[DBSYMBOL] AND A10.[TableName] = 'BORROWER' and A10.[COLUMNNAME] = 'S_COV_BORR_STATUS'
      LEFT JOIN [clt_NetO].[SymbolLookup] A11 on x.[S_BOR_UNIT_TYPE] = A11.[DBSYMBOL] AND A11.[TableName] = 'BORROWER' and A11.[COLUMNNAME] = 'S_BOR_UNIT_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A12 on x.[S_PARTY_TYPE] = A12.[DBSYMBOL] AND A12.[TableName] = 'BORROWER' and A12.[COLUMNNAME] = 'S_PARTY_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A13 on x.[S_CITIZENSHIP] = A13.[DBSYMBOL] AND A13.[TableName] = 'BORROWER' and A13.[COLUMNNAME] = 'S_CITIZENSHIP'
      LEFT JOIN [clt_NetO].[SymbolLookup] A14 on x.[S_UNMARRIED] = A14.[DBSYMBOL] AND A14.[TableName] = 'BORROWER' and A14.[COLUMNNAME] = 'S_UNMARRIED'
      LEFT JOIN [clt_NetO].[SymbolLookup] A15 on x.[S_UNMARRIED_RLTNSHIP] = A15.[DBSYMBOL] AND A15.[TableName] = 'BORROWER' and A15.[COLUMNNAME] = 'S_UNMARRIED_RLTNSHIP'
      LEFT JOIN [clt_NetO].[SymbolLookup] A16 on x.[LIVE_RENT_FREE_ENUMS] = A16.[DBSYMBOL] AND A16.[TableName] = 'BORROWER' and A16.[COLUMNNAME] = 'LIVE_RENT_FREE_ENUMS'
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
