-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO].[VwGF_TLR_RES_CREDIT_LIABILITY]
AS
   SELECT
      x.[LNUM],
      x.[DBID],
      x.[RESPONSEID],
      x.[CREDITRESPONSEID],
      x.[LIABILITYID],
      x.[PRIMARY_BNUM],
      x.[PRIMARY_DBID],
      x.[SECONDARY_BNUM],
      x.[SECONDARY_DBID],
      x.[CREDIT_TRADEID],
      x.[CLOSE_DATE],
      x.[ACCOUNT_IDENTIFIER],
      x.[OPENED_DATE],
      x.[OWNERSHIP_TYPE],
      x.[PAID_DATE],
      x.[REPORTED_DATE],
      x.[STATUS_DATE],
      x.[ACCOUNT_STATUS_TYPE],
      x.[ACCOUNT_TYPE],
      x.[BALLOON_PAYMENT],
      x.[CHARGE_OFF_AMOUNT],
      x.[CHARGE_OFF_DATE],
      x.[COLATERAL_DESC],
      x.[CONSUMER_DISPUTE_INDC],
      HASHBYTES('SHA2_256', CAST(x.[CREDIT_LIMIT_AMOUNT] AS NVARCHAR(50))) AS [CREDIT_LIMIT_AMOUNT],
      x.[DEROGATORY_INDC],
      x.[HIGH_BALANCE],
      x.[HIGH_CREDIT],
      x.[LAST_ACTIVITY_DATE],
      x.[MANUAL_UPDATE_INDC],
      x.[MONTHLY_AMOUNT],
      x.[MONTHS_REMAINING],
      x.[MONTHS_REVIEWED],
      x.[ORIGINAL_CREDITOR_NAME],
      x.[PAST_DUE_AMOUNT],
      x.[TERMS_DESC],
      x.[TERMS_MONTHS],
      x.[TERMS_SOURCE_TYPE],
      x.[UNPAID_BALANCE],
      x.[CREDIT_BUSINESS_TYPE],
      x.[CREDIT_LOAN_TYPE],
      x.[CREDIT_LOAN_OTHER_DESC],
      x.[CURRENT_RATING_CODE],
      x.[CURRENT_RATING_TYPE],
      x.[LATE_30_DAYS],
      x.[LATE_60_DAYS],
      x.[LATE_90_DAYS],
      x.[RECENT_ADVERSE_AMOUNT],
      x.[RECENT_ADVERSE_CODE],
      x.[RECENT_ADVERSE_TYPE],
      x.[RECENT_ADVERSE_DATE],
      x.[PATTERN_START_DATE],
      x.[PAYMENT_PATTERN],
      x.[VERIFY_BY_NAME],
      x.[VERIFY_COMMENT],
      x.[VERIFY_DATE],
      x.[VERIFY_STATUS_TYPE],
      x.[LATE120DAYS],
      x.[CREDITLIABILITYID],
      x.[ACCOUNTBALANCEDATE],
      x.[BALLOONPAYMENTDUEDATE],
      x.[HIGHEST_ADVERSE_AMOUNT],
      x.[HIGHEST_ADVERSE_CODE],
      x.[HIGHEST_ADVERSE_TYPE],
      x.[HIGHEST_ADVERSE_DATE],
      x.[CREDITCOUNSELINGINDICATOR]
   FROM [clt_NetO].[GF_TLR_RES_CREDIT_LIABILITY] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
