-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO].[VwWG_LOAN_EXCEPTIONS]
AS
   SELECT
      x.[LNUM],
      x.[DBID],
      x.[ROWSERIALNO],
      x.[S_EXCEPTION_TYPE],
      A0.Descript AS [EXCEPTION_TYPE],
      x.[S_EXCEPTION_STATUS],
      A1.Descript AS [EXCEPTION_STATUS],
      x.[S_EXCEPTION_REASON],
      A2.Descript AS [EXCEPTION_REASON],
      x.[EXCEPTION_RATE],
      x.[EXCEPTION_POINTS],
      x.[EXCEPTION_REQUESTED_BY_CID],
      x.[EXCEPTION_REQUESTED_DATE],
      x.[EXCEPTION_REQUEST_NOTE],
      x.[EXCEPTION_REFERENCE_ID],
      x.[WORKFLOW_PROCESS_MODEL_ID],
      x.[S_APPROVER1_CMSTYPE],
      A3.Descript AS [APPROVER1_CMSTYPE],
      x.[APPROVER1_CID],
      x.[S_APPROVER1_DECISION],
      A4.Descript AS [APPROVER1_DECISION],
      x.[APPROVER1_DECISION_DATE],
      x.[APPROVER1_NOTE],
      x.[S_APPROVER2_CMSTYPE],
      A5.Descript AS [APPROVER2_CMSTYPE],
      x.[APPROVER2_CID],
      x.[S_APPROVER2_DECISION],
      A6.Descript AS [APPROVER2_DECISION],
      x.[APPROVER2_DECISION_DATE],
      x.[APPROVER2_NOTE],
      x.[S_APPROVER3_CMSTYPE],
      A7.Descript AS [APPROVER3_CMSTYPE],
      x.[APPROVER3_CID],
      x.[S_APPROVER3_DECISION],
      A8.Descript AS [APPROVER3_DECISION],
      x.[APPROVER3_DECISION_DATE],
      x.[APPROVER3_NOTE],
      x.[S_CANNED_REASON],
      A9.Descript AS [CANNED_REASON],
      x.[EXC_REQ_DISC_PCT],
      x.[EXC_REQ_RATE_PCT],
      x.[EXC_REQ_MARGIN_PCT],
      x.[S_EXCEPTION_CATEGORY],
      A10.Descript AS [EXCEPTION_CATEGORY],
      x.[S_APPR1_EXC_REASON1],
      A11.Descript AS [APPR1_EXC_REASON1],
      x.[S_APPR2_EXC_REASON1],
      A12.Descript AS [APPR2_EXC_REASON1],
      x.[S_APPR3_EXC_REASON1],
      A13.Descript AS [APPR3_EXC_REASON1],
      x.[S_APPR1_EXC_REASON2],
      A14.Descript AS [APPR1_EXC_REASON2],
      x.[S_APPR2_EXC_REASON2],
      A15.Descript AS [APPR2_EXC_REASON2],
      x.[S_APPR3_EXC_REASON2],
      A16.Descript AS [APPR3_EXC_REASON2],
      x.[S_APPR1_EXC_REASON3],
      A17.Descript AS [APPR1_EXC_REASON3],
      x.[S_APPR2_EXC_REASON3],
      A18.Descript AS [APPR2_EXC_REASON3],
      x.[S_APPR3_EXC_REASON3],
      A19.Descript AS [APPR3_EXC_REASON3],
      x.[S_APPR1_DEC_REASON],
      A20.Descript AS [APPR1_DEC_REASON],
      x.[S_APPR2_DEC_REASON],
      A21.Descript AS [APPR2_DEC_REASON],
      x.[S_APPR3_DEC_REASON],
      A22.Descript AS [APPR3_DEC_REASON],
      x.[S_APPR1_DEC_REASON1],
      A23.Descript AS [APPR1_DEC_REASON1],
      x.[S_APPR1_DEC_REASON2],
      A24.Descript AS [APPR1_DEC_REASON2],
      x.[S_APPR2_DEC_REASON1],
      A25.Descript AS [APPR2_DEC_REASON1],
      x.[S_APPR2_DEC_REASON2],
      A26.Descript AS [APPR2_DEC_REASON2],
      x.[S_APPR3_DEC_REASON1],
      A27.Descript AS [APPR3_DEC_REASON1],
      x.[S_APPR3_DEC_REASON2],
      A28.Descript AS [APPR3_DEC_REASON2],
      x.[S_APPR1_EXC_REASON_DTL1],
      A29.Descript AS [APPR1_EXC_REASON_DTL1],
      x.[S_APPR2_EXC_REASON_DTL1],
      A30.Descript AS [APPR2_EXC_REASON_DTL1],
      x.[S_APPR3_EXC_REASON_DTL1],
      A31.Descript AS [APPR3_EXC_REASON_DTL1],
      x.[S_APPR1_EXC_REASON_DTL2],
      A32.Descript AS [APPR1_EXC_REASON_DTL2],
      x.[S_APPR2_EXC_REASON_DTL2],
      A33.Descript AS [APPR2_EXC_REASON_DTL2],
      x.[S_APPR3_EXC_REASON_DTL2],
      A34.Descript AS [APPR3_EXC_REASON_DTL2],
      x.[S_APPR1_EXC_REASON_DTL3],
      A35.Descript AS [APPR1_EXC_REASON_DTL3],
      x.[S_APPR2_EXC_REASON_DTL3],
      A36.Descript AS [APPR2_EXC_REASON_DTL3],
      x.[S_APPR3_EXC_REASON_DTL3],
      A37.Descript AS [APPR3_EXC_REASON_DTL3],
      x.[EXC_REQ_INTRO_RATE],
      x.[EXC_REQ_ANNUAL_FEE],
      x.[EXC_REQ_DURATION],
      x.[EXC_REQ_WAIVE_ANN_FEE]
   FROM [clt_NetO].[WG_LOAN_EXCEPTIONS] x
      LEFT JOIN [clt_NetO].[SymbolLookup] A0 on x.[S_EXCEPTION_TYPE] = A0.[DBSYMBOL] AND A0.[TableName] = 'WG_LOAN_EXCEPTIONS' and A0.[COLUMNNAME] = 'S_EXCEPTION_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A1 on x.[S_EXCEPTION_STATUS] = A1.[DBSYMBOL] AND A1.[TableName] = 'WG_LOAN_EXCEPTIONS' and A1.[COLUMNNAME] = 'S_EXCEPTION_STATUS'
      LEFT JOIN [clt_NetO].[SymbolLookup] A2 on x.[S_EXCEPTION_REASON] = A2.[DBSYMBOL] AND A2.[TableName] = 'WG_LOAN_EXCEPTIONS' and A2.[COLUMNNAME] = 'S_EXCEPTION_REASON'
      LEFT JOIN [clt_NetO].[SymbolLookup] A3 on x.[S_APPROVER1_CMSTYPE] = A3.[DBSYMBOL] AND A3.[TableName] = 'WG_LOAN_EXCEPTIONS' and A3.[COLUMNNAME] = 'S_APPROVER1_CMSTYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A4 on x.[S_APPROVER1_DECISION] = A4.[DBSYMBOL] AND A4.[TableName] = 'WG_LOAN_EXCEPTIONS' and A4.[COLUMNNAME] = 'S_APPROVER1_DECISION'
      LEFT JOIN [clt_NetO].[SymbolLookup] A5 on x.[S_APPROVER2_CMSTYPE] = A5.[DBSYMBOL] AND A5.[TableName] = 'WG_LOAN_EXCEPTIONS' and A5.[COLUMNNAME] = 'S_APPROVER2_CMSTYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A6 on x.[S_APPROVER2_DECISION] = A6.[DBSYMBOL] AND A6.[TableName] = 'WG_LOAN_EXCEPTIONS' and A6.[COLUMNNAME] = 'S_APPROVER2_DECISION'
      LEFT JOIN [clt_NetO].[SymbolLookup] A7 on x.[S_APPROVER3_CMSTYPE] = A7.[DBSYMBOL] AND A7.[TableName] = 'WG_LOAN_EXCEPTIONS' and A7.[COLUMNNAME] = 'S_APPROVER3_CMSTYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A8 on x.[S_APPROVER3_DECISION] = A8.[DBSYMBOL] AND A8.[TableName] = 'WG_LOAN_EXCEPTIONS' and A8.[COLUMNNAME] = 'S_APPROVER3_DECISION'
      LEFT JOIN [clt_NetO].[SymbolLookup] A9 on x.[S_CANNED_REASON] = A9.[DBSYMBOL] AND A9.[TableName] = 'WG_LOAN_EXCEPTIONS' and A9.[COLUMNNAME] = 'S_CANNED_REASON'
      LEFT JOIN [clt_NetO].[SymbolLookup] A10 on x.[S_EXCEPTION_CATEGORY] = A10.[DBSYMBOL] AND A10.[TableName] = 'WG_LOAN_EXCEPTIONS' and A10.[COLUMNNAME] = 'S_EXCEPTION_CATEGORY'
      LEFT JOIN [clt_NetO].[SymbolLookup] A11 on x.[S_APPR1_EXC_REASON1] = A11.[DBSYMBOL] AND A11.[TableName] = 'WG_LOAN_EXCEPTIONS' and A11.[COLUMNNAME] = 'S_APPR1_EXC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A12 on x.[S_APPR2_EXC_REASON1] = A12.[DBSYMBOL] AND A12.[TableName] = 'WG_LOAN_EXCEPTIONS' and A12.[COLUMNNAME] = 'S_APPR2_EXC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A13 on x.[S_APPR3_EXC_REASON1] = A13.[DBSYMBOL] AND A13.[TableName] = 'WG_LOAN_EXCEPTIONS' and A13.[COLUMNNAME] = 'S_APPR3_EXC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A14 on x.[S_APPR1_EXC_REASON2] = A14.[DBSYMBOL] AND A14.[TableName] = 'WG_LOAN_EXCEPTIONS' and A14.[COLUMNNAME] = 'S_APPR1_EXC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A15 on x.[S_APPR2_EXC_REASON2] = A15.[DBSYMBOL] AND A15.[TableName] = 'WG_LOAN_EXCEPTIONS' and A15.[COLUMNNAME] = 'S_APPR2_EXC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A16 on x.[S_APPR3_EXC_REASON2] = A16.[DBSYMBOL] AND A16.[TableName] = 'WG_LOAN_EXCEPTIONS' and A16.[COLUMNNAME] = 'S_APPR3_EXC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A17 on x.[S_APPR1_EXC_REASON3] = A17.[DBSYMBOL] AND A17.[TableName] = 'WG_LOAN_EXCEPTIONS' and A17.[COLUMNNAME] = 'S_APPR1_EXC_REASON3'
      LEFT JOIN [clt_NetO].[SymbolLookup] A18 on x.[S_APPR2_EXC_REASON3] = A18.[DBSYMBOL] AND A18.[TableName] = 'WG_LOAN_EXCEPTIONS' and A18.[COLUMNNAME] = 'S_APPR2_EXC_REASON3'
      LEFT JOIN [clt_NetO].[SymbolLookup] A19 on x.[S_APPR3_EXC_REASON3] = A19.[DBSYMBOL] AND A19.[TableName] = 'WG_LOAN_EXCEPTIONS' and A19.[COLUMNNAME] = 'S_APPR3_EXC_REASON3'
      LEFT JOIN [clt_NetO].[SymbolLookup] A20 on x.[S_APPR1_DEC_REASON] = A20.[DBSYMBOL] AND A20.[TableName] = 'WG_LOAN_EXCEPTIONS' and A20.[COLUMNNAME] = 'S_APPR1_DEC_REASON'
      LEFT JOIN [clt_NetO].[SymbolLookup] A21 on x.[S_APPR2_DEC_REASON] = A21.[DBSYMBOL] AND A21.[TableName] = 'WG_LOAN_EXCEPTIONS' and A21.[COLUMNNAME] = 'S_APPR2_DEC_REASON'
      LEFT JOIN [clt_NetO].[SymbolLookup] A22 on x.[S_APPR3_DEC_REASON] = A22.[DBSYMBOL] AND A22.[TableName] = 'WG_LOAN_EXCEPTIONS' and A22.[COLUMNNAME] = 'S_APPR3_DEC_REASON'
      LEFT JOIN [clt_NetO].[SymbolLookup] A23 on x.[S_APPR1_DEC_REASON1] = A23.[DBSYMBOL] AND A23.[TableName] = 'WG_LOAN_EXCEPTIONS' and A23.[COLUMNNAME] = 'S_APPR1_DEC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A24 on x.[S_APPR1_DEC_REASON2] = A24.[DBSYMBOL] AND A24.[TableName] = 'WG_LOAN_EXCEPTIONS' and A24.[COLUMNNAME] = 'S_APPR1_DEC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A25 on x.[S_APPR2_DEC_REASON1] = A25.[DBSYMBOL] AND A25.[TableName] = 'WG_LOAN_EXCEPTIONS' and A25.[COLUMNNAME] = 'S_APPR2_DEC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A26 on x.[S_APPR2_DEC_REASON2] = A26.[DBSYMBOL] AND A26.[TableName] = 'WG_LOAN_EXCEPTIONS' and A26.[COLUMNNAME] = 'S_APPR2_DEC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A27 on x.[S_APPR3_DEC_REASON1] = A27.[DBSYMBOL] AND A27.[TableName] = 'WG_LOAN_EXCEPTIONS' and A27.[COLUMNNAME] = 'S_APPR3_DEC_REASON1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A28 on x.[S_APPR3_DEC_REASON2] = A28.[DBSYMBOL] AND A28.[TableName] = 'WG_LOAN_EXCEPTIONS' and A28.[COLUMNNAME] = 'S_APPR3_DEC_REASON2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A29 on x.[S_APPR1_EXC_REASON_DTL1] = A29.[DBSYMBOL] AND A29.[TableName] = 'WG_LOAN_EXCEPTIONS' and A29.[COLUMNNAME] = 'S_APPR1_EXC_REASON_DTL1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A30 on x.[S_APPR2_EXC_REASON_DTL1] = A30.[DBSYMBOL] AND A30.[TableName] = 'WG_LOAN_EXCEPTIONS' and A30.[COLUMNNAME] = 'S_APPR2_EXC_REASON_DTL1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A31 on x.[S_APPR3_EXC_REASON_DTL1] = A31.[DBSYMBOL] AND A31.[TableName] = 'WG_LOAN_EXCEPTIONS' and A31.[COLUMNNAME] = 'S_APPR3_EXC_REASON_DTL1'
      LEFT JOIN [clt_NetO].[SymbolLookup] A32 on x.[S_APPR1_EXC_REASON_DTL2] = A32.[DBSYMBOL] AND A32.[TableName] = 'WG_LOAN_EXCEPTIONS' and A32.[COLUMNNAME] = 'S_APPR1_EXC_REASON_DTL2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A33 on x.[S_APPR2_EXC_REASON_DTL2] = A33.[DBSYMBOL] AND A33.[TableName] = 'WG_LOAN_EXCEPTIONS' and A33.[COLUMNNAME] = 'S_APPR2_EXC_REASON_DTL2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A34 on x.[S_APPR3_EXC_REASON_DTL2] = A34.[DBSYMBOL] AND A34.[TableName] = 'WG_LOAN_EXCEPTIONS' and A34.[COLUMNNAME] = 'S_APPR3_EXC_REASON_DTL2'
      LEFT JOIN [clt_NetO].[SymbolLookup] A35 on x.[S_APPR1_EXC_REASON_DTL3] = A35.[DBSYMBOL] AND A35.[TableName] = 'WG_LOAN_EXCEPTIONS' and A35.[COLUMNNAME] = 'S_APPR1_EXC_REASON_DTL3'
      LEFT JOIN [clt_NetO].[SymbolLookup] A36 on x.[S_APPR2_EXC_REASON_DTL3] = A36.[DBSYMBOL] AND A36.[TableName] = 'WG_LOAN_EXCEPTIONS' and A36.[COLUMNNAME] = 'S_APPR2_EXC_REASON_DTL3'
      LEFT JOIN [clt_NetO].[SymbolLookup] A37 on x.[S_APPR3_EXC_REASON_DTL3] = A37.[DBSYMBOL] AND A37.[TableName] = 'WG_LOAN_EXCEPTIONS' and A37.[COLUMNNAME] = 'S_APPR3_EXC_REASON_DTL3'
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
