-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO].[VwWG_CRM_CUSTOMER_ACCT_DETAIL]
AS
   SELECT
      HASHBYTES('SHA2_256', x.[CURRENT_CUSTOMERID]) AS [CURRENT_CUSTOMERID],
      x.[ACC_TYPE],
      HASHBYTES('SHA2_256', CAST(x.[ROWSERIALNO] AS NVARCHAR(50))) AS [ROWSERIALNO],
      HASHBYTES('SHA2_256', x.[ACCTNUM]) AS [ACCTNUM],
      x.[MINORCODE],
      HASHBYTES('SHA2_256', CAST(x.[ACCTBAL] AS NVARCHAR(50))) AS [ACCTBAL],
      HASHBYTES('SHA2_256', x.[BANKRUPTCY]) AS [BANKRUPTCY],
      x.[ACCT_CHOFF],
      x.[ACCT_CHOFFPAID],
      x.[LIMITREMOVED],
      x.[LOANACCT_BUCODE],
      x.[LOANACCT_LIMIT],
      HASHBYTES('SHA2_256', CAST(x.[HIGH_CREDIT] AS NVARCHAR(50))) AS [HIGH_CREDIT],
      x.[INTEREST_RATE],
      HASHBYTES('SHA2_256', CAST(x.[DEBTPAYOFFTHRUDT] AS NVARCHAR(50))) AS [DEBTPAYOFFTHRUDT],
      x.[ORIGDBTDT],
      x.[LOANACCT_LIMIT_SUSP],
      x.[LOANACCT_DELINQUENCY],
      x.[LOANACCT_DAYSDELINQUENT],
      x.[LOANACCT_LOC],
      x.[SECURED],
      HASHBYTES('SHA2_256', CAST(x.[MTHPYMT] AS NVARCHAR(50))) AS [MTHPYMT],
      x.[LOANACCT_LIMIT_MAINTENANCEDT],
      x.[LOANACCT_PREV_BAL],
      x.[LOANACCT_PREV_BAL_6MNTHS],
      x.[LINEOF_CREDITEXISTS],
      x.[LOANACCT_PRIMARY_HOLDER],
      x.[LOANACCT_TYPE],
      x.[LOANACCT_OBLIGATION],
      HASHBYTES('SHA2_256', x.[DEPACCT_PRIMARY_HOLDER]) AS [DEPACCT_PRIMARY_HOLDER],
      x.[ACCOUNT_QUALIFICATIONS],
      x.[ISONLINE_BANKINGUSER]
   FROM [clt_NetO].[WG_CRM_CUSTOMER_ACCT_DETAIL] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
;
