-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO].[VwWG_INCOME_SOURCE]
AS
   SELECT
      x.[LNUM],
      x.[DBID],
      x.[BNUM],
      x.[INC_SRC_CTR],
      x.[RECORD_CREATED],
      x.[S_INCOME_SOURCE_TYPE],
      HASHBYTES('SHA2_256', x.[OTHER_INCOME_SRC_DESC]) AS [OTHER_INCOME_SRC_DESC],
      x.[S_BUSINESS_TYPE],
      HASHBYTES('SHA2_256', x.[SOURCE_NAME]) AS [SOURCE_NAME],
      HASHBYTES('SHA2_256', x.[SOURCE_CONTACT]) AS [SOURCE_CONTACT],
      HASHBYTES('SHA2_256', x.[ADDRESS_LN_1]) AS [ADDRESS_LN_1],
      HASHBYTES('SHA2_256', x.[ADDRESS_LN_2]) AS [ADDRESS_LN_2],
      HASHBYTES('SHA2_256', x.[CITY]) AS [CITY],
      HASHBYTES('SHA2_256', x.[INC_STATE]) AS [INC_STATE],
      HASHBYTES('SHA2_256', x.[ZIPCODE]) AS [ZIPCODE],
      HASHBYTES('SHA2_256', x.[COUNTRY]) AS [COUNTRY],
      HASHBYTES('SHA2_256', x.[PHONE]) AS [PHONE],
      HASHBYTES('SHA2_256', x.[PHONE_EXT]) AS [PHONE_EXT],
      x.[FAX_NBR],
      x.[TITLE],
      x.[S_SPECIAL_BOR_EMP_REL_TYPE],
      A0.[Descript] AS [S_SPECIAL_BOR_EMP_REL_TYPE_X],
      x.[SPEC_BOR_EMP_REL_TYPE_DESC],
      HASHBYTES('SHA2_256', x.[OCCUPATION]) AS [OCCUPATION],
      HASHBYTES('SHA2_256', CAST(x.[EMPLOYED_FROM] AS NVARCHAR(50))) AS [EMPLOYED_FROM],
      HASHBYTES('SHA2_256', CAST(x.[EMPLOYED_TO] AS NVARCHAR(50))) AS [EMPLOYED_TO],
      HASHBYTES('SHA2_256', CAST(x.[YEARS_AT_JOB] AS NVARCHAR(50))) AS [YEARS_AT_JOB],
      HASHBYTES('SHA2_256', x.[SUPERVISOR_NAME]) AS [SUPERVISOR_NAME],
      x.[INC_SRC_EMP_ID],
      x.[SELF_EMPLOYED_FLAG],
      x.[PCT_BUSINESS_OWNED],
      x.[S_SELF_EMPL_TYPE],
      A1.[Descript] AS [S_SELF_EMPL_TYPE_X],
      x.[PROF_MONTHS],
      x.[PROF_YEARS],
      HASHBYTES('SHA2_256', CAST(x.[BASE_INCOME] AS NVARCHAR(50))) AS [BASE_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[BONUS_INCOME] AS NVARCHAR(50))) AS [BONUS_INCOME],
      x.[COMMISSION_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[OVERTIME_INCOME] AS NVARCHAR(50))) AS [OVERTIME_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[MILITARY_INCOME] AS NVARCHAR(50))) AS [MILITARY_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_INCOME] AS NVARCHAR(50))) AS [OTHER_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[TOTAL_INCOME] AS NVARCHAR(50))) AS [TOTAL_INCOME],
      x.[LIABCTR],
      x.[S_EMP_UNIT_TYPE],
      A2.[Descript] AS [S_EMP_UNIT_TYPE_X],
      HASHBYTES('SHA2_256', x.[EMP_UNIT_NUMBER]) AS [EMP_UNIT_NUMBER],
      HASHBYTES('SHA2_256', x.[INCOME_STATE_FOREIN]) AS [INCOME_STATE_FOREIN],
      HASHBYTES('SHA2_256', x.[INCOME_POSTCODE]) AS [INCOME_POSTCODE],
      HASHBYTES('SHA2_256', x.[EMP_CNTRY_COD]) AS [EMP_CNTRY_COD],
      HASHBYTES('SHA2_256', x.[EMP_COUNTRY]) AS [EMP_COUNTRY],
      x.[INC_STMT_IND],
      HASHBYTES('SHA2_256', CAST(x.[BUSINESS_INCOME] AS NVARCHAR(50))) AS [BUSINESS_INCOME],
      x.[VOE_DT],
      x.[INC_STMT_EMP_ID],
      HASHBYTES('SHA2_256', x.[INC_DBA_NAME]) AS [INC_DBA_NAME],
      HASHBYTES('SHA2_256', x.[INC_EIN]) AS [INC_EIN]
   FROM [clt_NetO].[WG_INCOME_SOURCE] x
      LEFT JOIN [clt_NetO].[SymbolLookup] A0 on x.[S_SPECIAL_BOR_EMP_REL_TYPE] = A0.[DBSYMBOL] AND A0.[TableName] = 'WG_INCOME_SOURCE' and A0.[COLUMNNAME] = 'S_SPECIAL_BOR_EMP_REL_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A1 on x.[S_SELF_EMPL_TYPE] = A1.[DBSYMBOL] AND A1.[TableName] = 'WG_INCOME_SOURCE' and A1.[COLUMNNAME] = 'S_SELF_EMPL_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A2 on x.[S_EMP_UNIT_TYPE] = A2.[DBSYMBOL] AND A2.[TableName] = 'WG_INCOME_SOURCE' and A2.[COLUMNNAME] = 'S_EMP_UNIT_TYPE'
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
