-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLR_INSURANCE]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [ROWSERIALNO]                      int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [S_INSTYPE]                        nvarchar(8)          NULL,
   [COVAMNT]                          decimal(18,3)        NULL,
   [MINCOVER]                         decimal(18,3)        NULL,
   [PREMAMT]                          decimal(18,3)        NULL,
   [COVERPER]                         int                  NULL,
   [POLICYNO]                         nvarchar(20)         NULL,
   [FILENUM]                          nvarchar(20)         NULL,
   [EFFINSDT]                         datetime             NULL,
   [INSEXPDT]                         datetime             NULL,
   [BINDEXPD]                         datetime             NULL,
   [PAYEECDE]                         nvarchar(20)         NULL,
   [ESCRITEM]                         nchar(1)             NULL,
   [COMPNAME]                         nvarchar(35)         NULL,
   [INSADDR1]                         nvarchar(35)         NULL,
   [INSADDR2]                         nvarchar(35)         NULL,
   [INSCITY]                          nvarchar(25)         NULL,
   [INSSTATE]                         nvarchar(2)          NULL,
   [INSZIP]                           nvarchar(10)         NULL,
   [INSPHONE]                         nvarchar(10)         NULL,
   [INSFAX]                           nvarchar(10)         NULL,
   [AGENTNAME]                        nvarchar(100)        NULL,
   [GUAR_REPL_COST]                   nchar(1)             NULL,
   [INSURANCE_TERM]                   nvarchar(8)          NULL,
   [NEXT_DUE_DATE]                    datetime             NULL,
   [INS_PAID_RECEIPT]                 nchar(1)             NULL,
   [INS_DEDUCTIBLE]                   decimal(18,3)        NULL,
   [COVERAGETYPEDESC]                 nvarchar(255)        NULL,
   [CUSHION]                          decimal(16,6)        NULL,
   [MASTER_POLICY_IND]                nchar(1)             NULL,
   [COLFIRSTYR]                       nchar(1)             NULL,
   [RATE_CHARGED_ON_COST]             decimal(16,6)        NULL,
   [PMTOPTDBID]                       nchar(5)             NULL,
   [PMTOPTSERNO]                      int                  NULL,
   [S_OTH_INS_TYPE_DESC]              nvarchar(60)         NULL,
   [HUDLINE]                          smallint             NULL,
   [POLICY_TERM]                      int                  NULL,
   [S_ESCINS]                         nvarchar(8)          NULL,
   [ASSETID]                          int                  NULL,
   [DT_ORDERED]                       datetime             NULL,
   [DT_EXPECTED]                      datetime             NULL,
   [DT_RECEIVED]                      datetime             NULL,
   [COVG_RESOLUTION]                  nvarchar(8)          NULL,
   [INS_NOTES_DBID]                   nchar(5)             NULL,
   [INS_NOTES_SN]                     int                  NULL,
   [REPLACE_COST]                     numeric(16,6)        NULL,
   [DEDUCTIBLE]                       numeric(16,6)        NULL,
   [SECURED_PARTY_INS]                nvarchar(8)          NULL,
   [SECURED_PARTY_INS_OTH]            nvarchar(35)         NULL,
   [APIADDLINFO]                      nvarchar(80)         NULL,
   [INSEMAIL]                         nvarchar(128)        NULL,
   [CIDINS_PROVIDER]                  int                  NULL,
   [CIDINS_AGENT]                     int                  NULL,
   [PREPAID_INS_MNTH]                 int                  NULL,
   [IS_INS_POLICY_EXIST]              nchar(1)             NULL,
   [PREFIRM_CONSTRUCTION]             nchar(1)             NULL,
   [REPLACEMENT_VALUE]                decimal(18,3)        NULL,
   [NFIP_MAX_COVERAGE]                decimal(18,3)        NULL,
   [MINIMUM_COVERAGE]                 decimal(18,3)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
