-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TL_DATES3]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [VAAUTHEXPDT]                      datetime             NULL,
   [APPRAISER_ASSIGNED_DT]            datetime             NULL,
   [SCORECARD_DEC_DATE]               datetime             NULL,
   [ADV_ACTION_MAIL_DATE]             datetime             NULL,
   [UWEXPOVRD]                        datetime             NULL,
   [CREDIT_FILE_RECEIVED_DT]          datetime             NULL,
   [FILE_COMPLETE_DT]                 datetime             NULL,
   [CLOSING_PKG_RECEIVED_DT]          datetime             NULL,
   [LOAN_SPECIALIST_REVIEW_DT]        datetime             NULL,
   [CREDIT_REVIEW_DT]                 datetime             NULL,
   [APPROVED_W_CONDITIONS_DT]         datetime             NULL,
   [SENTPROC]                         datetime             NULL,
   [INTENT_TO_PROCEED_DT]             datetime             NULL,
   [COUNTER_OFFER_ACCEPT_DATE]        datetime             NULL,
   [COUNTER_OFFER_ISSUED]             datetime             NULL,
   [UNDERWRITING_RESUBMIT_DATE]       datetime             NULL,
   [NOTE_SENT_TO_SEC]                 datetime             NULL,
   [REGB_END_DATE]                    datetime             NULL,
   [CONSENT_DATE]                     datetime             NULL,
   [CONSENT_DECLINED_DATE]            datetime             NULL,
   [WHL_LOAN_REG_DATE]                datetime             NULL,
   [PREVREGB_END_DATE]                datetime             NULL,
   [HOMESTY_COMPLT_DATE]              datetime             NULL,
   [REHAB_COMPLETN_DATE]              datetime             NULL,
   [REMOVE_RECOUR_REQ_DATE]           datetime             NULL,
   [PRED_CLOSING_DT_AI_HLM]           datetime             NULL,
   [PC_NOTE_RXD_DT]                   datetime             NULL,
   [PC_NOTE_SENT_DT]                  datetime             NULL,
   [FINCONDT]                         datetime             NULL,
   [CREDIT_FILE_ACCEPTED_DT]          datetime             NULL,
   [CLOSING_PKG_ACCEPTED_DT]          datetime             NULL,
   [FINAL_NOTE]                       datetime             NULL,
   [ORIG_RECORDED_MTG]                datetime             NULL,
   [ALLONGE]                          datetime             NULL,
   [FINAL_TITLE_PLCY_RCVD_DATE]       datetime             NULL,
   [TRUST_ADDENDUM_POA]               datetime             NULL,
   [LOAN_IMPORT_UPDATE_COMP]          datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
