-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[HMDAINFO]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [DEBT2INC]                         nchar(1)             NULL,
   [EMPHIST]                          nchar(1)             NULL,
   [CRDHIST]                          nchar(1)             NULL,
   [COLLAT]                           nchar(1)             NULL,
   [NOCASH]                           nchar(1)             NULL,
   [UNVERIF]                          nchar(1)             NULL,
   [INCOMP]                           nchar(1)             NULL,
   [MIDENIED]                         nchar(1)             NULL,
   [OTHER]                            nchar(1)             NULL,
   [OTHERDSC]                         nvarchar(255)        NULL,
   [RLOANAMT]                         decimal(18,3)        NULL,
   [PURCHCD]                          int                  NULL,
   [EMPLOYEE]                         nchar(1)             NULL,
   [SUBMITREQUEST]                    nchar(1)             NULL,
   [HMDALOANTYPECODE]                 smallint             NULL,
   [HMDAPROPTYPECODE]                 smallint             NULL,
   [HMDALOANPURPCODE]                 smallint             NULL,
   [HMDAOOCODE]                       smallint             NULL,
   [HMDAREPORTABLELA]                 decimal(18,3)        NULL,
   [HMDAPREAPPREQUESTED]              smallint             NULL,
   [HMDAACTIONTAKENCODE]              smallint             NULL,
   [HMDAINFOREPORTABLEINCOME]         decimal(16,6)        NULL,
   [HMDARATESPREAD]                   decimal(16,6)        NULL,
   [HMDAHOEPASTATUS]                  smallint             NULL,
   [HMDALIENSTATUS]                   smallint             NULL,
   [BORRETHNICITY]                    smallint             NULL,
   [COBORRETHNICITY]                  smallint             NULL,
   [BORRRACE1]                        smallint             NULL,
   [BORRRACE2]                        smallint             NULL,
   [BORRRACE3]                        smallint             NULL,
   [BORRRACE4]                        smallint             NULL,
   [BORRRACE5]                        smallint             NULL,
   [COBORRRACE1]                      smallint             NULL,
   [COBORRRACE2]                      smallint             NULL,
   [COBORRRACE3]                      smallint             NULL,
   [COBORRRACE4]                      smallint             NULL,
   [COBORRRACE5]                      smallint             NULL,
   [BORRSEXCODE]                      smallint             NULL,
   [COBORRSEXCODE]                    smallint             NULL,
   [DENIALCODE1]                      smallint             NULL,
   [DENIALCODE2]                      smallint             NULL,
   [DENIALCODE3]                      smallint             NULL,
   [REPORTABLEYR]                     nvarchar(4)          NULL,
   [HMDAACTIONDATE]                   datetime             NULL,
   [DENYCODE1PRIORITY]                int                  NULL,
   [DENYCODE2PRIORITY]                int                  NULL,
   [DENYCODE3PRIORITY]                int                  NULL,
   [DENYCODE4PRIORITY]                int                  NULL,
   [DENYCODE5PRIORITY]                int                  NULL,
   [DENYCODE6PRIORITY]                int                  NULL,
   [DENYCODE7PRIORITY]                int                  NULL,
   [DENYCODE8PRIORITY]                int                  NULL,
   [DENYCODE9PRIORITY]                int                  NULL,
   [REPORTABLEYROVR]                  nvarchar(100)        NULL,
   [HMDAREPORTABLELAOVR]              decimal(16,6)        NULL,
   [MSACODE]                          nvarchar(6)          NULL,
   [STCODE]                           nvarchar(2)          NULL,
   [CYCODE]                           nvarchar(3)          NULL,
   [CENTRACT]                         nvarchar(8)          NULL,
   [ISANYBORRINCHMDARPTB]             nchar(1)             NULL,
   [HMDAREPORTABLEDESC]               nvarchar(50)         NULL,
   [APPDATEISNULL]                    nchar(4)             NULL,
   [LOCKDATEISNULL]                   nchar(4)             NULL,
   [RATESPREADISNULL]                 nchar(4)             NULL,
   [APPINCOMEISNULL]                  nchar(4)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
