-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[SEIA]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [TAXYEAR]                          int                  NOT NULL,
   [METHOD]                           nchar(1)             NOT NULL,
   [CNTR]                             int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [SCHCPRFT]                         decimal(18,3)        NULL,
   [SCHCDEPL]                         decimal(18,3)        NULL,
   [SCHCDEPR]                         decimal(18,3)        NULL,
   [SCHCPERD]                         decimal(18,3)        NULL,
   [SCHDGAIN]                         decimal(18,3)        NULL,
   [SCHFPRFT]                         decimal(18,3)        NULL,
   [SCHFDEPR]                         decimal(18,3)        NULL,
   [K1_1065]                          decimal(18,3)        NULL,
   [K1_1120S]                         decimal(18,3)        NULL,
   [EXPN2106]                         decimal(18,3)        NULL,
   [W2INCORP]                         decimal(18,3)        NULL,
   [ADJGRINC]                         decimal(18,3)        NULL,
   [WAGSALRY]                         decimal(18,3)        NULL,
   [TAXINTIN]                         decimal(18,3)        NULL,
   [TAXEXMIN]                         decimal(18,3)        NULL,
   [DIVNDINC]                         decimal(18,3)        NULL,
   [TAXREFND]                         decimal(18,3)        NULL,
   [ALIMONY]                          decimal(18,3)        NULL,
   [GAINRLOS]                         decimal(18,3)        NULL,
   [IRADISTB]                         decimal(18,3)        NULL,
   [PENSANNU]                         decimal(18,3)        NULL,
   [SCDEDEPR]                         decimal(18,3)        NULL,
   [UNEMPCOM]                         decimal(18,3)        NULL,
   [SSBENEFT]                         decimal(18,3)        NULL,
   [ODESC1]                           nvarchar(40)         NULL,
   [OAMOUNT1]                         decimal(18,3)        NULL,
   [ODESC2]                           nvarchar(40)         NULL,
   [OAMOUNT2]                         decimal(18,3)        NULL,
   [OATOTAL]                          decimal(18,3)        NULL,
   [INCSECTL]                         decimal(18,3)        NULL,
   [IRADEDUC]                         decimal(18,3)        NULL,
   [HALFSETX]                         decimal(18,3)        NULL,
   [SEHEALTH]                         decimal(18,3)        NULL,
   [KEOGHRET]                         decimal(18,3)        NULL,
   [EARLYPEN]                         decimal(18,3)        NULL,
   [ALIMNYPD]                         decimal(18,3)        NULL,
   [UNREBREX]                         decimal(18,3)        NULL,
   [AMORTIZT]                         decimal(18,3)        NULL,
   [A_TOTAL]                          decimal(18,3)        NULL,
   [B_TAXINC]                         decimal(18,3)        NULL,
   [B_TOTTAX]                         decimal(18,3)        NULL,
   [B_DEPRET]                         decimal(18,3)        NULL,
   [B_DEPLET]                         decimal(18,3)        NULL,
   [B_MORTNB]                         decimal(18,3)        NULL,
   [B_SUBT_1]                         decimal(18,3)        NULL,
   [B_PEROWN]                         decimal(16,6)        NULL,
   [B_SUBT_2]                         decimal(18,3)        NULL,
   [B_DIVIDN]                         decimal(18,3)        NULL,
   [B_TOTAL]                          decimal(18,3)        NULL,
   [C_DEPRET]                         decimal(18,3)        NULL,
   [C_DEPLET]                         decimal(18,3)        NULL,
   [C_MORTNB]                         decimal(18,3)        NULL,
   [C_SUBT_1]                         decimal(18,3)        NULL,
   [C_PEROWN]                         decimal(16,6)        NULL,
   [C_TOTAL]                          decimal(18,3)        NULL,
   [SALARY]                           decimal(18,3)        NULL,
   [ADDBACK]                          decimal(18,3)        NULL,
   [D_PEROWN]                         decimal(16,6)        NULL,
   [D_SUBT_1]                         decimal(18,3)        NULL,
   [D_NETPRF]                         decimal(18,3)        NULL,
   [D_PERON2]                         decimal(16,6)        NULL,
   [D_SUBT_2]                         decimal(18,3)        NULL,
   [D_TOTAL]                          decimal(18,3)        NULL,
   [NOMONTHS]                         int                  NULL,
   [MNTHAVRG]                         decimal(18,3)        NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [CTR]                              smallint             NOT NULL,
   [TOTINC]                           decimal(18,3)        NULL,
   [DEPR2106]                         decimal(18,3)        NULL,
   [SCHCOTHI]                         decimal(18,3)        NULL,
   [SCHCHOME]                         decimal(18,3)        NULL,
   [SCHCAMRT]                         decimal(18,3)        NULL,
   [GAIN479]                          decimal(18,3)        NULL,
   [NOTE6252]                         nchar(1)             NULL,
   [CONT6252]                         nchar(1)             NULL,
   [PRIN6252]                         decimal(18,3)        NULL,
   [E_ROYALY]                         nchar(1)             NULL,
   [E_RNTROY]                         decimal(18,3)        NULL,
   [E_XBDEPR]                         decimal(18,3)        NULL,
   [E_AMORT]                          decimal(18,3)        NULL,
   [E_IMITICL]                        decimal(18,3)        NULL,
   [F_ONCOOP]                         decimal(18,3)        NULL,
   [F_OTHINC]                         decimal(18,3)        NULL,
   [F_AMORTL]                         decimal(18,3)        NULL,
   [F_USHOME]                         decimal(18,3)        NULL,
   [NINL1065]                         decimal(18,3)        NULL,
   [GPYMT1065]                        decimal(18,3)        NULL,
   [K1_COND1]                         nchar(1)             NULL,
   [K1_COND2]                         nchar(1)             NULL,
   [K1_COND3]                         nchar(1)             NULL,
   [K1_NINCL]                         decimal(18,3)        NULL,
   [PASS1065]                         decimal(18,3)        NULL,
   [OTHI1065]                         decimal(18,3)        NULL,
   [DEPR1065]                         decimal(18,3)        NULL,
   [DEPL1065]                         decimal(18,3)        NULL,
   [AMOR1065]                         decimal(18,3)        NULL,
   [NOTE1065]                         decimal(18,3)        NULL,
   [MEAL1065]                         decimal(18,3)        NULL,
   [SUB_1065]                         decimal(18,3)        NULL,
   [OWNPERC]                          decimal(16,6)        NULL,
   [PARTTOTL]                         decimal(18,3)        NULL,
   [C_NRECUR]                         decimal(18,3)        NULL,
   [C_AMORTL]                         decimal(18,3)        NULL,
   [C_MEALET]                         decimal(18,3)        NULL,
   [B_RECURG]                         decimal(18,3)        NULL,
   [B_OTHINC]                         decimal(18,3)        NULL,
   [B_AMORTL]                         decimal(18,3)        NULL,
   [B_NOLASD]                         decimal(18,3)        NULL,
   [B_MEALET]                         decimal(18,3)        NULL,
   [EGAINLOS]                         decimal(18,3)        NULL,
   [CON11065]                         nchar(1)             NULL,
   [CON21065]                         nchar(1)             NULL,
   [CON31065]                         nchar(1)             NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [E_DEPLET]                         decimal(18,3)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
