-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[SELLER]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [SELCNTR]                          smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [FNAME]                            nvarchar(250)        NULL,
   [MNAME]                            nvarchar(25)         NULL,
   [LNAME]                            nvarchar(25)         NULL,
   [ADDR1]                            nvarchar(35)         NULL,
   [ADDR2]                            nvarchar(35)         NULL,
   [CITY]                             nvarchar(25)         NULL,
   [STATE]                            nchar(2)             NULL,
   [ZIP]                              nvarchar(10)         NULL,
   [PHONE]                            nvarchar(10)         NULL,
   [SSNTIN]                           nvarchar(11)         NULL,
   [PCTGP]                            decimal(16,6)        NULL,
   [TAXCREDT]                         decimal(18,3)        NULL,
   [NAME_SUFFIX]                      nvarchar(20)         NULL,
   [UNPARSED_NAME]                    nvarchar(250)        NULL,
   [NONPERSON_IND]                    nchar(1)             NULL,
   [CNTY]                             nvarchar(35)         NULL,
   [LDP_NUMBER]                       nvarchar(20)         NULL,
   [GSA_NUMBER]                       nvarchar(20)         NULL,
   [SELLER_WORK_PH]                   nvarchar(10)         NULL,
   [CONSIDERATION_INCL_SRVCS]         nchar(1)             NULL,
   [ACH_CID_BANK]                     int                  NULL,
   [ACH_ACCOUNT_TYPE]                 nvarchar(35)         NULL,
   [ACH_ACCOUNT_NUMBER]               nvarchar(35)         NULL,
   [AMOUNT_PROCEEDS]                  decimal(18,3)        NULL,
   [AMOUNT_PROCEEDS_OVRD]             decimal(18,3)        NULL,
   [ACH_BANK_ADDR_CNTR]               int                  NULL,
   [SELLER_ADDRESS_CNTR]              int                  NULL,
   [ACH_BANK_ADDR_ROWSERNO]           int                  NULL,
   [COUNTRY]                          nvarchar(35)         NULL,
   [POWER_OF_ATT]                     nvarchar(50)         NULL,
   [POWER_OF_ATT_DESC]                nvarchar(50)         NULL,
   [ESTABLISHED_STATE]                nchar(2)             NULL,
   [S_BOR_SELLER_OPTION]              nvarchar(8)          NULL,
   [S_SEL_UNIT_TYPE]                  nvarchar(8)          NULL,
   [SEL_UNIT_NUM]                     nvarchar(12)         NULL,
   [SEL_COUNTRY_CODE]                 nvarchar(2)          NULL,
   [SEL_STATE_FOREIN]                 nvarchar(200)        NULL,
   [SEL_POSTCODE]                     nvarchar(200)        NULL,
   [EMAIL]                            nvarchar(128)        NULL,
   [S_IDENTIFICATION_TYPE]            nvarchar(8)          NULL,
   [IDENTIFICATION_NUMBER]            nvarchar(35)         NULL,
   [SELLER_LIENHOLDER]                nvarchar(30)         NULL,
   [SELLER_CODE]                      int                  NULL,
   [SALES_TAX_ID]                     nvarchar(64)         NULL,
   [REGION]                           nvarchar(25)         NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
