-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_INCOME_SOURCE]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [INC_SRC_CTR]                      int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [S_INCOME_SOURCE_TYPE]             nchar(1)             NULL,
   [OTHER_INCOME_SRC_DESC]            nvarchar(40)         NULL,
   [S_BUSINESS_TYPE]                  nvarchar(30)         NULL,
   [SOURCE_NAME]                      nvarchar(50)         NULL,
   [SOURCE_CONTACT]                   nvarchar(35)         NULL,
   [ADDRESS_LN_1]                     nvarchar(35)         NULL,
   [ADDRESS_LN_2]                     nvarchar(35)         NULL,
   [CITY]                             nvarchar(35)         NULL,
   [INC_STATE]                        nchar(2)             NULL,
   [ZIPCODE]                          nvarchar(10)         NULL,
   [COUNTRY]                          nvarchar(35)         NULL,
   [PHONE]                            nvarchar(11)         NULL,
   [PHONE_EXT]                        nvarchar(6)          NULL,
   [FAX_NBR]                          nvarchar(11)         NULL,
   [TITLE]                            nvarchar(30)         NULL,
   [S_SPECIAL_BOR_EMP_REL_TYPE]       nvarchar(8)          NULL,
   [SPEC_BOR_EMP_REL_TYPE_DESC]       nvarchar(80)         NULL,
   [OCCUPATION]                       nvarchar(8)          NULL,
   [EMPLOYED_FROM]                    datetime             NULL,
   [EMPLOYED_TO]                      datetime             NULL,
   [YEARS_AT_JOB]                     decimal(18,3)        NULL,
   [SUPERVISOR_NAME]                  nvarchar(35)         NULL,
   [INC_SRC_EMP_ID]                   nvarchar(12)         NULL,
   [SELF_EMPLOYED_FLAG]               nchar(1)             NULL,
   [PCT_BUSINESS_OWNED]               decimal(16,6)        NULL,
   [S_SELF_EMPL_TYPE]                 nvarchar(8)          NULL,
   [PROF_MONTHS]                      int                  NULL,
   [PROF_YEARS]                       int                  NULL,
   [BASE_INCOME]                      decimal(18,3)        NULL,
   [BONUS_INCOME]                     decimal(18,3)        NULL,
   [COMMISSION_INCOME]                decimal(18,3)        NULL,
   [OVERTIME_INCOME]                  decimal(18,3)        NULL,
   [MILITARY_INCOME]                  decimal(18,3)        NULL,
   [OTHER_INCOME]                     decimal(18,3)        NULL,
   [TOTAL_INCOME]                     decimal(18,3)        NULL,
   [LIABCTR]                          int                  NULL,
   [S_EMP_UNIT_TYPE]                  nvarchar(8)          NULL,
   [EMP_UNIT_NUMBER]                  nvarchar(12)         NULL,
   [INCOME_STATE_FOREIN]              nvarchar(35)         NULL,
   [INCOME_POSTCODE]                  nvarchar(12)         NULL,
   [EMP_CNTRY_COD]                    nvarchar(12)         NULL,
   [EMP_COUNTRY]                      nvarchar(200)        NULL,
   [INC_STMT_IND]                     nchar(1)             NULL,
   [BUSINESS_INCOME]                  decimal(18,3)        NULL,
   [VOE_DT]                           datetime             NULL,
   [INC_STMT_EMP_ID]                  nvarchar(35)         NULL,
   [INC_DBA_NAME]                     nvarchar(45)         NULL,
   [INC_EIN]                          nvarchar(9)          NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
