-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_RPT_HMDA]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [REPORTABLE_YEAR]                  nchar(4)             NULL,
   [ACTION_DATE]                      datetime             NULL,
   [ACTION_TAKEN_CODE]                smallint             NULL,
   [ACTION_TAKEN]                     nvarchar(50)         NULL,
   [PURCHASER_TYPE_CODE]              int                  NULL,
   [PURCHASER_TYPE]                   nvarchar(50)         NULL,
   [LOAN_TYPE_CODE]                   smallint             NULL,
   [LOAN_TYPE]                        nvarchar(50)         NULL,
   [LOAN_PURPOSE_CODE]                smallint             NULL,
   [LOAN_PURPOSE]                     nvarchar(50)         NULL,
   [OWNER_OCCUPANCY_CODE]             smallint             NULL,
   [OWNER_OCCUPANCY]                  nvarchar(50)         NULL,
   [PREAPPRVL_REQ_TYPE_CODE]          smallint             NULL,
   [PREAPPRVL_REQ_TYPE]               nvarchar(50)         NULL,
   [RATE_SPREAD]                      numeric(16,6)        NULL,
   [HOEPA_STATUS_CODE]                smallint             NULL,
   [HOEPA_STATUS]                     nvarchar(50)         NULL,
   [LIEN_STATUS_CODE]                 smallint             NULL,
   [LIEN_STATUS]                      nvarchar(50)         NULL,
   [DENIAL_1_CODE]                    int                  NULL,
   [DENIAL_1]                         nvarchar(50)         NULL,
   [DENIAL_2_CODE]                    int                  NULL,
   [DENIAL_2]                         nvarchar(50)         NULL,
   [DENIAL_3_CODE]                    int                  NULL,
   [DENIAL_3]                         nvarchar(50)         NULL,
   [B1_SEX_CODE]                      smallint             NULL,
   [B1_SEX]                           nvarchar(50)         NULL,
   [B1_ETHNICITY_CODE]                smallint             NULL,
   [B1_ETHNICITY]                     nvarchar(50)         NULL,
   [B1_RACE_1_CODE]                   smallint             NULL,
   [B1_RACE_1]                        nvarchar(50)         NULL,
   [B1_RACE_2_CODE]                   smallint             NULL,
   [B1_RACE_2]                        nvarchar(50)         NULL,
   [B1_RACE_3_CODE]                   smallint             NULL,
   [B1_RACE_3]                        nvarchar(50)         NULL,
   [B1_RACE_4_CODE]                   smallint             NULL,
   [B1_RACE_4]                        nvarchar(50)         NULL,
   [B1_RACE_5_CODE]                   smallint             NULL,
   [B1_RACE_5]                        nvarchar(50)         NULL,
   [B2_SEX_CODE]                      smallint             NULL,
   [B2_SEX]                           nvarchar(50)         NULL,
   [B2_ETHNICITY_CODE]                smallint             NULL,
   [B2_ETHNICITY]                     nvarchar(50)         NULL,
   [B2_RACE_1_CODE]                   smallint             NULL,
   [B2_RACE_1]                        nvarchar(50)         NULL,
   [B2_RACE_2_CODE]                   smallint             NULL,
   [B2_RACE_2]                        nvarchar(50)         NULL,
   [B2_RACE_3_CODE]                   smallint             NULL,
   [B2_RACE_3]                        nvarchar(50)         NULL,
   [B2_RACE_4_CODE]                   smallint             NULL,
   [B2_RACE_4]                        nvarchar(50)         NULL,
   [B2_RACE_5_CODE]                   smallint             NULL,
   [B2_RACE_5]                        nvarchar(50)         NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
