-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwGF_TLR_DISCL_DATA]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[ROWSERIALNO] AS [ROWSERIALNO],
      x.[DBID] AS [DBID],
      x.[APR] AS [APR],
      x.[FINANCE_CHARGE_AMOUNT] AS [FINANCE_CHARGE_AMOUNT],
      x.[FINANCED_AMOUNT] AS [FINANCED_AMOUNT],
      x.[TOTAL_PAYMENT_AMOUNT] AS [TOTAL_PAYMENT_AMOUNT],
      x.[YSP_AMOUNT] AS [YSP_AMOUNT],
      x.[DISCL_LOAN_AMOUNT] AS [DISCL_LOAN_AMOUNT],
      x.[DISCL_CLOSING_COSTS] AS [DISCL_CLOSING_COSTS],
      x.[DISCL_REVIEW_TILA] AS [DISCL_REVIEW_TILA],
      x.[DISCL_LOAN_TYPE] AS [DISCL_LOAN_TYPE],
      x.[DISCL_PROGRAM] AS [DISCL_PROGRAM],
      x.[DISCL_PAYMENT_STREAM] AS [DISCL_PAYMENT_STREAM],
      x.[DISCL_MI_PLAN] AS [DISCL_MI_PLAN],
      x.[DISCL_OCCUPANCY] AS [DISCL_OCCUPANCY],
      x.[INT_RATE] AS [INT_RATE],
      x.[DISCL_BORROWER_COUNT] AS [DISCL_BORROWER_COUNT],
      x.[VERBALDISC] AS [VERBALDISC]
   FROM [clt_NetO].[GF_TLR_DISCL_DATA] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
