-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwWG_RPT_BORROWER]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[B_ORDER] AS [B_ORDER],
      x.[BNUM] AS [BNUM],
      x.[B_AGE] AS [B_AGE],
      x.[B_BORTYPE] AS [B_BORTYPE],
      x.[B_BORTYPE_DESC] AS [B_BORTYPE_DESC],
      HASHBYTES('SHA2_256', CAST(x.[B_DOB] AS NVARCHAR(50))) AS [B_DOB],
      HASHBYTES('SHA2_256', x.[B_EMAIL]) AS [B_EMAIL],
      x.[B_FIRST_TIME_YN] AS [B_FIRST_TIME_YN],
      x.[B_FOREIGN_NATL_YN] AS [B_FOREIGN_NATL_YN],
      HASHBYTES('SHA2_256', x.[B_GENDER]) AS [B_GENDER],
      HASHBYTES('SHA2_256', x.[B_HOME_PHONE]) AS [B_HOME_PHONE],
      HASHBYTES('SHA2_256', x.[B_MAIL_ADDR1]) AS [B_MAIL_ADDR1],
      HASHBYTES('SHA2_256', x.[B_MAIL_ADDR2]) AS [B_MAIL_ADDR2],
      HASHBYTES('SHA2_256', x.[B_MAIL_CITY]) AS [B_MAIL_CITY],
      HASHBYTES('SHA2_256', x.[B_MAIL_COUNTY]) AS [B_MAIL_COUNTY],
      HASHBYTES('SHA2_256', x.[B_MAIL_STATE]) AS [B_MAIL_STATE],
      HASHBYTES('SHA2_256', x.[B_MAIL_ZIP]) AS [B_MAIL_ZIP],
      HASHBYTES('SHA2_256', x.[B_MARITAL_STATUS]) AS [B_MARITAL_STATUS],
      HASHBYTES('SHA2_256', x.[B_MARITAL_STATUS_DESC]) AS [B_MARITAL_STATUS_DESC],
      HASHBYTES('SHA2_256', x.[B_NAME_FIRST]) AS [B_NAME_FIRST],
      HASHBYTES('SHA2_256', x.[B_NAME_LAST]) AS [B_NAME_LAST],
      HASHBYTES('SHA2_256', x.[B_NAME_MID]) AS [B_NAME_MID],
      x.[B_PRIMARY_YN] AS [B_PRIMARY_YN],
      HASHBYTES('SHA2_256', x.[B_RACE]) AS [B_RACE],
      HASHBYTES('SHA2_256', x.[B_RACE_DESC]) AS [B_RACE_DESC],
      HASHBYTES('SHA2_256', CAST(x.[B_SCORE] AS NVARCHAR(50))) AS [B_SCORE],
      HASHBYTES('SHA2_256', x.[B_SSN]) AS [B_SSN],
      x.[B_VETERAN_YN] AS [B_VETERAN_YN],
      HASHBYTES('SHA2_256', x.[B_WORK_PHONE]) AS [B_WORK_PHONE],
      x.[PROSPECT_CONTACT_METHOD] AS [PROSPECT_CONTACT_METHOD],
      x.[PROSPECT_OPTOUT] AS [PROSPECT_OPTOUT],
      x.[PROSPECT_STATUS] AS [PROSPECT_STATUS],
      x.[PROSPECT_STATUS_EXP] AS [PROSPECT_STATUS_EXP],
      x.[PROSPECT_TIME_TO_CALL] AS [PROSPECT_TIME_TO_CALL],
      x.[PROSPECT_YN] AS [PROSPECT_YN],
      x.[ETHNICITY] AS [ETHNICITY],
      x.[B_INTERVIEW_METHOD] AS [B_INTERVIEW_METHOD],
      x.[B_INTERVIEW_METHOD_DESC] AS [B_INTERVIEW_METHOD_DESC],
      x.[USA_CITIZEN_YN] AS [USA_CITIZEN_YN],
      HASHBYTES('SHA2_256', CAST(x.[B_SCORE_OVR] AS NVARCHAR(50))) AS [B_SCORE_OVR],
      x.[B_CELL_PHONE] AS [B_CELL_PHONE],
      HASHBYTES('SHA2_256', x.[EMAIL_CONSENT]) AS [EMAIL_CONSENT],
      x.[SMS_CONSENT] AS [SMS_CONSENT]
   FROM [clt_NetO].[WG_RPT_BORROWER] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
