-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[APPREQ]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [DBID]                             nchar(5)             NULL,
   [SERIALNO]                         int                  NULL,
   [LOTDIM1]                          decimal(16,6)        NULL,
   [LOTDIM2]                          decimal(16,6)        NULL,
   [IRREGLR]                          nchar(1)             NULL,
   [IRRGDSC]                          nvarchar(20)         NULL,
   [SQRFEET]                          decimal(16,6)        NULL,
   [ACREAGE]                          decimal(16,6)        NULL,
   [ELECUTL]                          nchar(1)             NULL,
   [GASUTL]                           nchar(1)             NULL,
   [WATRUTL]                          nchar(1)             NULL,
   [SANUTL]                           nchar(1)             NULL,
   [TTLLIMTS]                         nvarchar(40)         NULL,
   [STACCESS]                         nchar(1)             NULL,
   [STMAINT]                          nchar(1)             NULL,
   [RANGE]                            nchar(1)             NULL,
   [FRIDGE]                           nchar(1)             NULL,
   [DISHWASH]                         nchar(1)             NULL,
   [CLTHWASH]                         nchar(1)             NULL,
   [DRYER]                            nchar(1)             NULL,
   [DISPOSAL]                         nchar(1)             NULL,
   [VENTFAN]                          nchar(1)             NULL,
   [WWCARPET]                         nchar(1)             NULL,
   [OTHEREQP]                         nchar(1)             NULL,
   [OEQPDESC]                         nvarchar(20)         NULL,
   [BLDSTAT]                          nchar(1)             NULL,
   [BLDTYPE]                          nchar(1)             NULL,
   [COMPINSP]                         nchar(1)             NULL,
   [PLANS]                            nchar(1)             NULL,
   [WARINC]                           nchar(1)             NULL,
   [WARNAME]                          nvarchar(20)         NULL,
   [EXPDATE]                          datetime             NULL,
   [CNSTVRF]                          nchar(1)             NULL,
   [CNSTCOMP]                         datetime             NULL,
   [BLDGNUM]                          int                  NULL,
   [MINRITES]                         nchar(1)             NULL,
   [PROPOCC]                          nvarchar(15)         NULL,
   [OWNRNAME]                         nvarchar(20)         NULL,
   [MNTHRENT]                         decimal(18,3)        NULL,
   [OCCNAME]                          nvarchar(20)         NULL,
   [HOMEPHN]                          nvarchar(10)         NULL,
   [BUSPHONE]                         nvarchar(14)         NULL,
   [KEYSAT]                           nvarchar(40)         NULL,
   [TIMAVAIL]                         nvarchar(15)         NULL,
   [AMPMINSP]                         nchar(1)             NULL,
   [LEASEIS]                          nvarchar(15)         NULL,
   [ANNRENT]                          decimal(18,3)        NULL,
   [VACONTNO]                         nvarchar(20)         NULL,
   [PURCHSEP]                         nchar(1)             NULL,
   [CONATT]                           nchar(1)             NULL,
   [FACTORY]                          nchar(1)             NULL,
   [PLANNO]                           nvarchar(20)         NULL,
   [ESTATE]                           nchar(1)             NULL,
   [FLOODDESC]                        nvarchar(10)         NULL,
   [FLOODFLAG]                        nchar(1)             NULL,
   [WARADDR]                          nvarchar(40)         NULL,
   [WARPHONE]                         nvarchar(14)         NULL,
   [MINEXPLAN]                        nvarchar(20)         NULL,
   [ORIGID]                           nvarchar(20)         NULL,
   [SPONSID]                          nvarchar(20)         NULL,
   [INSTCASE]                         nvarchar(20)         NULL,
   [BRKNAME]                          nvarchar(20)         NULL,
   [BRKHPHN]                          nvarchar(10)         NULL,
   [BRKBPHN]                          nvarchar(14)         NULL,
   [SECNUM]                           nvarchar(50)         NULL,
   [ASSGNDT]                          datetime             NULL,
   [WARADDR2]                         nvarchar(40)         NULL,
   [WARCITY]                          nvarchar(40)         NULL,
   [WARSTATE]                         nchar(2)             NULL,
   [WARZIP]                           nvarchar(10)         NULL,
   [APPR_B2G_LIC_TYPE]                nvarchar(8)          NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
