-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[ASSETS]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [ASSETCTR]                         smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [S_ASSET]                          nvarchar(8)          NULL,
   [ASSETDSC]                         nvarchar(100)        NULL,
   [ACCTNUM]                          nvarchar(35)         NULL,
   [HOLDER]                           nvarchar(30)         NULL,
   [HADDR1]                           nvarchar(35)         NULL,
   [HADDR2]                           nvarchar(35)         NULL,
   [HCITY]                            nvarchar(25)         NULL,
   [HSTATE]                           nchar(2)             NULL,
   [HZIP]                             nvarchar(10)         NULL,
   [HPHONE]                           nvarchar(11)         NULL,
   [HEXT]                             nvarchar(5)          NULL,
   [HFAX]                             nvarchar(11)         NULL,
   [ATTNOF]                           nvarchar(30)         NULL,
   [ACCTBAL]                          decimal(18,3)        NULL,
   [ACCTIN]                           nvarchar(30)         NULL,
   [LIFEFACE]                         decimal(18,3)        NULL,
   [VERIFY]                           nchar(1)             NULL,
   [ISSUER]                           nvarchar(30)         NULL,
   [SHARES]                           decimal(16,6)        NULL,
   [DIVIDEND]                         decimal(18,3)        NULL,
   [OMIT]                             nchar(1)             NULL,
   [ASSETVERIFIED]                    nchar(1)             NULL,
   [AUTO_MAKE_DESC]                   nvarchar(80)         NULL,
   [AUTO_MODEL_YEAR]                  nvarchar(4)          NULL,
   [OTHERASSETTYPEDESC]               nvarchar(80)         NULL,
   [HCOUNTRY]                         nvarchar(35)         NULL,
   [ATS_ACCOUNT]                      nchar(1)             NULL,
   [ODP_ACCOUNT]                      nchar(1)             NULL,
   [ASSET_VERIFI_TYPE]                nvarchar(8)          NULL,
   [ASSET_VERI_TYPE_DESC]             nvarchar(80)         NULL,
   [ORDER_CHECK]                      nchar(1)             NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [FORMFREE_CTR]                     int                  NULL,
   [BUILDER_EARNEST]                  nchar(1)             NULL,
   [ASSET_INDICATOR]                  nchar(1)             NULL,
   [S_ACCOUNT_OWNERSHIP]              nvarchar(8)          NULL,
   [S_GIFT_PRVDR_TYPE]                nvarchar(8)          NULL,
   [GIFT_PRVDR_OTH_DESC]              nvarchar(80)         NULL,
   [GIFT_DEPOSIT_STATUS]              nchar(1)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
