-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[DOWNPYMT]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [DPYMTCTR]                         smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [S_TYPE]                           nvarchar(8)          NULL,
   [AMOUNT]                           decimal(18,3)        NULL,
   [NAME]                             nvarchar(30)         NULL,
   [ADDR1]                            nvarchar(35)         NULL,
   [ADDR2]                            nvarchar(35)         NULL,
   [CITY]                             nvarchar(25)         NULL,
   [STATE]                            nchar(2)             NULL,
   [ZIP]                              nvarchar(10)         NULL,
   [PHONE]                            nvarchar(10)         NULL,
   [RELATION]                         nvarchar(30)         NULL,
   [INCASS]                           nchar(1)             NULL,
   [FNDGIVEN]                         nchar(1)             NULL,
   [DTAVAIL]                          datetime             NULL,
   [FININST]                          nchar(1)             NULL,
   [ACCTNUM]                          nvarchar(35)         NULL,
   [BANKNAME]                         nvarchar(80)         NULL,
   [FIADDR1]                          nvarchar(35)         NULL,
   [FIADDR2]                          nvarchar(35)         NULL,
   [FICITY]                           nvarchar(25)         NULL,
   [FISTATE]                          nchar(2)             NULL,
   [FIZIP]                            nvarchar(10)         NULL,
   [FIACCTYP]                         nvarchar(8)          NULL,
   [VERIFYFND]                        nchar(1)             NULL,
   [OTHERDOWNPAYTYPEDESC]             nvarchar(80)         NULL,
   [S_DOWN_PMT_SRC_TYP]               nvarchar(8)          NULL,
   [S_DOWN_PMT_SRC_OTH]               nvarchar(8)          NULL,
   [S_DOWN_PMT_TYP]                   nvarchar(8)          NULL,
   [S_TYPE_OTH]                       nvarchar(8)          NULL,
   [PRIMARY_SRC]                      nchar(1)             NULL,
   [DOWNPAYMENTPERCENT]               decimal(16,6)        NULL,
   [S_DOWN_PMT_SRC]                   nvarchar(8)          NULL,
   [S_TYPENM]                         nvarchar(8)          NULL,
   [DOWNPAYTYPENMOTHERDESC]           nvarchar(80)         NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [TOTAL_GIFT_FUNDS]                 decimal(18,3)        NULL,
   [ASSETCTR]                         smallint             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
