-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLBR_EMPLOYER]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [EMPID]                            smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [TITLE]                            nvarchar(30)         NULL,
   [BUSTYPE]                          nvarchar(30)         NULL,
   [SUPERVSR]                         nvarchar(35)         NULL,
   [INCMNAME]                         nvarchar(50)         NULL,
   [ADDR1]                            nvarchar(35)         NULL,
   [ADDR2]                            nvarchar(35)         NULL,
   [CITY]                             nvarchar(35)         NULL,
   [STATE]                            nchar(2)             NULL,
   [ZIP]                              nvarchar(10)         NULL,
   [PHONE]                            nvarchar(11)         NULL,
   [PHONEXT]                          nvarchar(6)          NULL,
   [ATTNOF]                           nvarchar(35)         NULL,
   [FAXNO]                            nvarchar(11)         NULL,
   [ID]                               nvarchar(12)         NULL,
   [EMPDFROM]                         datetime             NULL,
   [EMPDTO]                           datetime             NULL,
   [YRSATJOB]                         smallint             NULL,
   [YRSINPRO]                         smallint             NULL,
   [PRIMARY_EMPLOYER]                 nchar(1)             NULL,
   [TYPEFLAG]                         nchar(1)             NULL,
   [SELFEMPL]                         nchar(1)             NULL,
   [PERCBUSOWN]                       decimal(16,6)        NULL,
   [S_JOB_TYPE]                       nvarchar(8)          NULL,
   [OVRTIME_CONT]                     nvarchar(25)         NULL,
   [PROB_CONT_EMPLOY]                 nvarchar(25)         NULL,
   [OTHERINCTYPEDESC]                 nvarchar(80)         NULL,
   [S_SPECBOREMPRELTYPE]              nvarchar(8)          NULL,
   [OTHERSPECBOREMPRELTYPEDSC]        nvarchar(80)         NULL,
   [IS_EMPLOYED_ABROAD]               nchar(1)             NULL,
   [COUNTRY]                          nvarchar(10)         NULL,
   [MONTHS_AT_JOB]                    smallint             NULL,
   [MONTHS_IN_PROFESSION]             smallint             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
