-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLBR_ADDITIONALDATA]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [ETHINICITY]                       nvarchar(8)          NULL,
   [CELL_PHONE]                       nvarchar(10)         NULL,
   [PRIM_CONTACT]                     nchar(1)             NULL,
   [S_FIRSTTIMEHBCOUNSEL]             nvarchar(8)          NULL,
   [S_TITLE]                          nvarchar(8)          NULL,
   [CURRENT_CUSTOMER]                 nchar(1)             NULL,
   [WORK_EXT]                         nvarchar(5)          NULL,
   [CREDIT_AUTHORIZATION_YN]          nchar(1)             NULL,
   [NATIONALITY]                      nvarchar(30)         NULL,
   [AFFILIATE]                        nchar(1)             NULL,
   [S_COUNSEL_CONFIRM_TYP]            nvarchar(8)          NULL,
   [S_COUNSEL_CONFIRM_OTH]            nvarchar(8)          NULL,
   [S_COUNSEL_FORMAT_TYP]             nvarchar(8)          NULL,
   [CREDIT_AUTHORIZATION_DATE]        datetime             NULL,
   [CUSTOMER_ID]                      nvarchar(15)         NULL,
   [S_CRDTSCORE_MODEL_OVR]            nvarchar(8)          NULL,
   [URLA_BESTCONTACT]                 nvarchar(20)         NULL,
   [URLA_ALTCONTACT]                  nvarchar(20)         NULL,
   [S_CREDIT_TYPE]                    nvarchar(8)          NULL,
   [JOINT_CREDIT_BNUM]                nvarchar(8)          NULL,
   [SPOUSE_FNAME]                     nvarchar(250)        NULL,
   [SPOUSE_MNAME]                     nvarchar(30)         NULL,
   [SPOUSE_LNAME]                     nvarchar(30)         NULL,
   [SPOUSE_ADD1]                      nvarchar(100)        NULL,
   [SPOUSE_ADD2]                      nvarchar(100)        NULL,
   [SPOUSE_CITY]                      nvarchar(25)         NULL,
   [SPOUSE_STATE]                     nchar(2)             NULL,
   [SPOUSE_ZIP]                       nvarchar(10)         NULL,
   [ATTR_BORROWER_ID]                 nchar(1)             NULL,
   [MARITALSTATUSYN]                  nchar(1)             NULL,
   [DATEOFCHANGEMS]                   datetime             NULL,
   [EXPLANATIONMS]                    nvarchar(80)         NULL,
   [ATTR_CAIVRS]                      nchar(1)             NULL,
   [ATTR_ESIGN]                       nchar(1)             NULL,
   [S_LANGUAGEPREFERENCE]             nvarchar(8)          NULL,
   [OTHER_LANGUAGE]                   nvarchar(50)         NULL,
   [CURRENTINCOTHERTOTAL]             decimal(18,3)        NULL,
   [CURRENTINCOMETOTAL]               decimal(18,3)        NULL,
   [TOTALCURRENTINCOME]               decimal(18,3)        NULL,
   [ATTR_SPOUSE_INFO]                 nchar(1)             NULL,
   [ON_NOTE_BORROWERS]                int                  NULL,
   [CALL_CONSENT_PREFER]              nchar(1)             NULL,
   [HASCHECKINGACCT_WITHCU]           nvarchar(8)          NULL,
   [HASSAVINGACCT_WITHCU]             nvarchar(8)          NULL,
   [CURRENT_CUSTOMERID]               nvarchar(30)         NULL,
   [ISCUSTOMER_STATUS_VERIFIED]       nvarchar(8)          NULL,
   [ISCURRENTCUSTOMER]                nvarchar(8)          NULL,
   [HMDA_DISC_NOTICE]                 nchar(1)             NULL,
   [CRDTSCORE_MODEL_OTHDESC_OVR]      nvarchar(100)        NULL,
   [PERSON_RECORD_FOUND]              nchar(1)             NULL,
   [MOTHERS_MAIDEN]                   nvarchar(100)        NULL,
   [APP_DISCL_READ]                   nchar(1)             NULL,
   [S_ELIGIBLE_TYPE]                  nvarchar(8)          NULL,
   [ELIGIBLE_CODE]                    nvarchar(20)         NULL,
   [ELIGIBLE_TEXT]                    nvarchar(400)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
