-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TL_PNP_IPG_DETAIL]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [INVESTOR_CODE]                    nvarchar(4)          NULL,
   [PRODUCT_CODE]                     nvarchar(4)          NULL,
   [PROGRAM_CODE]                     nvarchar(4)          NULL,
   [PRICE_GROUP_CODE]                 nvarchar(4)          NULL,
   [IPG_NAME]                         nvarchar(240)        NULL,
   [S_SEC_MANAGE_TYPE]                nvarchar(8)          NULL,
   [S_SEC_LOAN_TYPE]                  nvarchar(8)          NULL,
   [S_SEC_POOL_TYPE]                  nvarchar(8)          NULL,
   [S_PREPAY_PEN]                     nvarchar(8)          NULL,
   [OVER_ALLOW_PCT]                   decimal(16,6)        NULL,
   [SHORT_ALLOW_PCT]                  decimal(16,6)        NULL,
   [OVER_SPLIT_PCT]                   decimal(16,6)        NULL,
   [SHORT_SPLIT_PCT]                  decimal(16,6)        NULL,
   [REQUIRES_MERS]                    nchar(1)             NULL,
   [REQUIRES_MI]                      nchar(1)             NULL,
   [ONE_TIMECLOSE_CONST]              nchar(1)             NULL,
   [INTERIM_CONSTRUCTION]             nchar(1)             NULL,
   [ASSUMABLE]                        nchar(1)             NULL,
   [CONV_PERIOD_ST]                   smallint             NULL,
   [CONV_PERIOD_END]                  smallint             NULL,
   [EZD_PRODUCT]                      nchar(1)             NULL,
   [HMDA_REPORTABLE]                  nchar(1)             NULL,
   [BUYDOWN_ALLOWED]                  nchar(1)             NULL,
   [HELOC_ALLOW_YN]                   nchar(1)             NULL,
   [PROD_PROF_TRUE]                   nchar(1)             NULL,
   [PRICE_NAME]                       nvarchar(240)        NULL,
   [ALLOW_DPA]                        nchar(1)             NULL,
   [AVAIL_BTOC]                       nchar(1)             NULL,
   [FIRST_LOCK_IND]                   nchar(1)             NULL,
   [OLD_AGENCY_NUM_IND]               nchar(1)             NULL,
   [PRODUCT_IDENTIFIER]               nvarchar(80)         NULL,
   [S_AUS_IND]                        nvarchar(8)          NULL,
   [S_SERVICE_TYPE]                   nvarchar(8)          NULL,
   [SERVICING_INTERFACE_IND]          nvarchar(30)         NULL,
   [SERVICING_LOCATION]               nvarchar(20)         NULL,
   [SUB_PRIME_IND]                    nchar(1)             NULL,
   [MI_REQUIRE]                       nchar(1)             NULL,
   [INTEREST_ONLY_PRODUCT]            nchar(1)             NULL,
   [S_SPEC_PROG]                      nvarchar(8)          NULL,
   [CRA_REPORT]                       nchar(1)             NULL,
   [INV_CODE_OVR]                     nvarchar(4)          NULL,
   [INV_PROD_CODE_OVR]                nvarchar(4)          NULL,
   [INV_PROG_CODE_OVR]                nvarchar(4)          NULL,
   [INV_NAME_OVR]                     nvarchar(40)         NULL,
   [INV_PROD_NAME_OVR]                nvarchar(40)         NULL,
   [INV_PROG_NAME_OVR]                nvarchar(40)         NULL,
   [INV_PRICE_NAME_OVR]               nvarchar(40)         NULL,
   [INV_PRICE_CODE_OVR]               nvarchar(40)         NULL,
   [MIN_ALLOW_LN_TERM]                int                  NULL,
   [MAX_ALLOW_LN_TERM]                int                  NULL,
   [ODDDAYSDEFER]                     nchar(1)             NULL,
   [OVRD_PROD_RULES]                  nchar(1)             NULL,
   [DEBT_PROTECT_OFFERED]             nchar(1)             NULL,
   [EVAL_ATR]                         nchar(1)             NULL,
   [EVAL_QM]                          nchar(1)             NULL,
   [APPLY_MLA_RULES]                  nchar(1)             NULL,
   [LNDR_PD_MI_ALLOWED]               nchar(1)             NULL,
   [S_ASSUMABILITY_FEATURE]           nvarchar(8)          NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
