-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLR_RSP_LP_LOANFDBCK]
(
   [LNUM]                              nchar(20)            NOT NULL,
   [DBID]                              nchar(5)             NOT NULL,
   [RESPONSEID]                        int                  NOT NULL,
   [LPRESPONSEID]                      int                  NOT NULL,
   [LOANFEEDBACKID]                    int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]      datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]               datetime2(7)         NULL,
   [LPKEYIDENTIFIER]                   nvarchar(8)          NULL,
   [LPLOANIDENTIFIER]                  nvarchar(20)         NULL,
   [FRELPTRANSACTIONIDENTIFIER]        nvarchar(20)         NULL,
   [LPTRANSACTIONIDENTIFIER]           nvarchar(8)          NULL,
   [LENDERCASEIDENTIFIER]              nvarchar(15)         NULL,
   [LPSUBMISSIONNUMBER]                int                  NULL,
   [LPSERVICEEVALUATIONTYPE]           nvarchar(45)         NULL,
   [LPEVALUATIONSTATUSTYPE]            nvarchar(14)         NULL,
   [LPSUBMISSIONDATE]                  nvarchar(23)         NULL,
   [LPEVALUATIONDATE]                  nvarchar(23)         NULL,
   [FREPURCHASEELIGIBILITYTYPE]        nvarchar(56)         NULL,
   [LPINITIALLTVRATIO]                 decimal(16,6)        NULL,
   [LPINITIALTOTALLTVRATIO]            decimal(16,6)        NULL,
   [LPCREDITRISKCLASSTYPE]             nvarchar(7)          NULL,
   [LPDOCCLASSTYPE]                    nvarchar(10)         NULL,
   [LPACCEPTPLUSELIGIBLEINDICATOR]     nchar(1)             NULL,
   [CREDSCOREDATAREPOSSRCTYPE]         nvarchar(15)         NULL,
   [SCOREDBORROWERNAME]                nvarchar(45)         NULL,
   [CREDITSCOREVALUE]                  int                  NULL,
   [HOUSINGRATIOPERCENT]               decimal(16,6)        NULL,
   [DEBTRATIOPERCENT]                  decimal(16,6)        NULL,
   [LPRISKGRADEASSIGNEDTYPE]           nvarchar(5)          NULL,
   [FINANCINGCONCESSIONAMOUNT]         decimal(16,6)        NULL,
   [FRECASHOUTINDICATOR]               nchar(1)             NULL,
   [ORIGINATINGCOMPANYNAME]            nvarchar(250)        NULL,
   [SUBMITTINGCOMPANYNAME]             nvarchar(250)        NULL,
   [FRELOANPURPOSEDESCRIPTION]         nvarchar(25)         NULL,
   [FREPROPERTYCATEGORYDESC]           nvarchar(30)         NULL,
   [MORTGAGELOANLIMIT]                 decimal(16,6)        NULL,
   [FREHIGHERTOTALLTV]                 decimal(16,6)        NULL,
   [FREOCCUPANTHOUSINGRATIO]           decimal(16,6)        NULL,
   [FREOCCUPANTDEBTRATIO]              decimal(16,6)        NULL,
   [FRECREDITEXPIRATIONDATE]           nvarchar(10)         NULL,
   [FRECREDITSCORELTVFEELVLDESC]       nvarchar(20)         NULL,
   [FRELOANASSIGNMENTSTATUSDESC]       nvarchar(18)         NULL,
   [FREDOCUMENTATIONLEVELDESC]         nvarchar(20)         NULL,
   [FREHUDSCOREDINDICATOR]             nvarchar(1)          NULL,
   [ASSIGNFROMUNPARSEDNAME]            nvarchar(45)         NULL,
   [ASSIGNTOUNPARSEDNAME]              nvarchar(45)         NULL,
   [FRELOANRELEASEFROMUNPRSDNME]       nvarchar(45)         NULL,
   [FRELOANRELEASETOUNPARSEDNME]       nvarchar(45)         NULL,
   [FRELOANMSPASSIGNUNPRSDNME]         nvarchar(45)         NULL,
   [CREDITREPORTIDENTIFIER]            nvarchar(30)         NULL,
   [DOCCHECKLSTRPT]                    nvarchar(5)          NULL,
   [DOCCHECKLST_SER]                   int                  NULL,
   [FEEDBACKRPT]                       nvarchar(5)          NULL,
   [FEEDBACK_SER]                      int                  NULL,
   [MIFEEDBACKRPT]                     nvarchar(5)          NULL,
   [MIFEEDBACK_SER]                    int                  NULL,
   [FEEDBACKREPORTIMAGEID]             nvarchar(100)        NULL,
   [MIFEEDBACKREPORTIMAGEID]           nvarchar(100)        NULL,
   [DOCCHECKLISTIMAGEID]               nvarchar(100)        NULL,
   [MERGEDCREDCERT]                    nvarchar(5)          NULL,
   [MERGEDCRED_SER]                    int                  NULL,
   [LPERRORRPT]                        nvarchar(5)          NULL,
   [LPERROR_SER]                       int                  NULL,
   [ERRORRPTIMAGEID]                   nvarchar(100)        NULL,
   [MERGEDCREDITCERTIMAGEID]           nvarchar(100)        NULL,
   [S_CRWELIGIBILITYTYPE]              nvarchar(8)          NULL,
   [HVERPTIMAGEID]                     nvarchar(100)        NULL,
   [MERGEDCREDITIMAGEID]               nvarchar(100)        NULL,
   [LPATTLASSETDEFICITAMT]             decimal(16,6)        NULL,
   [LPATTLTHRDPRTYVALIDATEAMT]         decimal(16,6)        NULL,
   [LPAPRODUCTIDENTIFIER]              nvarchar(5)          NULL,
   [LPAVERIFIEDASSETTOTALAMT]          decimal(16,6)        NULL,
   [LPACOLLREPANDWARRRELIEFDES]        nvarchar(30)         NULL,
   [LPAINCREPANDWARRRELIEF]            nvarchar(15)         NULL,
   [LPAGFTGRNTTTLCASHMARKETAMT]        decimal(16,6)        NULL,
   [LPATTLELIGIBLEASSETAMOUNT]         decimal(16,6)        NULL,
   [LPATTLFNDSTOVERIFIEDAMOUNT]        decimal(16,6)        NULL,
   [LPANONSUBPROPDBTTOPAIDOFF]         decimal(16,6)        NULL,
   [LPALIABILITYPTPAIDOFFAMT]          decimal(16,6)        NULL,
   [LPAPURCHASEPRICEAMOUNT]            decimal(16,6)        NULL,
   [LPATOTALDOWNPMTAMOUNT]             decimal(16,6)        NULL,
   [LPAHOUEXPPRESENTTTLMTLYAMT]        decimal(16,6)        NULL,
   [LPAHOUEXPPROPOSEDMNTLYAMT]         decimal(16,6)        NULL,
   [LPANONOCCBORRHEXPPRSNTPMT]         decimal(16,6)        NULL,
   [LPATTLSUBFINANCEPROCEEDAMT]        decimal(16,6)        NULL,
   [LPAPROJECTEDRESERVESAMT]           decimal(16,6)        NULL,
   [LPAQUALIFYINGPMTAMT]               decimal(16,6)        NULL,
   [LPATTLLIABLTYMNTHLYPMTAMT]         decimal(16,6)        NULL,
   [LPATTLMNTLYINCOMEAMT]              decimal(16,6)        NULL,
   [LPANONOCCUBORRTTLNHLIABPMT]        decimal(16,6)        NULL,
   [LPATTLREQUIREDFUNDSAMT]            decimal(16,6)        NULL,
   [LPATTLREQUIREDRESERVESAMT]         decimal(16,6)        NULL,
   [CREDIT_INFILE]                     nvarchar(100)        NULL,
   [ASAP_ROW_HASH]                     nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                     nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                 datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                 datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                   nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                  nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                   nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                 nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]                datetime2(7)         NULL,
   [ASAP_SRC_NAME]                     nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
