-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[INCOME]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [CTR]                              smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [TITLE]                            nvarchar(30)         NULL,
   [BUSTYPE]                          nvarchar(30)         NULL,
   [SUPERVSR]                         nvarchar(35)         NULL,
   [INCMNAME]                         nvarchar(50)         NULL,
   [ADDR1]                            nvarchar(35)         NULL,
   [ADDR2]                            nvarchar(35)         NULL,
   [CITY]                             nvarchar(35)         NULL,
   [STATE]                            nchar(2)             NULL,
   [ZIP]                              nvarchar(10)         NULL,
   [PHONE]                            nvarchar(11)         NULL,
   [PHONEXT]                          nvarchar(6)          NULL,
   [ATTNOF]                           nvarchar(35)         NULL,
   [FAXNO]                            nvarchar(11)         NULL,
   [ID]                               nvarchar(12)         NULL,
   [EMPDFROM]                         datetime             NULL,
   [EMPDTO]                           datetime             NULL,
   [YRSATJOB]                         decimal(16,6)        NULL,
   [YRSINPRO]                         decimal(16,6)        NULL,
   [JEXPDESC]                         nvarchar(35)         NULL,
   [JEXPAMT]                          decimal(16,6)        NULL,
   [PRIMINC]                          nchar(1)             NULL,
   [S_INCOME]                         nvarchar(8)          NULL,
   [S_PAYPER]                         nvarchar(8)          NULL,
   [INCAMT]                           decimal(18,3)        NULL,
   [INCDESC]                          nvarchar(30)         NULL,
   [MNTEQUIV]                         decimal(18,3)        NULL,
   [USEQUAL]                          nchar(1)             NULL,
   [TYPEFLAG]                         nchar(1)             NULL,
   [SELFEMPL]                         nchar(1)             NULL,
   [BENEFIT]                          nchar(1)             NULL,
   [BEN_TYPE]                         nvarchar(30)         NULL,
   [ACCTOF]                           nvarchar(35)         NULL,
   [ACCTNUM]                          nvarchar(20)         NULL,
   [VERIFY]                           nchar(1)             NULL,
   [OTHERDSC]                         nvarchar(40)         NULL,
   [NONTAXBL]                         nchar(1)             NULL,
   [INCOME_VERIFIED]                  nchar(1)             NULL,
   [MILITARY_YN]                      nchar(1)             NULL,
   [PERCBUSOWN]                       decimal(16,6)        NULL,
   [TSWE_INCOME_IND]                  nchar(1)             NULL,
   [EFFECTIVE_MO_INC]                 decimal(18,3)        NULL,
   [S_JOB_TYPE]                       nvarchar(8)          NULL,
   [OVRTIME_CONT]                     nvarchar(25)         NULL,
   [PROB_CONT_EMPLOY]                 nvarchar(25)         NULL,
   [OTHERINCTYPEDESC]                 nvarchar(500)        NULL,
   [S_SPECBOREMPRELTYPE]              nvarchar(8)          NULL,
   [OTHERSPECBOREMPRELTYPEDSC]        nvarchar(80)         NULL,
   [RURALHOUSINGCALC]                 nchar(1)             NULL,
   [COUNTRY]                          nvarchar(35)         NULL,
   [VERIFICATION_TYPE]                nvarchar(8)          NULL,
   [VERIF_TYPE_DESC]                  nvarchar(80)         NULL,
   [STATED_FLAG]                      nchar(1)             NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [S_INCOMECATEGORY]                 nvarchar(8)          NULL,
   [OCCUPATION]                       nvarchar(8)          NULL,
   [INCSTIND]                         nchar(1)             NULL,
   [S_SELFEMPTYPE]                    nvarchar(8)          NULL,
   [PRE_VERI_GROSS_INC]               decimal(18,3)        NULL,
   [USE_GROSS_INCOME]                 nchar(1)             NULL,
   [YTD_AMOUNT]                       decimal(18,3)        NULL,
   [YTD_AS_OF_DATE]                   datetime             NULL,
   [INC_SRC_CTR]                      int                  NULL,
   [YTD_AVG_INCOME]                   decimal(18,3)        NULL,
   [FOREIGNINCOME]                    nchar(1)             NULL,
   [SEASONALINCOME]                   nchar(1)             NULL,
   [LIABCTR]                          int                  NULL,
   [GROSSUPOVR]                       decimal(16,6)        NULL,
   [GROSSUP]                          decimal(16,6)        NULL,
   [FROM_INCOME_CALC]                 nchar(1)             NULL,
   [STATED_INC]                       decimal(18,3)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
