-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[REOWNED]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [REOCNTR]                          smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [INCINTOT]                         nchar(1)             NULL,
   [REOADDR1]                         nvarchar(55)         NULL,
   [REOADDR2]                         nvarchar(55)         NULL,
   [REOCITY]                          nvarchar(25)         NULL,
   [REOSTATE]                         nchar(2)             NULL,
   [REOZIP]                           nvarchar(10)         NULL,
   [S_REOPST]                         nvarchar(8)          NULL,
   [S_REOTYP]                         nvarchar(8)          NULL,
   [PRESVAL]                          decimal(18,3)        NULL,
   [PRESMTG]                          decimal(18,3)        NULL,
   [GROSRENT]                         decimal(18,3)        NULL,
   [MTGPYMT]                          decimal(18,3)        NULL,
   [TINMISC]                          decimal(18,3)        NULL,
   [NETRENT]                          decimal(18,3)        NULL,
   [PGROSINC]                         decimal(16,6)        NULL,
   [AGROSINC]                         decimal(18,3)        NULL,
   [S_ONRSHP]                         nvarchar(8)          NULL,
   [REOCNTRY]                         nvarchar(35)         NULL,
   [PRIM_RES]                         nchar(1)             NULL,
   [SUBJECTP]                         nchar(1)             NULL,
   [NETRENTOV]                        decimal(18,3)        NULL,
   [XPROCEED]                         decimal(18,3)        NULL,
   [ASSETCTR]                         smallint             NULL,
   [ISLINKED]                         nchar(1)             NULL,
   [XPROCEEDOV]                       decimal(18,3)        NULL,
   [REOCNTY]                          nvarchar(35)         NULL,
   [ORIG_COST]                        decimal(18,3)        NULL,
   [PERC_OF_OWNERSHIP]                decimal(16,6)        NULL,
   [ISBLANKET]                        nchar(1)             NULL,
   [MSACODE]                          nvarchar(6)          NULL,
   [STCODE]                           nchar(2)             NULL,
   [CYCODE]                           nchar(3)             NULL,
   [STRUCTURE]                        nchar(1)             NULL,
   [INFLOODZONE]                      nchar(1)             NULL,
   [PARCELID]                         nvarchar(40)         NULL,
   [CENSUSTRACT]                      nvarchar(8)          NULL,
   [CLOSINGDT]                        datetime             NULL,
   [DISBURSEDT]                       datetime             NULL,
   [LEGALDBID]                        nchar(5)             NULL,
   [LEGALSERNO]                       int                  NULL,
   [VESTINGDBID]                      nchar(5)             NULL,
   [VESTINGSERNO]                     int                  NULL,
   [RECDIST]                          nvarchar(20)         NULL,
   [PROJECTNAME]                      nvarchar(80)         NULL,
   [PUDDECLDBID]                      nchar(5)             NULL,
   [PUDDECLSERNO]                     int                  NULL,
   [VERIF_INCOME_TYPE]                nvarchar(8)          NULL,
   [VERIF_DEBT_TYPE]                  nvarchar(8)          NULL,
   [VERIF_TYPE_DESC]                  nvarchar(80)         NULL,
   [VERIFY]                           nchar(1)             NULL,
   [VERIFIED]                         nchar(1)             NULL,
   [HOADUES]                          decimal(18,3)        NULL,
   [HOME_IMPRV_FLAG]                  nvarchar(1)          NULL,
   [NUMBEROFUNITS_REO]                int                  NULL,
   [DEBT_DOESNTAPPLY]                 nchar(1)             NULL,
   [UNITNUMREO]                       nvarchar(12)         NULL,
   [UNITTYPEREO]                      nvarchar(100)        NULL,
   [S_ACCOUNT_OWNERSHIP]              nvarchar(8)          NULL,
   [XPROCEEDOVR]                      decimal(18,3)        NULL,
   [S_REO_INTEND_OCCUPANCY]           nvarchar(8)          NULL,
   [REO_OTHROCCUP_DESC]               nvarchar(200)        NULL,
   [S_REO_CURR_PROP_USAGE]            nvarchar(8)          NULL,
   [REO_STATE_FOREIN]                 nvarchar(35)         NULL,
   [REO_POSTCODE]                     nvarchar(12)         NULL,
   [REO_CNTRY_COD]                    nvarchar(12)         NULL,
   [RECORD_CREATED]                   nvarchar(35)         NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
