-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[TAXINFO]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [REFUN3RD]                         nchar(1)             NULL,
   [OTH3RDNM]                         nvarchar(80)         NULL,
   [TRAN1040]                         nchar(1)             NULL,
   [TAXFORM]                          nchar(1)             NULL,
   [CERTCOPY]                         nchar(1)             NULL,
   [VERIFNON]                         nchar(1)             NULL,
   [W2COPY]                           nchar(1)             NULL,
   [W2STATE]                          nchar(1)             NULL,
   [SBAREQ]                           nchar(1)             NULL,
   [DOEREQ]                           nchar(1)             NULL,
   [FINREQ]                           nchar(1)             NULL,
   [VAREQ]                            nchar(1)             NULL,
   [FRMREQ1]                          nvarchar(10)         NULL,
   [FRMREQ2]                          nvarchar(10)         NULL,
   [FRMREQ3]                          nvarchar(10)         NULL,
   [FRMREQ4]                          nvarchar(10)         NULL,
   [PERCOST]                          decimal(18,3)        NULL,
   [REQTIME]                          nvarchar(20)         NULL,
   [TAXTYPE1]                         nvarchar(20)         NULL,
   [TAXTYPE2]                         nvarchar(20)         NULL,
   [TAXTYPE3]                         nvarchar(20)         NULL,
   [TAXTYPE4]                         nvarchar(20)         NULL,
   [BRTITLE1]                         nvarchar(20)         NULL,
   [BRTITLE2]                         nvarchar(20)         NULL,
   [CAFNUM]                           nchar(9)             NULL,
   [PLANNUM]                          nchar(3)             NULL,
   [APPNWADD]                         nchar(1)             NULL,
   [APPNWPH]                          nchar(1)             NULL,
   [TAXSPUSE]                         nchar(1)             NULL,
   [TAXTOAPP]                         nchar(1)             NULL,
   [TAXREVOK]                         nchar(1)             NULL,
   [EXECMOU]                          nchar(1)             NULL,
   [MOUACCT]                          nvarchar(20)         NULL,
   [REQPHONE]                         nchar(10)            NULL,
   [NUMPRDS]                          smallint             NULL,
   [APPNWFAX_CHK]                     nchar(1)             NULL,
   [PERREQ1]                          nchar(4)             NULL,
   [PERREQ2]                          nchar(4)             NULL,
   [PERREQ3]                          nchar(4)             NULL,
   [PERREQ4]                          nchar(4)             NULL,
   [PERREQ5]                          nchar(4)             NULL,
   [PERREQ6]                          nchar(4)             NULL,
   [PERREQ7]                          nchar(4)             NULL,
   [PERREQ8]                          nchar(4)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
