-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[VETINFO]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [SERVNUM]                          nchar(15)            NULL,
   [S_BRANCH]                         nvarchar(8)          NULL,
   [STRTSERV]                         datetime             NULL,
   [ENDSERV]                          datetime             NULL,
   [EXEMPT]                           nchar(1)             NULL,
   [VETDECES]                         nchar(1)             NULL,
   [DATEDECS]                         datetime             NULL,
   [RELNAME]                          nvarchar(30)         NULL,
   [RELADDR1]                         nvarchar(35)         NULL,
   [RELADDR2]                         nvarchar(35)         NULL,
   [RELCITY]                          nvarchar(25)         NULL,
   [RELSTATE]                         nchar(2)             NULL,
   [RELZIP]                           nchar(10)            NULL,
   [RELPHONE]                         nchar(11)            NULL,
   [RELRELTN]                         nvarchar(20)         NULL,
   [SERVPERD]                         nchar(1)             NULL,
   [OSRVNUM1]                         nchar(15)            NULL,
   [S_OBRCH1]                         nvarchar(8)          NULL,
   [OSTRTDT1]                         datetime             NULL,
   [OENDDT1]                          datetime             NULL,
   [OSRVNUM2]                         nchar(15)            NULL,
   [S_OBRCH2]                         nvarchar(8)          NULL,
   [OSTRTDT2]                         datetime             NULL,
   [OENDDT2]                          datetime             NULL,
   [OSRVNUM3]                         nchar(15)            NULL,
   [S_OBRCH3]                         nvarchar(8)          NULL,
   [OSTRTDT3]                         datetime             NULL,
   [OENDDT3]                          datetime             NULL,
   [VETSTATUS]                        nchar(1)             NULL,
   [VETENTITLE]                       decimal(16,6)        NULL,
   [DVETDOB]                          datetime             NULL,
   [DVETSSN]                          nchar(11)            NULL,
   [DVETCAIVR]                        nvarchar(20)         NULL,
   [STATASCR]                         nchar(1)             NULL,
   [AWAREVAL]                         nchar(1)             NULL,
   [CERTENCS]                         nchar(1)             NULL,
   [CERTLOST]                         nchar(1)             NULL,
   [PRESDELQ]                         nchar(1)             NULL,
   [DELDESSN]                         int                  NULL,
   [DELDEDBID]                        nchar(5)             NULL,
   [FORECLOS]                         nchar(1)             NULL,
   [FORCLSSN]                         int                  NULL,
   [FORCLDBID]                        nchar(5)             NULL,
   [PREVGILN]                         nchar(1)             NULL,
   [SUBVALGE]                         nchar(1)             NULL,
   [VETDEBT]                          nchar(1)             NULL,
   [VETPORTIONLOAN]                   decimal(18,3)        NULL,
   [VETMAXENT]                        decimal(18,3)        NULL,
   [VETPREVENT]                       decimal(18,3)        NULL,
   [VETADDLENT]                       decimal(18,3)        NULL,
   [VETENTCHARGE]                     decimal(18,3)        NULL,
   [VETENTCHARGEOVR]                  decimal(18,3)        NULL,
   [VETENTCODE]                       nchar(2)             NULL,
   [VETFFFACTOR]                      decimal(16,6)        NULL,
   [VETFFTOTAL]                       decimal(18,3)        NULL,
   [CONTCTVA]                         nchar(1)             NULL,
   [PREVCERT]                         nchar(1)             NULL,
   [RENEWAL_OFFICE]                   nvarchar(25)         NULL,
   [ELIGIBILITY_OFFICE]               nvarchar(25)         NULL,
   [GILOAN_OFFICE]                    nvarchar(25)         NULL,
   [PRVAPPCT]                         nchar(1)             NULL,
   [PRVAPPDT]                         datetime             NULL,
   [RECCERT]                          nchar(1)             NULL,
   [RECCOMCT]                         nchar(1)             NULL,
   [RECDETE]                          nchar(1)             NULL,
   [SECLOAN]                          nchar(1)             NULL,
   [SATIS]                            nchar(1)             NULL,
   [CLAIM_NBR]                        nvarchar(10)         NULL,
   [NAME_AS_ON_PAPERS1]               nvarchar(40)         NULL,
   [NAME_AS_ON_PAPERS2]               nvarchar(40)         NULL,
   [NAME_AS_ON_PAPERS3]               nvarchar(40)         NULL,
   [NAME_AS_ON_PAPERS4]               nvarchar(40)         NULL,
   [REL_FADDR_INDICATOR]              nchar(1)             NULL,
   [ISANOTHERNAME]                    nchar(1)             NULL,
   [CLAIM_LOC]                        nvarchar(30)         NULL,
   [ANOTHERNAME]                      nvarchar(30)         NULL,
   [RETIRED_MILITARY]                 nchar(1)             NULL,
   [RESERVE_NATLGUARD]                nchar(1)             NULL,
   [SURVIVING_SPOUSE]                 nchar(1)             NULL,
   [SERVICE_EXPIRATION_DATE]          datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
