-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_BORR_INCOME_SRC_PAYSTUB]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [PS_CTR]                           int                  NOT NULL,
   [INC_SRC_CTR]                      int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [YTD_FROM_DATE]                    datetime             NULL,
   [YTD_TO_DATE]                      datetime             NULL,
   [PAYSTUB_DATE]                     datetime             NULL,
   [AVGHOURSPERWEEK]                  numeric(16,6)        NULL,
   [MONTHLYBASEPAY]                   numeric(16,6)        NULL,
   [MONTHLYRATE]                      numeric(16,6)        NULL,
   [OVERTIME_PAY]                     decimal(18,2)        NULL,
   [YTD_BASEPAY]                      numeric(16,6)        NULL,
   [YTD_OVERTIMEPAY]                  numeric(16,6)        NULL,
   [YTD_BONUSPAY]                     numeric(16,6)        NULL,
   [YTD_COMMISSIONPAY]                numeric(16,6)        NULL,
   [YTD_TOTALPAY]                     numeric(16,6)        NULL,
   [OTHER_PAY]                        decimal(18,2)        NULL,
   [COMMISSION_PAY]                   decimal(18,2)        NULL,
   [DEPENDENT_CARE_BENEFITS]          decimal(18,2)        NULL,
   [GARNISHMENTS]                     decimal(18,2)        NULL,
   [YTD_OTHERPAY]                     decimal(18,2)        NULL,
   [LOAN_REPAYMENT]                   decimal(18,2)        NULL,
   [PAYS_TOTAL_PAY]                   decimal(18,2)        NULL,
   [CALCULATED_INCOME]                decimal(18,2)        NULL,
   [OVR_CALCULATED_INCOME]            decimal(18,2)        NULL,
   [OTHER_DEDUCTION]                  decimal(18,2)        NULL,
   [AVG_YTD_BASE]                     decimal(18,2)        NULL,
   [AVG_YTD_GROSS]                    decimal(18,2)        NULL,
   [CHK_AVG_YTD_BASE]                 nchar(1)             NULL,
   [CHK_CURRENT_BASE]                 nchar(1)             NULL,
   [CHK_AVG_YTD_GROSS]                nchar(1)             NULL,
   [BONUS_PAY]                        decimal(18,2)        NULL,
   [PAYFREQ]                          nchar(2)             NULL,
   [BASE_HOURLY_PAY]                  decimal(18,2)        NULL,
   [CHK_BASE_HOURLY_PAY]              nchar(1)             NULL,
   [SUMMARY_CURRENT_NETPAY]           decimal(18,3)        NULL,
   [OVERTIMEHOURS]                    numeric(16,6)        NULL,
   [OVERTIMERATE]                     numeric(16,6)        NULL,
   [BONUSHOURS]                       numeric(16,6)        NULL,
   [BONUSRATE]                        numeric(16,6)        NULL,
   [COMMISSIONHOURS]                  numeric(16,6)        NULL,
   [COMMISSIONRATE]                   numeric(16,6)        NULL,
   [OTHERHOURS]                       numeric(16,6)        NULL,
   [OTHERRATE]                        numeric(16,6)        NULL,
   [MILITARYHOURS]                    numeric(16,6)        NULL,
   [MILITARYRATE]                     numeric(16,6)        NULL,
   [MILITARY_PAY]                     decimal(18,2)        NULL,
   [YTD_MILITARYPAY]                  decimal(18,2)        NULL,
   [DOC_UPLOADED_DATE]                datetime             NULL,
   [DATA_UPDATED_DATE]                datetime             NULL,
   [DATA_UPDATED_BYUSER]              nvarchar(100)        NULL,
   [OCR_DATA_FLAG]                    nchar(1)             NULL,
   [VALID_CARD]                       nchar(1)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
