-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_RPT_LOAN]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [CLNUM]                            nvarchar(20)         NULL,
   [EXTERNAL_LNUM]                    nvarchar(40)         NULL,
   [JPM_LNUM]                         nvarchar(40)         NULL,
   [AMORTIZATION]                     nvarchar(128)        NULL,
   [AMORTIZATION_DESC]                nvarchar(256)        NULL,
   [CHANNEL]                          nvarchar(128)        NULL,
   [CHANNEL_DESC]                     nvarchar(256)        NULL,
   [CREDIT_SCORE]                     int                  NULL,
   [DOC_TYPE]                         nvarchar(128)        NULL,
   [DOC_TYPE_DESC]                    nvarchar(256)        NULL,
   [LEAD_SOURCE]                      nvarchar(128)        NULL,
   [LEAD_SOURCE_DESC]                 nvarchar(256)        NULL,
   [LIEN_POSITION]                    nvarchar(128)        NULL,
   [LIEN_POSITION_DESC]               nvarchar(256)        NULL,
   [LOAN_PURPOSE]                     nvarchar(128)        NULL,
   [LOAN_PURPOSE_DESC]                nvarchar(256)        NULL,
   [LOAN_STATUS]                      nvarchar(128)        NULL,
   [LOAN_STATUS_DESC]                 nvarchar(256)        NULL,
   [LOAN_TYPE]                        nvarchar(128)        NULL,
   [LOAN_TYPE_DESC]                   nvarchar(256)        NULL,
   [OCCUPANCY]                        nvarchar(128)        NULL,
   [OCCUPANCY_DESC]                   nvarchar(256)        NULL,
   [PREPAY_PENALTY_YN]                nchar(1)             NULL,
   [PRODUCT]                          nvarchar(128)        NULL,
   [PRODUCT_DESC]                     nvarchar(256)        NULL,
   [PROGRAM]                          nvarchar(128)        NULL,
   [PROGRAM_DESC]                     nvarchar(256)        NULL,
   [UW_DISPOSITION]                   nvarchar(128)        NULL,
   [UW_DISPOSITION_DESC]              nvarchar(256)        NULL,
   [LOAN_LOCKED]                      nchar(1)             NULL,
   [INVLK_COMMITMENT_NBR]             nvarchar(20)         NULL,
   [INVLK_LOCKED]                     nchar(1)             NULL,
   [INVLK_LOCK_STATUS]                nvarchar(128)        NULL,
   [INVLK_LOCK_STATUS_DESC]           nvarchar(256)        NULL,
   [LOAN_ACTIVITY]                    nvarchar(128)        NULL,
   [REFI_PURPOSE]                     nvarchar(128)        NULL,
   [REFI_PURPOSE_DESC]                nvarchar(256)        NULL,
   [AGENCY_CASE_NUMBER]               nvarchar(30)         NULL,
   [LOAN_IS_PREQUAL_YN]               nchar(1)             NULL,
   [MORTGAGE_TYPE]                    nvarchar(128)        NULL,
   [MORTGAGE_TYPE_DESC]               nvarchar(256)        NULL,
   [LOAN_TERM]                        smallint             NULL,
   [FUNDING_METHOD]                   nvarchar(128)        NULL,
   [FUNDING_METHOD_DESC]              nvarchar(256)        NULL,
   [DELIVERY_TERMS]                   nvarchar(128)        NULL,
   [DELIVERY_TERMS_DESC]              nvarchar(256)        NULL,
   [CONDITION_TEXT]                   nvarchar(MAX)        NULL,
   [CUSTATE]                          nchar(1)             NULL,
   [CUISACTIVE_YN]                    nchar(1)             NULL,
   [ESCROW_WAIVER]                    nchar(1)             NULL,
   [REDISCLOSE_YN]                    nchar(1)             NULL,
   [PRODUCT_RATECODE]                 nvarchar(10)         NULL,
   [UW_TOLERANCE_FLAG]                nchar(1)             NULL,
   [GFE_TOLERANCE_FLAG]               nchar(1)             NULL,
   [LOCK_CONFIRM_YN]                  nvarchar(1)          NULL,
   [CULTURE_CODE]                     nvarchar(10)         NULL,
   [LOCK_TYPE]                        nvarchar(40)         NULL,
   [LOCK_TYPE_DESC]                   nvarchar(160)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH ( CLUSTERED INDEX ([LNUM]) )
;
