-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_RPT_BORROWER]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [B_ORDER]                          smallint             NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [B_AGE]                            smallint             NULL,
   [B_BORTYPE]                        nvarchar(128)        NULL,
   [B_BORTYPE_DESC]                   nvarchar(256)        NULL,
   [B_DOB]                            datetime             NULL,
   [B_EMAIL]                          nvarchar(128)        NULL,
   [B_FIRST_TIME_YN]                  nchar(1)             NULL,
   [B_FOREIGN_NATL_YN]                nchar(1)             NULL,
   [B_GENDER]                         nvarchar(128)        NULL,
   [B_HOME_PHONE]                     nvarchar(11)         NULL,
   [B_MAIL_ADDR1]                     nvarchar(100)        NULL,
   [B_MAIL_ADDR2]                     nvarchar(100)        NULL,
   [B_MAIL_CITY]                      nvarchar(25)         NULL,
   [B_MAIL_COUNTY]                    nvarchar(35)         NULL,
   [B_MAIL_STATE]                     nchar(2)             NULL,
   [B_MAIL_ZIP]                       nvarchar(10)         NULL,
   [B_MARITAL_STATUS]                 nvarchar(128)        NULL,
   [B_MARITAL_STATUS_DESC]            nvarchar(256)        NULL,
   [B_NAME_FIRST]                     nvarchar(250)        NULL,
   [B_NAME_LAST]                      nvarchar(30)         NULL,
   [B_NAME_MID]                       nvarchar(30)         NULL,
   [B_PRIMARY_YN]                     nchar(1)             NULL,
   [B_RACE]                           nvarchar(128)        NULL,
   [B_RACE_DESC]                      nvarchar(256)        NULL,
   [B_SCORE]                          int                  NULL,
   [B_SSN]                            nvarchar(11)         NULL,
   [B_VETERAN_YN]                     nchar(1)             NULL,
   [B_WORK_PHONE]                     nvarchar(11)         NULL,
   [PROSPECT_CONTACT_METHOD]          nvarchar(128)        NULL,
   [PROSPECT_OPTOUT]                  nchar(1)             NULL,
   [PROSPECT_STATUS]                  nvarchar(128)        NULL,
   [PROSPECT_STATUS_EXP]              nvarchar(255)        NULL,
   [PROSPECT_TIME_TO_CALL]            nvarchar(24)         NULL,
   [PROSPECT_YN]                      nchar(1)             NULL,
   [ETHNICITY]                        nvarchar(128)        NULL,
   [B_INTERVIEW_METHOD]               nvarchar(128)        NULL,
   [B_INTERVIEW_METHOD_DESC]          nvarchar(256)        NULL,
   [USA_CITIZEN_YN]                   nchar(1)             NULL,
   [B_SCORE_OVR]                      int                  NULL,
   [B_CELL_PHONE]                     nvarchar(11)         NULL,
   [EMAIL_CONSENT]                    nchar(1)             NULL,
   [SMS_CONSENT]                      nchar(1)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
