-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO].[VwBORROWER]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      HASHBYTES('SHA2_256', x.[FNAME]) AS [FNAME],
      HASHBYTES('SHA2_256', x.[MNAME]) AS [MNAME],
      x.[LNAME],
      HASHBYTES('SHA2_256', x.[SSNBR]) AS [SSNBR],
      x.[AGE],
      x.[YRSSCHL],
      x.[S_MARITL],
      x.[FRNINFO],
      x.[GENDER],
      x.[NUMDEP],
      x.[DEPAGES],
      x.[ADDR1],
      x.[ADDR2],
      HASHBYTES('SHA2_256', x.[CITY]) AS [CITY],
      x.[STATE],
      HASHBYTES('SHA2_256', x.[ZIP]) AS [ZIP],
      x.[YRSPADDR],
      x.[HPHONE],
      x.[PRIMARYB],
      x.[APPNUMB],
      x.[FIRSTBUY],
      x.[S_OWNSHP],
      x.[VOR_ACCT],
      x.[VOR_NAME],
      x.[OTHINCM],
      x.[COMMUNTY],
      x.[JOINTLY],
      x.[DOB],
      x.[S_BORTYP],
      x.[ALIASES],
      x.[S_VESTNG],
      x.[PRTENTTL],
      x.[PARTNOTE],
      x.[COUNTY],
      x.[CITYFLAG],
      x.[MARBOR],
      x.[COUNTRY],
      x.[RACEDESC],
      x.[CAIVR1],
      x.[CAIVR2],
      x.[LDPGSA1],
      x.[LDPGSA2],
      x.[POAFLAG],
      x.[ALISDBID],
      x.[ALSERNUM],
      x.[WPHONE],
      x.[EMAIL],
      x.[FAXNUM],
      HASHBYTES('SHA2_256', x.[CANADIAN_SSN]) AS [CANADIAN_SSN],
      HASHBYTES('SHA2_256', x.[NAME_SUFFIX]) AS [NAME_SUFFIX],
      x.[B_1098_IDN],
      x.[QUAL_INCOME],
      x.[BOR_TIN],
      x.[UNPARSED_NAME],
      x.[AFFIL_SHARE_IND],
      HASHBYTES('SHA2_256', x.[SSN_CERTIFICATION_IND]) AS [SSN_CERTIFICATION_IND],
      x.[PHONE_ALLOWED_IND],
      x.[EMAIL_ALLOWED_IND],
      x.[US_MAIL_ALLOWED_IND],
      x.[CARRIER_ROUTE],
      x.[OVERALL_CRED_SCORE],
      x.[OVERALL_CRED_SCORE_OVR],
      x.[CORP_SIGNATURE],
      x.[INCBASEEMPTOTAL],
      x.[INCSELFEMPTOTAL],
      x.[INCOVERTIMETOTAL],
      x.[INCBONUSTOTAL],
      x.[INCCOMMISTOTAL],
      x.[INCDIVDTOTAL],
      x.[INCNETRENTOTAL],
      x.[ATCASHDEPOSITTOTAL],
      x.[ATCHECKSAVINGSTOTAL],
      x.[ATSTOCKBONDTOTAL],
      x.[ATLIFEINSNETTOTAL],
      x.[ATOTHLIQUIDTOTAL],
      x.[ATREOTOTAL],
      x.[ATVESTEDINTTOTAL],
      x.[ATNETWORTHTOTAL],
      x.[ATAUTOMOBILE],
      x.[ATOTHNONLIQTOTAL],
      x.[INCOTHERTOTAL],
      x.[ATLIFEINSFACEAMTTOTAL],
      x.[ATASSETSTOTAL],
      x.[LTALIMONYCSSMPTOTAL],
      x.[LTJOBRELATEDEXPTOTAL],
      x.[LTLIABILITIESTOTAL],
      x.[LTMONTHLYPAYMNTTOTAL],
      x.[REOGROSSRENTINCTOTAL],
      x.[REOMORTANDLIENTOTAL],
      x.[REOMORTGAGEPAYMNTTOTAL],
      x.[REOTAXMAINTMISCTOTAL],
      x.[URLANETWORTH],
      x.[ELEC_DISC_CONSENT],
      x.[ELEC_DISC_WITHDRAW],
      x.[S_IVMETH],
      x.[ATALLLIQUIDTOTAL],
      x.[ATGIFTTOTAL],
      x.[ATREONETPROCEEDSTOTAL],
      x.[BORROWED_DWNPMT_AMT],
      x.[LTNONSUBJDEBTMOTOTAL],
      x.[LTNONSUBJPAYOFFTOTAL],
      x.[S_CBSOURCE],
      x.[VETERAN],
      x.[ENTITLEMENT],
      x.[LDP_NUMBER],
      x.[GSA_NUMBER],
      x.[FOREIGN_NATIONAL],
      x.[COUNTRY_OF_INCORP],
      x.[EIN],
      x.[NLR_NAME],
      x.[NLR_REL_DESC],
      x.[NLR_PHONE],
      x.[NLR_ADDR1],
      x.[NLR_ADDR2],
      x.[NLR_CITY],
      x.[NLR_STATE],
      x.[NLR_POSTALCODE],
      HASHBYTES('SHA2_256', x.[EXEMPTSSN]) AS [EXEMPTSSN],
      x.[FHA_CLASSIFICATION],
      x.[LDP_YN],
      x.[GSA_YN],
      x.[OVERALL_CS_SOURCE],
      x.[DISPLAY_NAME],
      x.[NON_INDIV_BORR_NAME],
      x.[S_LEGAL_ENTITY_TYPE],
      x.[S_LEGAL_ENTITY_TYP_OTH],
      x.[ULDD_TAXPAYER_ID],
      x.[INCLUDE_IN_PROFORMA],
      x.[FADDR_INDICATOR],
      x.[DBA_NAME],
      x.[STATE_OF_INCORP],
      x.[INMILITARY],
      x.[BORRDISABLD],
      x.[RECORD_CREATED],
      x.[HUD_APPROVED],
      HASHBYTES('SHA2_256', x.[VERIFYSSN]) AS [VERIFYSSN],
      x.[BORR_CS_RANK_PERCENT],
      x.[YRS_AT_PRSNT],
      x.[MNTHS_AT_PRSNT],
      x.[BORR_COVERED],
      x.[S_COV_BORR_STATUS],
      x.[BORR_VERBDISC],
      x.[MLACERTID],
      x.[S_BOR_UNIT_TYPE],
      x.[BOR_UNIT_NUM],
      x.[BOR_COUNTRY],
      x.[BOR_COUNTRY_CODE],
      x.[BORR_QUAL_INC_SOURCE],
      x.[CREDIT_SCORE_MODEL],
      x.[CREDITSCORE_MODEL_OTHDESC],
      x.[BORR_FRAUD_SCORE],
      x.[FURNISH_GENDER_INFO_YN],
      x.[COLLD_BY_OBSRVTION_GENDER_YN],
      x.[COLLD_BY_OBSRVTION_RACE_YN],
      x.[COLLD_BY_OBSRVTION_ETH_YN],
      x.[SEX_MALE],
      x.[SEX_FEMALE],
      x.[COPIED_MAIL_ADDRESS],
      x.[CHECK_ALIAS],
      x.[S_PARTY_TYPE],
      x.[S_CITIZENSHIP],
      x.[S_UNMARRIED],
      x.[ATTR_PORTAL_REG],
      x.[ATTR_COUNSELING_REQUIRED],
      x.[ATTR_CHILD_CARE],
      x.[ATTR_GUARANTOR],
      x.[ATTR_GUARDIANSHIP],
      x.[ATTR_SOLE_PROPRIETOR],
      x.[S_UNMARRIED_RLTNSHIP],
      x.[UNMARRIED_RLTNSHIP_STATE],
      x.[UNMARRIED_RLTNSHIP_OTHERDESC],
      x.[RETIRED_BORROWER],
      x.[BOR_STATE_FOREIGN],
      x.[BOR_POSTCODE],
      x.[COUNTRY_OF_INCORP_CODE],
      HASHBYTES('SHA2_256', x.[EMAIL_CONSENT]) AS [EMAIL_CONSENT],
      x.[SMS_CONSENT],
      x.[OVERALL_CS_SOURCE_OVR],
      x.[IS_DEALER_EMPLOYEE],
      x.[LIVE_RENT_FREE_ENUMS]
   FROM [clt_NetO].[BORROWER] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
