IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'clt_AssetAcq')
BEGIN
  EXEC( 'CREATE SCHEMA clt_AssetAcq;' )
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'AssetAcq')
BEGIN
  EXEC( 'CREATE SCHEMA AssetAcq;' )
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'AssetAcq_restricted')
BEGIN
  EXEC( 'CREATE SCHEMA AssetAcq_restricted;' )
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'AssetAcq_pii')
BEGIN
  EXEC( 'CREATE SCHEMA AssetAcq_pii;' )
END
GO


-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'clt_AssetAcq' AND TABLE_NAME = 'DCU_Monthly')
BEGIN
   DROP TABLE [clt_AssetAcq].[DCU_Monthly]
END
GO

CREATE TABLE [clt_AssetAcq].[DCU_Monthly]
(
   [ASAP_RecordEffectiveDateTime]                      datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]                               datetime2(7)         NULL,
   [member_nbr]                                        int                  NULL,
   [loan_nbr]                                          int                  NULL,
   [act_pni_paid]                                      decimal(16,6)        NULL,
   [age_purchase]                                      int                  NULL,
   [amortizationtype]                                  nvarchar(50)         NULL,
   [asset_class]                                       nvarchar(50)         NULL,
   [auto_manual_apprvl]                                nvarchar(50)         NULL,
   [back_end_ltv]                                      decimal(16,6)        NULL,
   [bkrpt_chapter]                                     int                  NULL,
   [bkrpt_flag]                                        nchar(1)             NULL,
   [borrower_age]                                      int                  NULL,
   [borrower_occup]                                    nvarchar(50)         NULL,
   [borrower_state_code]                               nvarchar(50)         NULL,
   [business_account_flag]                             nchar(1)             NULL,
   [co_borrower_fico]                                  int                  NULL,
   [co_borrower_flag]                                  nchar(1)             NULL,
   [co_borrower_occup]                                 nvarchar(50)         NULL,
   [collateral_make]                                   nvarchar(50)         NULL,
   [collateral_model]                                  nvarchar(50)         NULL,
   [collateral_type]                                   nvarchar(50)         NULL,
   [collateral_year]                                   int                  NULL,
   [collateralstate]                                   nvarchar(50)         NULL,
   [collateralzipcode]                                 nvarchar(50)         NULL,
   [conform_collateral_type]                           int                  NULL,
   [conform_curr_dq_bkt]                               int                  NULL,
   [conform_curr_loan_status]                          int                  NULL,
   [conform_int_rate_index]                            int                  NULL,
   [conform_int_rate_type]                             int                  NULL,
   [conform_interest_accrual_basis]                    int                  NULL,
   [conform_loan_purpose]                              int                  NULL,
   [conform_paymnt_freqncy]                            int                  NULL,
   [conform_product_type]                              int                  NULL,
   [contract_res_value]                                int                  NULL,
   [credit_limit_change_action]                        int                  NULL,
   [credit_union_product_type]                         nvarchar(50)         NULL,
   [creditimpaired]                                    int                  NULL,
   [curr_bal]                                          decimal(16,6)        NULL,
   [curr_collateral_val]                               decimal(16,6)        NULL,
   [curr_cred_limit]                                   int                  NULL,
   [curr_credit_grade]                                 nchar(1)             NULL,
   [curr_dq_bkt]                                       nvarchar(50)         NULL,
   [curr_fico]                                         int                  NULL,
   [curr_fico_date]                                    int                  NULL,
   [curr_int_rate]                                     decimal(16,6)        NULL,
   [curr_loan_status]                                  nvarchar(50)         NULL,
   [curr_unfund_bal]                                   int                  NULL,
   [current_p_i_amount_owed]                           decimal(16,6)        NULL,
   [date_bank]                                         int                  NULL,
   [date_closed]                                       int                  NULL,
   [dealer_name]                                       int                  NULL,
   [defaultdate]                                       int                  NULL,
   [dpd]                                               int                  NULL,
   [dq_hist_12]                                        nvarchar(50)         NULL,
   [dti_back_orig]                                     decimal(16,6)        NULL,
   [dti_front_orig]                                    decimal(16,6)        NULL,
   [estimate_residual_value]                           int                  NULL,
   [exit_type]                                         int                  NULL,
   [first_pay_date]                                    int                  NULL,
   [first_reset_freq]                                  int                  NULL,
   [flag_used]                                         nchar(1)             NULL,
   [front_end_ltv]                                     decimal(16,6)        NULL,
   [instrumentidentifier]                              long                 NULL,
   [int_gross_margin]                                  int                  NULL,
   [int_paid_thru_date]                                int                  NULL,
   [int_rate_index]                                    int                  NULL,
   [int_rate_type]                                     nvarchar(50)         NULL,
   [interest_accrual_basis]                            nvarchar(50)         NULL,
   [last_limit_change_date]                            int                  NULL,
   [lease_factor]                                      int                  NULL,
   [loan_desc]                                         nvarchar(50)         NULL,
   [loan_id]                                           bigint               NULL,
   [loan_source]                                       nvarchar(50)         NULL,
   [maturity_date]                                     int                  NULL,
   [nbr_of_times_120_days_delinquent_life_of_loan]     int                  NULL,
   [nbr_of_times_180_days_delinquent_life_of_loan]     int                  NULL,
   [nbr_of_times_30_days_delinquent_life_of_loan]      int                  NULL,
   [nbr_of_times_60_days_delinquent_life_of_loan]      int                  NULL,
   [nbr_of_times_90_days_delinquent_life_of_loan]      int                  NULL,
   [next_due_date]                                     int                  NULL,
   [orig_bal]                                          int                  NULL,
   [orig_collateral_val]                               int                  NULL,
   [orig_cred_limit]                                   int                  NULL,
   [orig_credit_grade]                                 nchar(1)             NULL,
   [orig_date]                                         nvarchar(50)         NULL,
   [orig_fico]                                         int                  NULL,
   [orig_int_rate]                                     decimal(16,6)        NULL,
   [orig_loan_term]                                    int                  NULL,
   [orig_ltv]                                          decimal(16,6)        NULL,
   [original_p_i_amount_owed]                          decimal(16,6)        NULL,
   [paid_thru_date]                                    int                  NULL,
   [paymnt_freqncy]                                    nvarchar(50)         NULL,
   [portfolioidentifier]                               nvarchar(50)         NULL,
   [product_type]                                      nvarchar(50)         NULL,
   [pti]                                               decimal(16,6)        NULL,
   [rate_life_cap]                                     int                  NULL,
   [rate_life_floor]                                   int                  NULL,
   [recourse_flag]                                     nchar(1)             NULL,
   [secured_flag]                                      nchar(1)             NULL,
   [servicer]                                          nvarchar(50)         NULL,
   [snapshot_date]                                     int                  NULL,
   [subseq_reset_freq]                                 int                  NULL,
   [tdr_flag]                                          int                  NULL,
   [tdr_hist_flag]                                     int                  NULL,
   [tdr_impairment_amt]                                int                  NULL,
   [vehicle_mfgr]                                      nvarchar(50)         NULL,
   [vin]                                               nvarchar(50)         NULL,
   [wala]                                              int                  NULL,
   [wam]                                               int                  NULL,
   [ASAP_ROW_HASH]                                     nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                                     nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                                 datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                                 datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                                   nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                                  nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                                   nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                                 nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]                                datetime2(7)         NULL,
   [ASAP_SRC_NAME]                                     nvarchar(36)         NULL
)
;
GO


-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'AssetAcq' AND TABLE_NAME = 'DCU_Monthly')
BEGIN
   DROP VIEW [AssetAcq].[DCU_Monthly]
END
GO


CREATE VIEW [AssetAcq].[DCU_Monthly]
AS
   SELECT
      x.[member_nbr],
      x.[loan_nbr],
      x.[act_pni_paid],
      x.[age_purchase],
      x.[amortizationtype],
      x.[asset_class],
      x.[auto_manual_apprvl],
      x.[back_end_ltv],
      x.[bkrpt_chapter],
      x.[bkrpt_flag],
      x.[borrower_age],
      x.[borrower_occup],
      x.[borrower_state_code],
      x.[business_account_flag],
      x.[co_borrower_fico],
      x.[co_borrower_flag],
      x.[co_borrower_occup],
      x.[collateral_make],
      x.[collateral_model],
      x.[collateral_type],
      x.[collateral_year],
      x.[collateralstate],
      x.[collateralzipcode],
      x.[conform_collateral_type],
      x.[conform_curr_dq_bkt],
      x.[conform_curr_loan_status],
      x.[conform_int_rate_index],
      x.[conform_int_rate_type],
      x.[conform_interest_accrual_basis],
      x.[conform_loan_purpose],
      x.[conform_paymnt_freqncy],
      x.[conform_product_type],
      x.[contract_res_value],
      x.[credit_limit_change_action],
      x.[credit_union_product_type],
      x.[creditimpaired],
      x.[curr_bal],
      x.[curr_collateral_val],
      x.[curr_cred_limit],
      x.[curr_credit_grade],
      x.[curr_dq_bkt],
      x.[curr_fico],
      x.[curr_fico_date],
      x.[curr_int_rate],
      x.[curr_loan_status],
      x.[curr_unfund_bal],
      x.[current_p_i_amount_owed],
      x.[date_bank],
      x.[date_closed],
      x.[dealer_name],
      x.[defaultdate],
      x.[dpd],
      x.[dq_hist_12],
      x.[dti_back_orig],
      x.[dti_front_orig],
      x.[estimate_residual_value],
      x.[exit_type],
      x.[first_pay_date],
      x.[first_reset_freq],
      x.[flag_used],
      x.[front_end_ltv],
      x.[instrumentidentifier],
      x.[int_gross_margin],
      x.[int_paid_thru_date],
      x.[int_rate_index],
      x.[int_rate_type],
      x.[interest_accrual_basis],
      x.[last_limit_change_date],
      x.[lease_factor],
      x.[loan_desc],
      x.[loan_id],
      x.[loan_source],
      x.[maturity_date],
      x.[nbr_of_times_120_days_delinquent_life_of_loan],
      x.[nbr_of_times_180_days_delinquent_life_of_loan],
      x.[nbr_of_times_30_days_delinquent_life_of_loan],
      x.[nbr_of_times_60_days_delinquent_life_of_loan],
      x.[nbr_of_times_90_days_delinquent_life_of_loan],
      x.[next_due_date],
      x.[orig_bal],
      x.[orig_collateral_val],
      x.[orig_cred_limit],
      x.[orig_credit_grade],
      x.[orig_date],
      x.[orig_fico],
      x.[orig_int_rate],
      x.[orig_loan_term],
      x.[orig_ltv],
      x.[original_p_i_amount_owed],
      x.[paid_thru_date],
      x.[paymnt_freqncy],
      x.[portfolioidentifier],
      x.[product_type],
      x.[pti],
      x.[rate_life_cap],
      x.[rate_life_floor],
      x.[recourse_flag],
      x.[secured_flag],
      x.[servicer],
      x.[snapshot_date],
      x.[subseq_reset_freq],
      x.[tdr_flag],
      x.[tdr_hist_flag],
      x.[tdr_impairment_amt],
      x.[vehicle_mfgr],
      x.[vin],
      x.[wala],
      x.[wam],
      x.[ASAP_ROW_HASH],
      x.[ASAP_DML_FLAG],
      x.[ASAP_CREATED_DATE],
      x.[ASAP_UPDATED_DATE],
      x.[ASAP_LINEAGE_ID],
      x.[ASAP_ACTIVITY_ID],
      x.[ASAP_TRIGGER_ID],
      x.[ASAP_SRC_FILEPATH],
      x.[ASAP_SRC_FILE_DATE],
      x.[ASAP_SRC_NAME]
   FROM [clt_AssetAcq].[DCU_Monthly] x
   WHERE x.[ASAP_DeleteDateTime] IS NULL
;
GO

-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'AssetAcq_restricted' AND TABLE_NAME = 'DCU_Monthly')
BEGIN
   DROP VIEW [AssetAcq_restricted].[DCU_Monthly]
END
GO


CREATE VIEW [AssetAcq_restricted].[DCU_Monthly]
AS
   SELECT
      x.[member_nbr],
      x.[loan_nbr],
      x.[act_pni_paid],
      x.[age_purchase],
      x.[amortizationtype],
      x.[asset_class],
      x.[auto_manual_apprvl],
      x.[back_end_ltv],
      x.[bkrpt_chapter],
      x.[bkrpt_flag],
      x.[borrower_age],
      x.[borrower_occup],
      x.[borrower_state_code],
      x.[business_account_flag],
      x.[co_borrower_fico],
      x.[co_borrower_flag],
      x.[co_borrower_occup],
      x.[collateral_make],
      x.[collateral_model],
      x.[collateral_type],
      x.[collateral_year],
      x.[collateralstate],
      x.[collateralzipcode],
      x.[conform_collateral_type],
      x.[conform_curr_dq_bkt],
      x.[conform_curr_loan_status],
      x.[conform_int_rate_index],
      x.[conform_int_rate_type],
      x.[conform_interest_accrual_basis],
      x.[conform_loan_purpose],
      x.[conform_paymnt_freqncy],
      x.[conform_product_type],
      x.[contract_res_value],
      x.[credit_limit_change_action],
      x.[credit_union_product_type],
      x.[creditimpaired],
      x.[curr_bal],
      x.[curr_collateral_val],
      x.[curr_cred_limit],
      x.[curr_credit_grade],
      x.[curr_dq_bkt],
      x.[curr_fico],
      x.[curr_fico_date],
      x.[curr_int_rate],
      x.[curr_loan_status],
      x.[curr_unfund_bal],
      x.[current_p_i_amount_owed],
      x.[date_bank],
      x.[date_closed],
      x.[dealer_name],
      x.[defaultdate],
      x.[dpd],
      x.[dq_hist_12],
      x.[dti_back_orig],
      x.[dti_front_orig],
      x.[estimate_residual_value],
      x.[exit_type],
      x.[first_pay_date],
      x.[first_reset_freq],
      x.[flag_used],
      x.[front_end_ltv],
      x.[instrumentidentifier],
      x.[int_gross_margin],
      x.[int_paid_thru_date],
      x.[int_rate_index],
      x.[int_rate_type],
      x.[interest_accrual_basis],
      x.[last_limit_change_date],
      x.[lease_factor],
      x.[loan_desc],
      x.[loan_id],
      x.[loan_source],
      x.[maturity_date],
      x.[nbr_of_times_120_days_delinquent_life_of_loan],
      x.[nbr_of_times_180_days_delinquent_life_of_loan],
      x.[nbr_of_times_30_days_delinquent_life_of_loan],
      x.[nbr_of_times_60_days_delinquent_life_of_loan],
      x.[nbr_of_times_90_days_delinquent_life_of_loan],
      x.[next_due_date],
      x.[orig_bal],
      x.[orig_collateral_val],
      x.[orig_cred_limit],
      x.[orig_credit_grade],
      x.[orig_date],
      x.[orig_fico],
      x.[orig_int_rate],
      x.[orig_loan_term],
      x.[orig_ltv],
      x.[original_p_i_amount_owed],
      x.[paid_thru_date],
      x.[paymnt_freqncy],
      x.[portfolioidentifier],
      x.[product_type],
      x.[pti],
      x.[rate_life_cap],
      x.[rate_life_floor],
      x.[recourse_flag],
      x.[secured_flag],
      x.[servicer],
      x.[snapshot_date],
      x.[subseq_reset_freq],
      x.[tdr_flag],
      x.[tdr_hist_flag],
      x.[tdr_impairment_amt],
      x.[vehicle_mfgr],
      x.[vin],
      x.[wala],
      x.[wam],
      x.[ASAP_ROW_HASH],
      x.[ASAP_DML_FLAG],
      x.[ASAP_CREATED_DATE],
      x.[ASAP_UPDATED_DATE],
      x.[ASAP_LINEAGE_ID],
      x.[ASAP_ACTIVITY_ID],
      x.[ASAP_TRIGGER_ID],
      x.[ASAP_SRC_FILEPATH],
      x.[ASAP_SRC_FILE_DATE],
      x.[ASAP_SRC_NAME]
   FROM [clt_AssetAcq].[DCU_Monthly] x
   WHERE x.[ASAP_DeleteDateTime] IS NULL
;
GO

-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'AssetAcq_pii' AND TABLE_NAME = 'DCU_Monthly')
BEGIN
   DROP VIEW [AssetAcq_pii].[DCU_Monthly]
END
GO


CREATE VIEW [AssetAcq_pii].[DCU_Monthly]
AS
   SELECT
      x.[member_nbr],
      x.[loan_nbr],
      x.[act_pni_paid],
      x.[age_purchase],
      x.[amortizationtype],
      x.[asset_class],
      x.[auto_manual_apprvl],
      x.[back_end_ltv],
      x.[bkrpt_chapter],
      x.[bkrpt_flag],
      x.[borrower_age],
      x.[borrower_occup],
      x.[borrower_state_code],
      x.[business_account_flag],
      x.[co_borrower_fico],
      x.[co_borrower_flag],
      x.[co_borrower_occup],
      x.[collateral_make],
      x.[collateral_model],
      x.[collateral_type],
      x.[collateral_year],
      x.[collateralstate],
      x.[collateralzipcode],
      x.[conform_collateral_type],
      x.[conform_curr_dq_bkt],
      x.[conform_curr_loan_status],
      x.[conform_int_rate_index],
      x.[conform_int_rate_type],
      x.[conform_interest_accrual_basis],
      x.[conform_loan_purpose],
      x.[conform_paymnt_freqncy],
      x.[conform_product_type],
      x.[contract_res_value],
      x.[credit_limit_change_action],
      x.[credit_union_product_type],
      x.[creditimpaired],
      x.[curr_bal],
      x.[curr_collateral_val],
      x.[curr_cred_limit],
      x.[curr_credit_grade],
      x.[curr_dq_bkt],
      x.[curr_fico],
      x.[curr_fico_date],
      x.[curr_int_rate],
      x.[curr_loan_status],
      x.[curr_unfund_bal],
      x.[current_p_i_amount_owed],
      x.[date_bank],
      x.[date_closed],
      x.[dealer_name],
      x.[defaultdate],
      x.[dpd],
      x.[dq_hist_12],
      x.[dti_back_orig],
      x.[dti_front_orig],
      x.[estimate_residual_value],
      x.[exit_type],
      x.[first_pay_date],
      x.[first_reset_freq],
      x.[flag_used],
      x.[front_end_ltv],
      x.[instrumentidentifier],
      x.[int_gross_margin],
      x.[int_paid_thru_date],
      x.[int_rate_index],
      x.[int_rate_type],
      x.[interest_accrual_basis],
      x.[last_limit_change_date],
      x.[lease_factor],
      x.[loan_desc],
      x.[loan_id],
      x.[loan_source],
      x.[maturity_date],
      x.[nbr_of_times_120_days_delinquent_life_of_loan],
      x.[nbr_of_times_180_days_delinquent_life_of_loan],
      x.[nbr_of_times_30_days_delinquent_life_of_loan],
      x.[nbr_of_times_60_days_delinquent_life_of_loan],
      x.[nbr_of_times_90_days_delinquent_life_of_loan],
      x.[next_due_date],
      x.[orig_bal],
      x.[orig_collateral_val],
      x.[orig_cred_limit],
      x.[orig_credit_grade],
      x.[orig_date],
      x.[orig_fico],
      x.[orig_int_rate],
      x.[orig_loan_term],
      x.[orig_ltv],
      x.[original_p_i_amount_owed],
      x.[paid_thru_date],
      x.[paymnt_freqncy],
      x.[portfolioidentifier],
      x.[product_type],
      x.[pti],
      x.[rate_life_cap],
      x.[rate_life_floor],
      x.[recourse_flag],
      x.[secured_flag],
      x.[servicer],
      x.[snapshot_date],
      x.[subseq_reset_freq],
      x.[tdr_flag],
      x.[tdr_hist_flag],
      x.[tdr_impairment_amt],
      x.[vehicle_mfgr],
      x.[vin],
      x.[wala],
      x.[wam],
      x.[ASAP_ROW_HASH],
      x.[ASAP_DML_FLAG],
      x.[ASAP_CREATED_DATE],
      x.[ASAP_UPDATED_DATE],
      x.[ASAP_LINEAGE_ID],
      x.[ASAP_ACTIVITY_ID],
      x.[ASAP_TRIGGER_ID],
      x.[ASAP_SRC_FILEPATH],
      x.[ASAP_SRC_FILE_DATE],
      x.[ASAP_SRC_NAME]
   FROM [clt_AssetAcq].[DCU_Monthly] x
   WHERE x.[ASAP_DeleteDateTime] IS NULL
;
GO

