-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwFEEVALS]
AS
   SELECT
      x.[LNUM],
      x.[DBCODE],
      x.[HUDLINE],
      x.[BPORTION],
      x.[SPORTION],
      x.[LPORTION],
      x.[BRPRTION],
      x.[BPOCPORT],
      x.[SPOCPORT],
      x.[NDSVCPVD],
      x.[IFACTOR],
      x.[BFACTOR],
      x.[BPOCFCTR],
      x.[SFACTOR],
      x.[SPOCFCTR],
      x.[LFACTOR],
      x.[BRFACTOR],
      x.[CALCTYPE],
      x.[CATEGORY],
      x.[INCINTOT],
      x.[ESCMONTH],
      x.[REFERBY],
      x.[HUDDESC],
      x.[ESCITEM],
      x.[RATELOCK],
      x.[NOTEDBID],
      x.[NOTESERN],
      x.[HUDALLOW],
      x.[WAIVDBID],
      x.[WAIVSERN],
      x.[INCHUD],
      x.[WAIVED],
      x.[CSHMONTH],
      x.[S_PERIOD],
      x.[TOTALATC],
      x.[INCGFE],
      x.[SPOVERRIDE],
      x.[TOTAL],
      x.[DIRECTBILL],
      x.[REFUNDABLE],
      x.[IAGFEVERBIAGE],
      x.[INCHCL],
      x.[CID_FEE_SRVC_PRVDR_CO],
      x.[S_MISC_DESC],
      x.[LOCKEDYN],
      x.[LOCKEDTOTAL],
      x.[ISSUE_CHECK],
      x.[CREDIT_BACK],
      x.[IPORTION],
      x.[BORRCHOOSEPRVDR],
      x.[SUBFEE],
      x.[FEECODE],
      x.[S_AGGTYPE],
      x.[S_RESP_PARTY],
      x.[S_PAIDBY],
      x.[S_PAIDTO],
      x.[SUBCODE],
      x.[IS_NOCOST],
      x.[MANAGED_OVR],
      x.[TO_AFFILIATE],
      x.[S_SECTION_TYPE],
      x.[ID_SECTION_SUBTYPE],
      x.[PREPAID_MONTH],
      x.[S_TOLERANCE_CATEGORY],
      x.[S_CHANGE_TYPE],
      x.[CHANGE_REASON],
      x.[BOROPT],
      x.[EXC_MAPR]
   FROM [clt_NetO].[FEEVALS] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
