-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwGF_TLBR_ADDITIONALDATA]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[ETHINICITY],
      x.[CELL_PHONE],
      x.[PRIM_CONTACT],
      x.[S_FIRSTTIMEHBCOUNSEL],
      x.[S_TITLE],
      HASHBYTES('SHA2_256', x.[CURRENT_CUSTOMER]) AS [CURRENT_CUSTOMER],
      x.[WORK_EXT],
      x.[CREDIT_AUTHORIZATION_YN],
      x.[NATIONALITY],
      x.[AFFILIATE],
      x.[S_COUNSEL_CONFIRM_TYP],
      x.[S_COUNSEL_CONFIRM_OTH],
      x.[S_COUNSEL_FORMAT_TYP],
      x.[CREDIT_AUTHORIZATION_DATE],
      x.[CUSTOMER_ID],
      x.[S_CRDTSCORE_MODEL_OVR],
      x.[URLA_BESTCONTACT],
      x.[URLA_ALTCONTACT],
      x.[S_CREDIT_TYPE],
      x.[JOINT_CREDIT_BNUM],
      HASHBYTES('SHA2_256', x.[SPOUSE_FNAME]) AS [SPOUSE_FNAME],
      HASHBYTES('SHA2_256', x.[SPOUSE_MNAME]) AS [SPOUSE_MNAME],
      HASHBYTES('SHA2_256', x.[SPOUSE_LNAME]) AS [SPOUSE_LNAME],
      HASHBYTES('SHA2_256', x.[SPOUSE_ADD1]) AS [SPOUSE_ADD1],
      HASHBYTES('SHA2_256', x.[SPOUSE_ADD2]) AS [SPOUSE_ADD2],
      HASHBYTES('SHA2_256', x.[SPOUSE_CITY]) AS [SPOUSE_CITY],
      HASHBYTES('SHA2_256', x.[SPOUSE_STATE]) AS [SPOUSE_STATE],
      HASHBYTES('SHA2_256', x.[SPOUSE_ZIP]) AS [SPOUSE_ZIP],
      x.[ATTR_BORROWER_ID],
      x.[MARITALSTATUSYN],
      x.[DATEOFCHANGEMS],
      x.[EXPLANATIONMS],
      x.[ATTR_CAIVRS],
      x.[ATTR_ESIGN],
      x.[S_LANGUAGEPREFERENCE],
      x.[OTHER_LANGUAGE],
      x.[CURRENTINCOTHERTOTAL],
      x.[CURRENTINCOMETOTAL],
      x.[TOTALCURRENTINCOME],
      x.[ATTR_SPOUSE_INFO],
      x.[ON_NOTE_BORROWERS],
      x.[CALL_CONSENT_PREFER],
      x.[HASCHECKINGACCT_WITHCU],
      x.[HASSAVINGACCT_WITHCU],
      HASHBYTES('SHA2_256', x.[CURRENT_CUSTOMERID]) AS [CURRENT_CUSTOMERID],
      x.[ISCUSTOMER_STATUS_VERIFIED],
      x.[ISCURRENTCUSTOMER],
      x.[HMDA_DISC_NOTICE],
      x.[CRDTSCORE_MODEL_OTHDESC_OVR],
      x.[PERSON_RECORD_FOUND]
   FROM [clt_NetO].[GF_TLBR_ADDITIONALDATA] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
