-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwREOWNED]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[REOCNTR],
      x.[INCINTOT],
      x.[REOADDR1],
      x.[REOADDR2],
      x.[REOCITY],
      x.[REOSTATE],
      x.[REOZIP],
      x.[S_REOPST],
      x.[S_REOTYP],
      x.[PRESVAL],
      x.[PRESMTG],
      x.[GROSRENT],
      x.[MTGPYMT],
      x.[TINMISC],
      x.[NETRENT],
      x.[PGROSINC],
      x.[AGROSINC],
      x.[S_ONRSHP],
      x.[REOCNTRY],
      x.[PRIM_RES],
      x.[SUBJECTP],
      x.[NETRENTOV],
      x.[XPROCEED],
      x.[ASSETCTR],
      x.[ISLINKED],
      x.[XPROCEEDOV],
      x.[REOCNTY],
      x.[ORIG_COST],
      x.[PERC_OF_OWNERSHIP],
      x.[ISBLANKET],
      x.[MSACODE],
      x.[STCODE],
      x.[CYCODE],
      x.[STRUCTURE],
      x.[INFLOODZONE],
      x.[PARCELID],
      x.[CENSUSTRACT],
      x.[CLOSINGDT],
      x.[DISBURSEDT],
      x.[LEGALDBID],
      x.[LEGALSERNO],
      x.[VESTINGDBID],
      x.[VESTINGSERNO],
      x.[RECDIST],
      x.[PROJECTNAME],
      x.[PUDDECLDBID],
      x.[PUDDECLSERNO],
      x.[VERIF_INCOME_TYPE],
      x.[VERIF_DEBT_TYPE],
      x.[VERIF_TYPE_DESC],
      x.[VERIFY],
      x.[VERIFIED],
      x.[HOADUES],
      x.[HOME_IMPRV_FLAG],
      x.[NUMBEROFUNITS_REO],
      x.[DEBT_DOESNTAPPLY],
      x.[UNITNUMREO],
      x.[UNITTYPEREO],
      x.[S_ACCOUNT_OWNERSHIP],
      x.[XPROCEEDOVR],
      x.[S_REO_INTEND_OCCUPANCY],
      x.[REO_OTHROCCUP_DESC],
      x.[S_REO_CURR_PROP_USAGE],
      x.[REO_STATE_FOREIN],
      x.[REO_POSTCODE],
      x.[REO_CNTRY_COD],
      x.[RECORD_CREATED]
   FROM [clt_NetO].[REOWNED] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
