-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwTILINFO]
AS
   SELECT
      x.[LNUM],
      x.[INITDISC],
      x.[REQITEM],
      x.[AREQDEP],
      x.[DASSUM],
      x.[ASSUMBLE],
      x.[RQPRPINS],
      x.[INSTERM],
      x.[FEESTAXS],
      x.[ALLOWDYS],
      x.[LTCHG],
      x.[MINLTCHG],
      x.[MAXLTCHG],
      x.[RFNDFCHG],
      x.[SECINRST],
      x.[RQMTGINS],
      x.[COLLSN],
      x.[PRPOWNSN],
      x.[PRPOWNDB],
      x.[MLIFPREM],
      x.[MLIFTERM],
      x.[MDISPREM],
      x.[MDISTERM],
      x.[MLDPREM],
      x.[MLDTERM],
      x.[LATECHGFLAG],
      x.[ESTDISC],
      x.[COLLDBID],
      x.[YIELDDT],
      x.[COMP_APR],
      x.[TTLINSPMT],
      x.[PREPYPEN],
      x.[LENDOWN],
      x.[DSCMIPMT],
      x.[CLCOMPNY],
      x.[INSURED],
      x.[LAMTOVR],
      x.[FEESOVR],
      x.[PERLAOVR],
      x.[APROVR],
      x.[HOEPARES],
      x.[PPPTYPE],
      x.[DISINTRST],
      x.[APR],
      x.[DEMANDF],
      x.[ASSUME_BEGIN_DATE],
      x.[ASSUME_TERM_MONTHS],
      x.[ASSUMABLE_DESC],
      x.[JOINLIFETRM],
      x.[JOINLIFEPRM],
      x.[REDISCLOSE_IND],
      x.[SECINTPRC],
      x.[SECINTOWN],
      x.[SECINTOTH],
      x.[S_LATECHARGETYPE],
      x.[S_PPPOPT],
      x.[PMMS_RATE],
      x.[LOCK_REDISCLOSE_IND],
      x.[S_TIL2011_OVRD],
      x.[FLAT_AMT],
      x.[BPRESOTHPRGS],
      x.[DISCLOSE_APR],
      x.[CD_NEG_AMINFO],
      x.[CD_PAR_PAYINFO],
      x.[CD_PAR_PAYINFO_A],
      x.[CD_PAR_PAYINFO_H],
      x.[FINANCE_CHARGE],
      x.[TOTAL_OF_PMTS],
      x.[ESTIMATE_ESCROW],
      x.[AMT_FINANCED],
      x.[HIGHCOSTLOAN],
      x.[MAPR],
      x.[OTHER_LOAN_FEATURE],
      x.[OTHER_LOAN_FEATURES_DESC],
      x.[GOODS_PURCHASED],
      x.[PERSONAL_PROPERTY],
      x.[PRESENT_SHARES],
      x.[OTHER_COLLATERAL]
   FROM [clt_NetO].[TILINFO] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
