-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_creditScore].[VwGF_TLBC_EQ_RES_COLLECT]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[ROWCOUNTER],
      x.[RESPONSEID],
      HASHBYTES('SHA2_256', CAST(x.[CREDITRESPONSEID] AS NVARCHAR(50))) AS [CREDITRESPONSEID],
      x.[ECOA_DESIGNATOR],
      x.[ASSIGNED_DT],
      HASHBYTES('SHA2_256', CAST(x.[ORIG_AMT] AS NVARCHAR(50))) AS [ORIG_AMT],
      HASHBYTES('SHA2_256', CAST(x.[FIRST_DELINQUENCY_DT] AS NVARCHAR(50))) AS [FIRST_DELINQUENCY_DT],
      HASHBYTES('SHA2_256', x.[AGENCY_CUST_NUM]) AS [AGENCY_CUST_NUM],
      x.[AUTO_UPDATE_IND],
      x.[CLIENT_ID],
      x.[REPORTED_DT],
      HASHBYTES('SHA2_256', CAST(x.[BALANCE] AS NVARCHAR(50))) AS [BALANCE],
      HASHBYTES('SHA2_256', x.[ACCT_NUM]) AS [ACCT_NUM],
      x.[STATUS_CODE],
      x.[STATUS_CODE_TEXT],
      HASHBYTES('SHA2_256', x.[NARRATIVE_CODE1]) AS [NARRATIVE_CODE1],
      HASHBYTES('SHA2_256', x.[NARRATIVE_TEXT1]) AS [NARRATIVE_TEXT1],
      HASHBYTES('SHA2_256', x.[NARRATIVE_CODE2]) AS [NARRATIVE_CODE2],
      HASHBYTES('SHA2_256', x.[NARRATIVE_TEXT2]) AS [NARRATIVE_TEXT2],
      HASHBYTES('SHA2_256', x.[CREDITOR_CLASS_CODE]) AS [CREDITOR_CLASS_CODE],
      x.[CRECITOR_CLASS_TEXT],
      x.[LAST_PMT_DT]
   FROM [clt_NetO].[GF_TLBC_EQ_RES_COLLECT] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
