-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_creditScore].[VwWG_COLLATERAL_PLEDGOR]
AS
   SELECT
      x.[LNUM],
      x.[DBID],
      HASHBYTES('SHA2_256', CAST(x.[ROWSERIALNO] AS NVARCHAR(50))) AS [ROWSERIALNO],
      HASHBYTES('SHA2_256', CAST(x.[CHILDROWSERIALNO] AS NVARCHAR(50))) AS [CHILDROWSERIALNO],
      HASHBYTES('SHA2_256', x.[PLEDGOR_TYPE]) AS [PLEDGOR_TYPE],
      HASHBYTES('SHA2_256', x.[PLEDGOR_MID_NAME]) AS [PLEDGOR_MID_NAME],
      HASHBYTES('SHA2_256', x.[PLEDGOR_LAST_NAME]) AS [PLEDGOR_LAST_NAME],
      HASHBYTES('SHA2_256', x.[PLEDGOR_ENTITY_NAME]) AS [PLEDGOR_ENTITY_NAME],
      HASHBYTES('SHA2_256', x.[PLEDGOR_SIGN_CAP]) AS [PLEDGOR_SIGN_CAP],
      HASHBYTES('SHA2_256', x.[PLEDGOR_ENTITY_TTL]) AS [PLEDGOR_ENTITY_TTL],
      HASHBYTES('SHA2_256', x.[PLEDGOR_FIRST_NAME]) AS [PLEDGOR_FIRST_NAME]
   FROM [clt_NetO].[WG_COLLATERAL_PLEDGOR] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
