-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[FEEVALS]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [DBCODE]                           nvarchar(8)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [HUDLINE]                          smallint             NULL,
   [BPORTION]                         decimal(18,3)        NULL,
   [SPORTION]                         decimal(18,3)        NULL,
   [LPORTION]                         decimal(18,3)        NULL,
   [BRPRTION]                         decimal(18,3)        NULL,
   [BPOCPORT]                         decimal(18,3)        NULL,
   [SPOCPORT]                         decimal(18,3)        NULL,
   [NDSVCPVD]                         nvarchar(8)          NULL,
   [IFACTOR]                          decimal(16,6)        NULL,
   [BFACTOR]                          decimal(16,6)        NULL,
   [BPOCFCTR]                         decimal(16,6)        NULL,
   [SFACTOR]                          decimal(16,6)        NULL,
   [SPOCFCTR]                         decimal(16,6)        NULL,
   [LFACTOR]                          decimal(16,6)        NULL,
   [BRFACTOR]                         decimal(16,6)        NULL,
   [CALCTYPE]                         nchar(1)             NULL,
   [CATEGORY]                         nchar(1)             NULL,
   [INCINTOT]                         nchar(1)             NULL,
   [ESCMONTH]                         smallint             NULL,
   [REFERBY]                          nvarchar(32)         NULL,
   [HUDDESC]                          nvarchar(80)         NULL,
   [ESCITEM]                          nchar(1)             NULL,
   [RATELOCK]                         nchar(1)             NULL,
   [NOTEDBID]                         nchar(5)             NULL,
   [NOTESERN]                         int                  NULL,
   [HUDALLOW]                         nchar(1)             NULL,
   [WAIVDBID]                         nchar(5)             NULL,
   [WAIVSERN]                         int                  NULL,
   [INCHUD]                           nchar(1)             NULL,
   [WAIVED]                           nchar(1)             NULL,
   [CSHMONTH]                         smallint             NULL,
   [S_PERIOD]                         nvarchar(8)          NULL,
   [TOTALATC]                         decimal(18,3)        NULL,
   [INCGFE]                           nchar(1)             NULL,
   [SPOVERRIDE]                       nvarchar(40)         NULL,
   [TOTAL]                            decimal(16,6)        NULL,
   [DIRECTBILL]                       nchar(1)             NULL,
   [REFUNDABLE]                       nchar(1)             NULL,
   [IAGFEVERBIAGE]                    nchar(1)             NULL,
   [INCHCL]                           nchar(1)             NULL,
   [CID_FEE_SRVC_PRVDR_CO]            int                  NULL,
   [S_MISC_DESC]                      nvarchar(8)          NULL,
   [LOCKEDYN]                         nchar(1)             NULL,
   [LOCKEDTOTAL]                      decimal(18,3)        NULL,
   [ISSUE_CHECK]                      nchar(1)             NULL,
   [CREDIT_BACK]                      nchar(1)             NULL,
   [IPORTION]                         decimal(18,3)        NULL,
   [BORRCHOOSEPRVDR]                  nchar(1)             NULL,
   [SUBFEE]                           nchar(1)             NULL,
   [FEECODE]                          nvarchar(20)         NOT NULL,
   [S_AGGTYPE]                        nvarchar(8)          NULL,
   [S_RESP_PARTY]                     nvarchar(8)          NULL,
   [S_PAIDBY]                         nvarchar(8)          NULL,
   [S_PAIDTO]                         nvarchar(8)          NULL,
   [SUBCODE]                          smallint             NULL,
   [IS_NOCOST]                        nchar(1)             NULL,
   [MANAGED_OVR]                      nchar(1)             NULL,
   [TO_AFFILIATE]                     nchar(1)             NULL,
   [S_SECTION_TYPE]                   nvarchar(8)          NULL,
   [ID_SECTION_SUBTYPE]               nvarchar(80)         NULL,
   [PREPAID_MONTH]                    int                  NULL,
   [S_TOLERANCE_CATEGORY]             nvarchar(8)          NULL,
   [S_CHANGE_TYPE]                    nvarchar(8)          NULL,
   [CHANGE_REASON]                    nvarchar(80)         NULL,
   [BOROPT]                           nchar(1)             NULL,
   [EXC_MAPR]                         nchar(1)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
