-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLR_RES_CREDIT_SUMMARY]
(
   [LNUM]                               nchar(20)            NOT NULL,
   [BNUM]                               smallint             NOT NULL,
   [DBID]                               nchar(5)             NOT NULL,
   [RESPONSEID]                         int                  NOT NULL,
   [CREDITRESPONSEID]                   int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]       datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]                datetime2(7)         NULL,
   [PRCNT_REV_CRED_AVAIL]               int                  NULL,
   [TOTAL_INQ_COUNT]                    int                  NULL,
   [REALEST_LT30DAYS_CURDELINQ]         int                  NULL,
   [TOTAL_LT60DAYS_CURDELINQ]           int                  NULL,
   [REALEST_LATE60DAYS_CURDELINQ]       int                  NULL,
   [REV_LATE60DAYS_CURDELINQ]           int                  NULL,
   [TOTAL_LT90PLUSDAYS_CURDELINQ]       int                  NULL,
   [REALEST_LT90PLUSDAYS_CURDELINQ]     int                  NULL,
   [NEW_TRDS_IN6MONTHS]                 int                  NULL,
   [TOTAL_TRDLINES_COUNT]               int                  NULL,
   [TOTAL_CLOSED_TRDLINES_COUNT]        int                  NULL,
   [INST_TRDLINES_COUNT]                int                  NULL,
   [INST_CLOSED_TRDLINES_COUNT]         int                  NULL,
   [REALEST_TTRDLINES_COUNT]            int                  NULL,
   [REALEST_CLOSED_TRDLINES_COUNT]      int                  NULL,
   [REV_TRDLINES_COUNT]                 int                  NULL,
   [REV_CLOSED_TRDLINES_COUNT]          int                  NULL,
   [REV_CURRENT_TRDLINES_COUNT]         int                  NULL,
   [OTHER_CURRENT_TRDLINES_COUNT]       int                  NULL,
   [INST_CURRENT_TRDLINES_COUNT]        int                  NULL,
   [TOTAL_COLLECTIONS]                  int                  NULL,
   [OLDEST_TRADE_DATE]                  datetime             NULL,
   [REALEST_CURRENT_TRDLINES_COUNT]     int                  NULL,
   [TOTAL_CURRENT_TRDLINES_COUNT]       int                  NULL,
   [REV_TRL_MTH_PMT_AMOUNT]             decimal(18,3)        NULL,
   [INST_TRL_MTH_PMT_AMOUNT]            decimal(18,3)        NULL,
   [IDENTITY_ON_FILEDATE]               datetime             NULL,
   [TERM]                               nvarchar(30)         NULL,
   [INQ_AGE_DAYS]                       nvarchar(30)         NULL,
   [ELIM_SAME_DAY_INQ_COUNT]            int                  NULL,
   [INQ_ADJ_TOTAL]                      int                  NULL,
   [PAID_AS_AGREED]                     int                  NULL,
   [NOW_DELINQUENT]                     int                  NULL,
   [ALL_DELINQUENT]                     int                  NULL,
   [HIGHEST_HIGH_CREDIT]                int                  NULL,
   [LOWEST_HIGH_CREDIT]                 int                  NULL,
   [HIST_DELINQ_COUNT]                  int                  NULL,
   [REV_OTHER_ACCOUNTSCOUNT]            int                  NULL,
   [BAL_REVOLVING_OTHER]                int                  NULL,
   [PMTS_REVOLVING_OTHER]               int                  NULL,
   [REV_OTH_CREDIT_AVAILABLE]           int                  NULL,
   [REV_OTH_CREDIT_PERCENT]             int                  NULL,
   [TOTAL_TRL_BAL_AMT]                  int                  NULL,
   [TOTAL_TRL_MNTHLY_PMT_AMT]           int                  NULL,
   [TOTAL_CUR_TRDLINES_COUNT]           int                  NULL,
   [TOTAL_UNRATED_TRDLINES_COUNT]       int                  NULL,
   [TOTAL_LT30DAYS_CURDELINQ]           int                  NULL,
   [TOTAL_LT30DAYS_HISTDELINQ]          int                  NULL,
   [TOTAL_LT60DAYS_HISTDELINQ]          int                  NULL,
   [TOTAL_LT90PLUSDAYS_HISTDELINQ]      int                  NULL,
   [REALEST_TRLBAL_AMOUNT]              decimal(18,3)        NULL,
   [REALEST_TRLMONTHLY_PMT_AMOUNT]      decimal(18,3)        NULL,
   [REALEST_UNRATED_TRDLINES_COUNT]     int                  NULL,
   [REALEST_LT30DAYS_HISTDELINQ]        int                  NULL,
   [REALEST_LT60DAYS_HISTDELINQ]        int                  NULL,
   [REALEST_LT90PLSDAYS_HISTDELINQ]     int                  NULL,
   [INST_TRL_BAL_AMOUNT]                decimal(18,3)        NULL,
   [INST_UNRATED_TRDLINES_COUNT]        int                  NULL,
   [INST_LT30DAYS_CURDELINQ]            int                  NULL,
   [INST_LT60DAYS_CURDELINQ]            int                  NULL,
   [INST_LT90PLUSDAYS_CURDELINQ]        int                  NULL,
   [INST_LT30DAYS_HISTDELINQ]           int                  NULL,
   [INST_LT60DAYS_HISTDELINQ]           int                  NULL,
   [INST_LT90PLUSDAYS_HISTDELINQ]       int                  NULL,
   [REV_CREDITAVAILABLE]                int                  NULL,
   [REV_CREDITTOTAL]                    int                  NULL,
   [REV_TRL_BAL_AMOUNT]                 decimal(18,3)        NULL,
   [REV_UNRATED_TRDLINES_COUNT]         int                  NULL,
   [REV_LT30DAYS_CURDELINQ]             int                  NULL,
   [REV_LT60DAYS_CURDELINQ]             int                  NULL,
   [REV_LT90PLUSDAYS_CURDELINQ]         int                  NULL,
   [REV_LT30DAYS_HISTDELINQ]            int                  NULL,
   [REV_LT60DAYS_HISTDELINQ]            int                  NULL,
   [REV_LT90PLUSDAYS_HISTDELINQ]        int                  NULL,
   [OTHER_CREDITAVAILABLE]              int                  NULL,
   [OTHER_CREDITTOTAL]                  int                  NULL,
   [OTHER_TRDLINES_COUNT]               int                  NULL,
   [OTHER_TRL_BAL_AMOUNT]               decimal(18,3)        NULL,
   [OTHER_TRL_MTH_PMT_AMOUNT]           decimal(18,3)        NULL,
   [OTHER_CLOSED_TRDLINES_COUNT]        int                  NULL,
   [OTHER_UNRATED_TRDLINES_COUNT]       int                  NULL,
   [OTHER_LT30DAYS_CURDELINQ]           int                  NULL,
   [OTHER_LT60DAYS_CURDELINQ]           int                  NULL,
   [OTHER_LT90PLUSDAYS_CURDELINQ]       int                  NULL,
   [OTHER_LT30DAYS_HISTDELINQ]          int                  NULL,
   [OTHER_LT60DAYS_HISTDELINQ]          int                  NULL,
   [OTHER_LT90PLUSDAYS_HISTDELINQ]      int                  NULL,
   [ANY_PUBREC_LAST_2YRS]               nchar(1)             NULL,
   [TOTAL_PRCOUNT]                      int                  NULL,
   [EFX_PUBREC_COUNT]                   int                  NULL,
   [TUC_PUBREC_COUNT]                   int                  NULL,
   [XPN_PUBREC_COUNT]                   int                  NULL,
   [ASAP_ROW_HASH]                      nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                      nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                  datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                  datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                    nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                   nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                    nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                  nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]                 datetime2(7)         NULL,
   [ASAP_SRC_NAME]                      nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
