-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TL_POINT_OF_SALE_INFO]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [S_REFSC]                          nvarchar(8)          NULL,
   [TBDADDR]                          nchar(1)             NULL,
   [POSFHA]                           nchar(1)             NULL,
   [S_PROPTYPE]                       nvarchar(8)          NULL,
   [PROJCLAS]                         nvarchar(35)         NULL,
   [PROJNAME]                         nvarchar(35)         NULL,
   [DPPERCT]                          decimal(16,6)        NULL,
   [HELINE]                           decimal(16,6)        NULL,
   [HECURBAL]                         decimal(16,6)        NULL,
   [S_DOCLVL]                         nvarchar(8)          NULL,
   [S_LNSTATUS]                       nvarchar(8)          NULL,
   [HLTVH]                            decimal(16,6)        NULL,
   [TSWE_INC_EXPECTED]                nchar(1)             NULL,
   [QUAL_TSWE_LOAN]                   nchar(1)             NULL,
   [LNSTATUS_DT]                      datetime             NULL,
   [SCHEME_ID]                        int                  NULL,
   [BORRCONTACTMETH]                  nchar(1)             NULL,
   [EST_PROCESSING_DAYS]              int                  NULL,
   [TABLE_FUNDED_IND]                 nchar(1)             NULL,
   [WAIT_WAIVED_BPOC]                 nchar(1)             NULL,
   [WAIT_WAIVED_CLOSDT]               nchar(1)             NULL,
   [USE_RESPA_2010]                   nchar(1)             NULL,
   [LO_NAME_OVR]                      nvarchar(50)         NULL,
   [LO_NMLS_NUM_OVR]                  nvarchar(20)         NULL,
   [LO_PHONE_OVR]                     nvarchar(10)         NULL,
   [S_GFE_TIME_ZONE]                  nvarchar(8)          NULL,
   [ALLOWWITHDRAWLOAN]                nchar(1)             NULL,
   [GFE_INT_RATE_LSC]                 decimal(16,6)        NULL,
   [GFE_INT_RATE_LIR]                 decimal(16,6)        NULL,
   [GFE_SET_CHRG_LSC]                 decimal(18,3)        NULL,
   [GFE_SET_CHRG_LIR]                 decimal(18,3)        NULL,
   [MAXLTV]                           decimal(16,6)        NULL,
   [EMPLOYEE_LOAN_YN]                 nchar(1)             NULL,
   [HIGH_PRICE_LOAN_YN]               nchar(1)             NULL,
   [MONTHLY_ESCROW_TOTAL]             decimal(18,3)        NULL,
   [REFI_LOAN_ACCT_NBR]               nvarchar(25)         NULL,
   [LO_NMLS_NUM]                      nvarchar(21)         NULL,
   [LO_COMP_NMLS_NUM]                 nvarchar(21)         NULL,
   [DU_DISPLAY]                       nvarchar(35)         NULL,
   [LP2_RISK_CLASS]                   nvarchar(35)         NULL,
   [AUTO_UW_YN]                       nchar(1)             NULL,
   [VA_TOT_RESID_INCOME]              decimal(18,3)        NULL,
   [PER_DIEM_CALC_BASIS]              nvarchar(8)          NULL,
   [PER_DIEM]                         decimal(18,3)        NULL,
   [PER_DIEM_INTEREST]                decimal(16,6)        NULL,
   [ESCROW_CUSHION_MNTH]              int                  NULL,
   [SPEC_FLOOD_HAZ_AREA]              nchar(1)             NULL,
   [NFIP_FLOOD_ZONE_ID]               nvarchar(35)         NULL,
   [SCHEME_VERSION]                   int                  NULL,
   [HLTV_ROUNDED]                     int                  NULL,
   [CHECKLOANSTATUS]                  nchar(1)             NULL,
   [TOTAL_PROPOSED_HOUSING_EXP]       decimal(18,3)        NULL,
   [SELLER_OUT_MORT]                  nchar(1)             NULL,
   [LO_EMAIL_OVR]                     nvarchar(128)        NULL,
   [USE_NEW_ESCROW_CALC]              nchar(1)             NULL,
   [SPONSORORIG]                      nchar(1)             NULL,
   [ACH_SELECTED]                     nchar(1)             NULL,
   [REFERREDBY]                       nvarchar(50)         NULL,
   [LO_EMPLOYER_OVR]                  nvarchar(90)         NULL,
   [LO_ADDR1_OVR]                     nvarchar(50)         NULL,
   [LO_CSZ_OVR]                       nvarchar(60)         NULL,
   [TIL_UNDER_DISCL_AMT]              numeric(16,6)        NULL,
   [LO_COMP_NMLS_NO_OVR]              nvarchar(20)         NULL,
   [ORIGINATOR_NMLS_NO]               nvarchar(25)         NULL,
   [APP_DATE_REQUIREMENTS_MET]        nchar(1)             NULL,
   [IS_TEMPORARY_FINANCING_LOAN]      nchar(1)             NULL,
   [LO_PROPST_LICNUM_OVR]             nvarchar(50)         NULL,
   [ADJHCLTV]                         decimal(16,6)        NULL,
   [PRODNAMEPARAM_EMAIL]              nvarchar(50)         NULL,
   [LP2_RISK_CLASS_OVR]               nvarchar(20)         NULL,
   [DU_DISPLAY_OVR]                   nvarchar(20)         NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
