-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLBC_TU_RES_TRADELINE]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [BNUM]                             smallint             NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [ROWCOUNTER]                       smallint             NOT NULL,
   [RESPONSEID]                       int                  NOT NULL,
   [CREDITRESPONSEID]                 int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [CUSTOMER_NAME]                    nvarchar(30)         NULL,
   [PORTFOLIO_TYPE]                   nchar(1)             NULL,
   [HIGH_CREDIT]                      decimal(18,3)        NULL,
   [ECOA_DESIGNATOR]                  nchar(1)             NULL,
   [ACCOUNT_NUM]                      nvarchar(30)         NULL,
   [REPORTED_DT]                      datetime             NULL,
   [OPENED_DT]                        datetime             NULL,
   [MONTHS_REVIEWED]                  smallint             NULL,
   [ACCT_TYPE_CODE]                   nchar(2)             NULL,
   [CLOSED_DT]                        datetime             NULL,
   [SCHED_PAYMENT_AMT]                decimal(18,3)        NULL,
   [TERMS_FREQUENCY]                  nvarchar(15)         NULL,
   [INDUSTRY_CODE]                    nvarchar(2)          NULL,
   [MEMBER_CODE]                      nvarchar(8)          NULL,
   [CLOSED_DATE_IND]                  nvarchar(10)         NULL,
   [CURRENCY]                         nchar(1)             NULL,
   [CURRENT_BALANCE_AMT]              decimal(18,3)        NULL,
   [TERMS_PMT_AMT]                    decimal(18,3)        NULL,
   [CUR_ACCT_RATING]                  nchar(2)             NULL,
   [PMT_PATTERN_START_DT]             datetime             NULL,
   [PMT_PATTERN]                      nvarchar(48)         NULL,
   [TIMES_30_DAYS_LATE]               smallint             NULL,
   [TIMES_60_DAYS_LATE]               smallint             NULL,
   [TIMES_90_DAYS_LATE]               smallint             NULL,
   [HIGH_PAST_DUE_AMT]                decimal(18,3)        NULL,
   [HIGH_PAST_DUE_AMT_DT]             datetime             NULL,
   [HIGH_PAST_DUE_AMT_RT]             nchar(2)             NULL,
   [MAX_DELINQUENCY_AMT]              decimal(18,3)        NULL,
   [MAX_DELINQUENCY_DT]               datetime             NULL,
   [MAX_DELINQUENCY_ACCT_RT]          nchar(2)             NULL,
   [PMT_SCHED_TYPE_CODE]              nvarchar(10)         NULL,
   [PMT_SCHED_DT]                     datetime             NULL,
   [PORTFOLIO_SALE_CODE]              nvarchar(15)         NULL,
   [PORTFOLIO_SALE_NAME]              nvarchar(30)         NULL,
   [AFFILIATE_REMARK_CODE]            nvarchar(3)          NULL,
   [GENERIC_REMARK_CODE]              nvarchar(3)          NULL,
   [RATING_HIST_REMARK_CODE]          nvarchar(3)          NULL,
   [COMPLIANCE_REMARK_CODE]           nvarchar(3)          NULL,
   [CONSUMER_STATEMENT_CODE]          nvarchar(3)          NULL,
   [UPDATE_METHOD_CODE]               nchar(1)             NULL,
   [LAST_PMT_DT]                      datetime             NULL,
   [TERMS_PMT_SCHED_MNTH_CNT]         smallint             NULL,
   [PAST_DUE_AMT]                     decimal(18,3)        NULL,
   [CREDIT_LIMIT_AMT]                 decimal(18,3)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
