-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[GF_TLR_RES_NADA_VAL]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [DBID]                             nchar(5)             NOT NULL,
   [RESPONSEID]                       int                  NOT NULL,
   [NADARESPONSEID]                   int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [BASE_VALUE_TRADEIN]               decimal(18,3)        NULL,
   [BASE_VALUE_LOAN]                  decimal(18,3)        NULL,
   [BASE_VALUE_RETAIL]                decimal(18,3)        NULL,
   [ADJUSTED_VALUE_TRADEIN]           decimal(18,3)        NULL,
   [ADJUSTED_VALUE_LOAN]              decimal(18,3)        NULL,
   [ADJUSTED_VALUE_RETAIL]            decimal(18,3)        NULL,
   [MILEAGE_ADJ]                      decimal(18,3)        NULL,
   [MSRP]                             decimal(18,3)        NULL,
   [VALUE_SELECTED]                   nchar(1)             NULL,
   [BASE_VALUE_LOAN_OVR]              decimal(18,3)        NULL,
   [ACCESS_VALUE_LOAN]                decimal(18,3)        NULL,
   [ACCESS_VALUE_TRADIN]              decimal(18,3)        NULL,
   [ACCESS_VALUE_RETAIL]              decimal(18,3)        NULL,
   [MILEAGE]                          int                  NULL,
   [MILEADJLOAN]                      numeric(16,6)        NULL,
   [MILEADJRETAIL]                    numeric(16,6)        NULL,
   [MILEADJTRADEIN]                   numeric(16,6)        NULL,
   [WEIGHT]                           int                  NULL,
   [AVEMILEAGE]                       int                  NULL,
   [TRADEINVINACC]                    numeric(16,6)        NULL,
   [TRADEINVINACCMILE]                numeric(16,6)        NULL,
   [LOANVINACC]                       numeric(16,6)        NULL,
   [LOANVINACCMILE]                   numeric(16,6)        NULL,
   [RETAILVINACC]                     numeric(16,6)        NULL,
   [RETAILVINACCMILE]                 numeric(16,6)        NULL,
   [AVGTRADEIN]                       numeric(16,6)        NULL,
   [ROUGHTRADEIN]                     numeric(16,6)        NULL,
   [BASE_VALUE_ROUGH_TRADEIN]         decimal(18,3)        NULL,
   [ACCESS_VALUE_ROUGH_TRADEIN]       decimal(18,3)        NULL,
   [TOTAL_VALUE_ROUGH_TRADEIN]        decimal(18,3)        NULL,
   [BASE_VALUE_CLEAN_TRADEIN]         decimal(18,3)        NULL,
   [ACCESS_VALUE_CLEAN_TRADEIN]       decimal(18,3)        NULL,
   [TOTAL_VALUE_CLEAN_TRADEIN]        decimal(18,3)        NULL,
   [BASE_VALUE_AVG_TRADEIN]           decimal(18,3)        NULL,
   [ACCESS_VALUE_AVG_TRADEIN]         decimal(18,3)        NULL,
   [TOTAL_VALUE_AVG_TRADEIN]          decimal(18,3)        NULL,
   [TOTAL_VALUE_RETAIL_TRADEIN]       decimal(18,3)        NULL,
   [ASSETID_LINKED_TO_RESP]           int                  NULL,
   [VALUATIONID_LINKED_TO_RESP]       int                  NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
