-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_ASSET_VEHICLE]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASSETID]                          int                  NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [VIN]                              nvarchar(64)         NULL,
   [MAKE]                             nvarchar(30)         NULL,
   [MODEL]                            nvarchar(50)         NULL,
   [YEAR]                             nvarchar(4)          NULL,
   [MSRP]                             numeric(16,6)        NULL,
   [NEW_YN]                           nchar(1)             NULL,
   [SERIAL]                           nvarchar(30)         NULL,
   [S_FUEL_TYPE]                      nvarchar(8)          NULL,
   [VEHICLE_REG_NUMBER]               nvarchar(64)         NULL,
   [BODY_TRIM]                        nvarchar(50)         NULL,
   [S_VEHICLE_CONDITION]              nvarchar(8)          NULL,
   [COLL_TITLE_NUM]                   nvarchar(64)         NULL,
   [S_CNRE_OWNERSHIP]                 nvarchar(8)          NULL,
   [LENGTH]                           numeric(18,0)        NULL,
   [WIDTH]                            numeric(18,0)        NULL,
   [PRIOR_TITLE_NUM]                  nvarchar(64)         NULL,
   [S_TRANSF_AS]                      nvarchar(8)          NULL,
   [S_TRANSF_TO]                      nvarchar(8)          NULL,
   [S_DAMAGE_TYPE]                    nvarchar(8)          NULL,
   [IS_BONAFIDE_GIFT]                 nchar(1)             NULL,
   [IS_REBUILDABLE]                   nchar(1)             NULL,
   [IS_ENERGY_EFFICIENT]              nchar(1)             NULL,
   [PRIOR_STATE]                      nvarchar(2)          NULL,
   [S_COLOR]                          nvarchar(8)          NULL,
   [S_GV_WEIGHT_RATING]               nvarchar(8)          NULL,
   [SCALE_WEIGHT]                     numeric(18,3)        NULL,
   [PAYOFF_AMT]                       numeric(18,3)        NULL,
   [MFG_REBATE]                       numeric(18,3)        NULL,
   [DLR_REBATE]                       numeric(18,3)        NULL,
   [INVOICE_PRC]                      numeric(18,3)        NULL,
   [DLR_OPT_PRICE]                    numeric(18,3)        NULL,
   [DLR_OPT_VALUE]                    numeric(18,3)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
