-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_CRM_CUSTOMER]
(
   [CUSTOMER_ID]                      nvarchar(50)         NOT NULL,
   [CUSTOMER_TYPE]                    nvarchar(8)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [CUSTOMER_NAME]                    nvarchar(250)        NULL,
   [FNAME]                            nvarchar(30)         NULL,
   [MNAME]                            nvarchar(30)         NULL,
   [LNAME]                            nvarchar(30)         NULL,
   [NAME_SUFFIX]                      nvarchar(5)          NULL,
   [SSNTIN]                           nvarchar(9)          NULL,
   [DOB]                              datetime             NULL,
   [MOTHER_MAIDENNAME]                nvarchar(50)         NULL,
   [IS_CURRENT]                       nchar(1)             NULL,
   [IS_EMPLOYEE]                      nchar(1)             NULL,
   [CUSTOMER_AS_YEARS]                int                  NULL,
   [CUSTOMER_AS_MONTHS]               int                  NULL,
   [EMAIL_ADDR]                       nvarchar(256)        NULL,
   [HASCHECKINGACCT]                  nchar(1)             NULL,
   [CHECKING_ACT_BAL]                 decimal(18,3)        NULL,
   [BU_ACT_BAL]                       decimal(18,3)        NULL,
   [SHARE_ACCT_BAL]                   decimal(18,3)        NULL,
   [QUALIFILESCORE]                   decimal(18,3)        NULL,
   [QUALIFILESCORE_DATE]              datetime             NULL,
   [NO_FUN_AUTO_30DAYS]               int                  NULL,
   [NO_ASLQACCT]                      int                  NULL,
   [NO_NSFS_LAST6MONTHS]              int                  NULL,
   [TOT_NO_NSFS_LAST6MONTHS]          int                  NULL,
   [NO_NSFS_LAST24MONTHS]             int                  NULL,
   [ALLLOAN_CHOFFPAID]                decimal(18,3)        NULL,
   [AGG_BUS_LOANS]                    int                  NULL,
   [AGG_SEC_LOANS]                    int                  NULL,
   [AGG_PER_LOANS]                    int                  NULL,
   [HAS_CHKNG_ACCT]                   nchar(1)             NULL,
   [NON_MORT_CREDITCHOFF]             nchar(1)             NULL,
   [DEPOSITACCT_CHOFF]                nchar(1)             NULL,
   [ALLDEPOSIT_ACCT_CHOFFPAID]        nchar(1)             NULL,
   [LOAN_CHOFF]                       nchar(1)             NULL,
   [BANKRUPTCY_FLAG]                  nchar(1)             NULL,
   [CREDITCARD_CHOFF]                 nchar(1)             NULL,
   [CREDITCARD_CHOFFPAID]             nchar(1)             NULL,
   [PERSON_REC_FOUND]                 nchar(1)             NULL,
   [LDFM_FLAG]                        nchar(1)             NULL,
   [LDFM_INACT_DATE]                  datetime             NULL,
   [PLATFORM_SOURCE]                  nvarchar(100)        NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([CUSTOMER_ID]), CLUSTERED COLUMNSTORE INDEX)
;
