-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------

CREATE TABLE [clt_NetO].[WG_RPT_IPG_DETAIL]
(
   [LNUM]                             nchar(20)            NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              datetime2(7)         NULL,
   [INVESTOR_CODE]                    nvarchar(4)          NULL,
   [PRODUCT_CODE]                     nvarchar(4)          NULL,
   [PRODUCT_NAME]                     nvarchar(80)         NULL,
   [PROGRAM_CODE]                     nvarchar(4)          NULL,
   [PROGRAM_NAME]                     nvarchar(80)         NULL,
   [PRICE_GROUP_CODE]                 nvarchar(4)          NULL,
   [PRICE_GROUP_CODE_NAME]            nvarchar(80)         NULL,
   [IPG_NAME]                         nvarchar(240)        NULL,
   [SECONDARY_LOAN_TYPE]              nvarchar(128)        NULL,
   [SECONDARY_LOAN_TYPE_DESC]         nvarchar(256)        NULL,
   [PREPAY_PENALTY_TYPE]              nvarchar(128)        NULL,
   [PREPAY_PENALTY_TYPE_DESC]         nvarchar(256)        NULL,
   [OVER_ALLOW_PCT]                   numeric(16,6)        NULL,
   [SHORT_ALLOW_PCT]                  numeric(16,6)        NULL,
   [OVER_SPLIT_PCT]                   numeric(16,6)        NULL,
   [SHORT_SPLIT_PCT]                  numeric(16,6)        NULL,
   [REQUIRES_MERS]                    nchar(1)             NULL,
   [REQUIRES_MI]                      nchar(1)             NULL,
   [ONE_TIMECLOSE_CONST]              nchar(1)             NULL,
   [INTERIM_CONSTRUCTION]             nchar(1)             NULL,
   [ASSUMABLE]                        nchar(1)             NULL,
   [CONV_PERIOD_ST]                   smallint             NULL,
   [CONV_PERIOD_END]                  smallint             NULL,
   [EZD_PRODUCT]                      nchar(1)             NULL,
   [HMDA_REPORTABLE]                  nchar(1)             NULL,
   [BUYDOWN_ALLOWED]                  nchar(1)             NULL,
   [HELOC_ALLOW_YN]                   nchar(1)             NULL,
   [PROD_PROF_TRUE]                   nchar(1)             NULL,
   [PRICE_NAME]                       nvarchar(240)        NULL,
   [ALLOW_DPA]                        nchar(1)             NULL,
   [AVAIL_BTOC]                       nchar(1)             NULL,
   [FIRST_LOCK_IND]                   nchar(1)             NULL,
   [OLD_AGENCY_NUM_IND]               nchar(1)             NULL,
   [PRODUCT_IDENTIFIER]               nvarchar(80)         NULL,
   [SERVICING_INTERFACE_IND]          nvarchar(30)         NULL,
   [SERVICING_LOCATION]               nchar(20)            NULL,
   [SUB_PRIME_IND]                    nchar(1)             NULL,
   [MI_REQUIRE]                       nchar(1)             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([LNUM]), CLUSTERED COLUMNSTORE INDEX)
;
