-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwWG_RPT_DATES]
AS
   SELECT
      x.[LNUM],
      x.[APPLICATION_DATE],
      x.[APPRAISAL_ORDER_DATE],
      x.[APPRAISAL_RECVD_DATE],
      x.[CANCELLED_DATE],
      x.[CLOSED_DATE],
      x.[COMMITMENT_EXP_DATE_OVR],
      x.[CREATE_DATE],
      x.[DENIAL_DATE],
      x.[DISBURSEMENT_DATE],
      x.[DOCS_DRAWN_DATE],
      x.[EST_CLOSE_DATE],
      x.[FILE_SUB_DATE],
      x.[FLOOD_ORDER_DATE],
      x.[FLOOD_RECVD_DATE],
      x.[FUNDED_DATE],
      x.[LOCKED_DATE],
      x.[NOIA_DATE],
      x.[ORIGINATION_DATE],
      x.[PROCESSING_BEGIN_DATE],
      x.[READY_FOR_DOCS_DATE],
      x.[REQ_ADDTL_PROC_DATE],
      x.[TITLE_ORDER_DATE],
      x.[TITLE_RECVD_DATE],
      x.[UW_DECISION_DATE],
      x.[WITHDRAWN_DATE],
      x.[LOCK_EXP_DATE],
      x.[INVLK_COMMITMENT_DATE],
      x.[INVLK_COMMITMENT_EXP_DATE],
      x.[INVLK_COMMITMENT_CNFRM_DATE],
      x.[READY_SHIP_DATE],
      x.[RESCISSION_EXP_DATE],
      x.[SHIPPED_DATE],
      x.[INV_FUNDED_DATE],
      x.[READY_FUND_DATE],
      x.[READY_UW_DATE],
      x.[DISCLOSURE_DATE],
      x.[INIT_DISCLOSURE_DATE],
      x.[REDISCLOSURE_DATE],
      x.[FINAL_DISCLOSURE_DATE],
      x.[THREEDAY_DISCLOSURE_DATE],
      x.[FIRST_CREDIT_RPT_DATE],
      x.[LAST_CREDIT_RPT_DATE],
      x.[FINAL_DOCS_SHIPPED],
      x.[HCM_DISCL_DT],
      x.[SYS_BORROWER_SITUATION_DATE],
      x.[MAN_BORROWER_SITUATION_DATE],
      x.[MATURITY_DATE],
      x.[FIRST_PMT_DATE],
      x.[APPROVAL_DATE],
      x.[SENT_TO_UNDERWRITING],
      x.[PURCHASE_DATE],
      x.[DOCUMENT_DATE],
      x.[CLOSING_PROXY_DATE],
      x.[CUDATE],
      x.[NOI_SENT_DATE],
      x.[NOI_START_DATE],
      x.[NOI_END_DATE],
      x.[FLOOD_DETMN_LETTER_DATE],
      x.[UW_DOC_EXP_DATE],
      x.[CLOSING_DOC_EXP_DATE],
      x.[CLOSING_DOCS_DUE_DATE],
      x.[SALES_CONTRACT_DATE],
      x.[FILE_RECEIVED_DATE],
      x.[UW_DECISION_EXP_DATE],
      x.[APPRAISAL_DUE_DATE],
      x.[APPRAISAL_RCVD_DATE],
      x.[TITLE_INS_ORDERED_DATE],
      x.[TITLE_INS_RCVD_DATE],
      x.[APPRAISAL_ISSUE_DATE],
      x.[MISC_7_DATE],
      x.[ASSET_EXP_DOC_DATE],
      x.[SUSPENDED_DATE],
      x.[DISBURSEMENT_ISSUE_DATE],
      x.[PREQUALIFY_DATE],
      x.[UW_APPROVAL_EXP_DATE],
      x.[CONFIRMED_LOCK_DATE],
      x.[UW_DECISION_DATETIME]
   FROM [clt_NetO].[WG_RPT_DATES] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
