-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwWG_RPT_LOAN]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[CLNUM] AS [CLNUM],
      HASHBYTES('SHA2_256', x.[EXTERNAL_LNUM]) AS [EXTERNAL_LNUM],
      x.[JPM_LNUM] AS [JPM_LNUM],
      x.[AMORTIZATION] AS [AMORTIZATION],
      x.[AMORTIZATION_DESC] AS [AMORTIZATION_DESC],
      x.[CHANNEL] AS [CHANNEL],
      x.[CHANNEL_DESC] AS [CHANNEL_DESC],
      HASHBYTES('SHA2_256', CAST(x.[CREDIT_SCORE] AS NVARCHAR(50))) AS [CREDIT_SCORE],
      x.[DOC_TYPE] AS [DOC_TYPE],
      x.[DOC_TYPE_DESC] AS [DOC_TYPE_DESC],
      x.[LEAD_SOURCE] AS [LEAD_SOURCE],
      x.[LEAD_SOURCE_DESC] AS [LEAD_SOURCE_DESC],
      x.[LIEN_POSITION] AS [LIEN_POSITION],
      x.[LIEN_POSITION_DESC] AS [LIEN_POSITION_DESC],
      x.[LOAN_PURPOSE] AS [LOAN_PURPOSE],
      x.[LOAN_PURPOSE_DESC] AS [LOAN_PURPOSE_DESC],
      x.[LOAN_STATUS] AS [LOAN_STATUS],
      x.[LOAN_STATUS_DESC] AS [LOAN_STATUS_DESC],
      x.[LOAN_TYPE] AS [LOAN_TYPE],
      x.[LOAN_TYPE_DESC] AS [LOAN_TYPE_DESC],
      x.[OCCUPANCY] AS [OCCUPANCY],
      x.[OCCUPANCY_DESC] AS [OCCUPANCY_DESC],
      x.[PREPAY_PENALTY_YN] AS [PREPAY_PENALTY_YN],
      x.[PRODUCT] AS [PRODUCT],
      x.[PRODUCT_DESC] AS [PRODUCT_DESC],
      x.[PROGRAM] AS [PROGRAM],
      x.[PROGRAM_DESC] AS [PROGRAM_DESC],
      x.[UW_DISPOSITION] AS [UW_DISPOSITION],
      x.[UW_DISPOSITION_DESC] AS [UW_DISPOSITION_DESC],
      x.[LOAN_LOCKED] AS [LOAN_LOCKED],
      x.[INVLK_COMMITMENT_NBR] AS [INVLK_COMMITMENT_NBR],
      x.[INVLK_LOCKED] AS [INVLK_LOCKED],
      x.[INVLK_LOCK_STATUS] AS [INVLK_LOCK_STATUS],
      x.[INVLK_LOCK_STATUS_DESC] AS [INVLK_LOCK_STATUS_DESC],
      x.[LOAN_ACTIVITY] AS [LOAN_ACTIVITY],
      x.[REFI_PURPOSE] AS [REFI_PURPOSE],
      x.[REFI_PURPOSE_DESC] AS [REFI_PURPOSE_DESC],
      x.[AGENCY_CASE_NUMBER] AS [AGENCY_CASE_NUMBER],
      x.[LOAN_IS_PREQUAL_YN] AS [LOAN_IS_PREQUAL_YN],
      x.[MORTGAGE_TYPE] AS [MORTGAGE_TYPE],
      x.[MORTGAGE_TYPE_DESC] AS [MORTGAGE_TYPE_DESC],
      x.[LOAN_TERM] AS [LOAN_TERM],
      x.[FUNDING_METHOD] AS [FUNDING_METHOD],
      x.[FUNDING_METHOD_DESC] AS [FUNDING_METHOD_DESC],
      x.[DELIVERY_TERMS] AS [DELIVERY_TERMS],
      x.[DELIVERY_TERMS_DESC] AS [DELIVERY_TERMS_DESC],
      x.[CONDITION_TEXT] AS [CONDITION_TEXT],
      HASHBYTES('SHA2_256', x.[CUSTATE]) AS [CUSTATE],
      x.[CUISACTIVE_YN] AS [CUISACTIVE_YN],
      x.[ESCROW_WAIVER] AS [ESCROW_WAIVER],
      x.[REDISCLOSE_YN] AS [REDISCLOSE_YN],
      x.[PRODUCT_RATECODE] AS [PRODUCT_RATECODE],
      x.[UW_TOLERANCE_FLAG] AS [UW_TOLERANCE_FLAG],
      x.[GFE_TOLERANCE_FLAG] AS [GFE_TOLERANCE_FLAG],
      x.[LOCK_CONFIRM_YN] AS [LOCK_CONFIRM_YN],
      x.[CULTURE_CODE] AS [CULTURE_CODE],
      x.[LOCK_TYPE] AS [LOCK_TYPE],
      x.[LOCK_TYPE_DESC] AS [LOCK_TYPE_DESC]
   FROM [clt_NetO].[WG_RPT_LOAN] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
