-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_restricted].[VwWG_TLR_RECORDING_INFO]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[DBID] AS [DBID],
      HASHBYTES('SHA2_256', CAST(x.[ROWSERIALNO] AS NVARCHAR(50))) AS [ROWSERIALNO],
      HASHBYTES('SHA2_256', CAST(x.[REOCNTR] AS NVARCHAR(50))) AS [REOCNTR],
      HASHBYTES('SHA2_256', CAST(x.[RECORDING_DATE] AS NVARCHAR(50))) AS [RECORDING_DATE],
      x.[DOCUMENT_TYPE] AS [DOCUMENT_TYPE],
      A0.[Descript] AS [DOCUMENT_TYPE_X],
      HASHBYTES('SHA2_256', x.[DOCUMENT_NUMBER]) AS [DOCUMENT_NUMBER],
      HASHBYTES('SHA2_256', x.[DOC_TYPE_OTHER_DESC]) AS [DOC_TYPE_OTHER_DESC],
      x.[JURISDICTION_NAME] AS [JURISDICTION_NAME],
      x.[JURISDICTION_TYPE] AS [JURISDICTION_TYPE],
      A1.[Descript] AS [JURISDICTION_TYPE_X],
      x.[JUDICIAL_DISTRICT] AS [JUDICIAL_DISTRICT],
      HASHBYTES('SHA2_256', x.[RECORDING_DISTRICT]) AS [RECORDING_DISTRICT],
      x.[BOOK_TYPE] AS [BOOK_TYPE],
      A2.[Descript] AS [BOOK_TYPE_X],
      x.[BOOK_NUMBER] AS [BOOK_NUMBER],
      HASHBYTES('SHA2_256', x.[INSTRUMENT_NUMBER]) AS [INSTRUMENT_NUMBER],
      HASHBYTES('SHA2_256', x.[RECORDING_OFFICE]) AS [RECORDING_OFFICE],
      HASHBYTES('SHA2_256', x.[RECORDING_STATE]) AS [RECORDING_STATE],
      HASHBYTES('SHA2_256', x.[RECORDING_COUNTY]) AS [RECORDING_COUNTY],
      x.[PAGE_NUMBER] AS [PAGE_NUMBER],
      x.[VOLUME_NUMBER] AS [VOLUME_NUMBER],
      HASHBYTES('SHA2_256', x.[RECORDING_CITY]) AS [RECORDING_CITY]
   FROM [clt_NetO].[WG_TLR_RECORDING_INFO] x
      LEFT JOIN [clt_NetO].[SymbolLookup] A0 on x.[DOCUMENT_TYPE] = A0.[DBSYMBOL] AND A0.[TableName] = 'WG_TLR_RECORDING_INFO' and A0.[COLUMNNAME] = 'DOCUMENT_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A1 on x.[JURISDICTION_TYPE] = A1.[DBSYMBOL] AND A1.[TableName] = 'WG_TLR_RECORDING_INFO' and A1.[COLUMNNAME] = 'JURISDICTION_TYPE'
      LEFT JOIN [clt_NetO].[SymbolLookup] A2 on x.[BOOK_TYPE] = A2.[DBSYMBOL] AND A2.[TableName] = 'WG_TLR_RECORDING_INFO' and A2.[COLUMNNAME] = 'BOOK_TYPE'
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
