-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas].[VwGF_TL_HOUSING_PROPSD]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      HASHBYTES('SHA2_256', CAST(x.[GROUND_RENT_AMT] AS NVARCHAR(50))) AS [GROUND_RENT_AMT],
      HASHBYTES('SHA2_256', CAST(x.[GROUND_RENT_OVRD] AS NVARCHAR(50))) AS [GROUND_RENT_OVRD],
      x.[HAZARD_INS_AMT] AS [HAZARD_INS_AMT],
      x.[HAZARD_INS_OVRD] AS [HAZARD_INS_OVRD],
      x.[HOA_DUES_AMT] AS [HOA_DUES_AMT],
      x.[HOA_DUES_OVRD] AS [HOA_DUES_OVRD],
      x.[LEASEHOLD_PMT_AMT] AS [LEASEHOLD_PMT_AMT],
      x.[LEASEHOLD_PMT_OVRD] AS [LEASEHOLD_PMT_OVRD],
      x.[MAINT_MISC_AMT] AS [MAINT_MISC_AMT],
      x.[MAINT_MISC_OVRD] AS [MAINT_MISC_OVRD],
      x.[MI_AMT] AS [MI_AMT],
      x.[MI_OVRD] AS [MI_OVRD],
      x.[MTG_PITI_AMT] AS [MTG_PITI_AMT],
      x.[MTG_PITI_OVRD] AS [MTG_PITI_OVRD],
      x.[MTG_PRIN_INT_AMT] AS [MTG_PRIN_INT_AMT],
      x.[MTG_PRIN_INT_OVRD] AS [MTG_PRIN_INT_OVRD],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_MTG_PITI_AMT] AS NVARCHAR(50))) AS [OTHER_MTG_PITI_AMT],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_MTG_PITI_OVRD] AS NVARCHAR(50))) AS [OTHER_MTG_PITI_OVRD],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_MTG_PRIN_INT_AMT] AS NVARCHAR(50))) AS [OTHER_MTG_PRIN_INT_AMT],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_MTG_PRIN_INT_OVRD] AS NVARCHAR(50))) AS [OTHER_MTG_PRIN_INT_OVRD],
      x.[REAL_ESTATE_TAX_AMT] AS [REAL_ESTATE_TAX_AMT],
      x.[REAL_ESTATE_TAX_OVRD] AS [REAL_ESTATE_TAX_OVRD],
      x.[UTILITIES_AMT] AS [UTILITIES_AMT],
      x.[UTILITIES_OVRD] AS [UTILITIES_OVRD],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_EXP_ALL] AS NVARCHAR(50))) AS [OTHER_EXP_ALL],
      x.[TOTAL_PROPOSED] AS [TOTAL_PROPOSED],
      x.[ASSESSMENT_AMT] AS [ASSESSMENT_AMT],
      x.[ASSESSMENT_OVRD] AS [ASSESSMENT_OVRD],
      HASHBYTES('SHA2_256', CAST(x.[FLOOD_INS_AMT] AS NVARCHAR(50))) AS [FLOOD_INS_AMT],
      HASHBYTES('SHA2_256', CAST(x.[FLOOD_INS_OVRD] AS NVARCHAR(50))) AS [FLOOD_INS_OVRD],
      x.[WATER_PURI_AMT] AS [WATER_PURI_AMT],
      x.[WATER_PURI_OVRD] AS [WATER_PURI_OVRD],
      x.[SUPPLE_INS_AMT_OVRD] AS [SUPPLE_INS_AMT_OVRD],
      x.[SUPPLE_INS_AMT] AS [SUPPLE_INS_AMT],
      x.[HOMEOWN_INS_AMT_OVRD] AS [HOMEOWN_INS_AMT_OVRD],
      x.[HOMEOWN_INS_AMT] AS [HOMEOWN_INS_AMT]
   FROM [clt_NetO].[GF_TL_HOUSING_PROPSD] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
