-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas].[VwWG_CRM_CUSTOMER_ACCT_DTL_SUMM_]
AS
   SELECT
      HASHBYTES('SHA2_256', x.[CURRENT_CUSTOMERID]) AS [CURRENT_CUSTOMERID],
      x.[AG_DA_ACCT_TYPE] AS [AG_DA_ACCT_TYPE],
      HASHBYTES('SHA2_256', CAST(x.[AG_DA_ACCT_TOTALASSETS] AS NVARCHAR(50))) AS [AG_DA_ACCT_TOTALASSETS],
      x.[TOTALASSETSDAVGLAST60DAYS] AS [TOTALASSETSDAVGLAST60DAYS],
      x.[TOTALASSETSDAVGLAST180DAYS] AS [TOTALASSETSDAVGLAST180DAYS],
      x.[SAVINGACCBALDAVGLAST60DAYS] AS [SAVINGACCBALDAVGLAST60DAYS],
      x.[SAVINGACCBALDAVGLAST180DAYS] AS [SAVINGACCBALDAVGLAST180DAYS],
      HASHBYTES('SHA2_256', CAST(x.[AGDIRECRDEPOSITVLAST30DAYS] AS NVARCHAR(50))) AS [AGDIRECRDEPOSITVLAST30DAYS],
      x.[AGGREGATEDIREALUELAST60DAYS] AS [AGGREGATEDIREALUELAST60DAYS],
      HASHBYTES('SHA2_256', CAST(x.[AGDEPOSITVALUELAST30DAYS] AS NVARCHAR(50))) AS [AGDEPOSITVALUELAST30DAYS],
      HASHBYTES('SHA2_256', CAST(x.[AGDEPOSITVALUELAST60DAYS] AS NVARCHAR(50))) AS [AGDEPOSITVALUELAST60DAYS],
      HASHBYTES('SHA2_256', CAST(x.[AGDEPOSITVALUELAST180DAYS] AS NVARCHAR(50))) AS [AGDEPOSITVALUELAST180DAYS]
   FROM [clt_NetO].[WG_CRM_CUSTOMER_ACCT_DETAIL_SUMMARY] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
;
