-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas].[VwWG_RPT_WORKFLOW]
AS
   SELECT
      x.[WORKTYPE_INSTANCE] AS [WORKTYPE_INSTANCE],
      x.[LNUM] AS [LNUM],
      x.[WORKTYPE_CODE] AS [WORKTYPE_CODE],
      x.[EST_EFFORT_TIME] AS [EST_EFFORT_TIME],
      x.[EXP_RESOLVE_DATE] AS [EXP_RESOLVE_DATE],
      x.[PROC_GROUP] AS [PROC_GROUP],
      x.[QUEUED_DATE] AS [QUEUED_DATE],
      x.[QUEUED_DATETIME] AS [QUEUED_DATETIME],
      x.[QUEUED_TIME] AS [QUEUED_TIME],
      x.[RESERVED_USER] AS [RESERVED_USER],
      x.[RESOLVE_DATE] AS [RESOLVE_DATE],
      x.[RESOLVE_TYPE] AS [RESOLVE_TYPE],
      x.[WF_ACTIVITY] AS [WF_ACTIVITY],
      x.[WF_STATUS] AS [WF_STATUS],
      x.[WORK_OPENED_DATE] AS [WORK_OPENED_DATE],
      x.[WORK_OPENED_DATETIME] AS [WORK_OPENED_DATETIME],
      x.[WORKED_TIME] AS [WORKED_TIME],
      x.[WORKTYPE] AS [WORKTYPE],
      x.[RESERVED_USERID] AS [RESERVED_USERID],
      x.[PROC_GROUP_CODE] AS [PROC_GROUP_CODE]
   FROM [clt_NetO].[WG_RPT_WORKFLOW] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
