-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas].[VwWG_CORR_FUNDING]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[RESPA_CUTOFF_DAY] AS [RESPA_CUTOFF_DAY],
      x.[RESPA_CUTOFF_DAY_OVRD] AS [RESPA_CUTOFF_DAY_OVRD],
      x.[PURCHASE_TYPE] AS [PURCHASE_TYPE],
      x.[FED_REF_NBR] AS [FED_REF_NBR],
      x.[FED_REF_NBR_OVRD] AS [FED_REF_NBR_OVRD],
      x.[WIRE_SCHED_DATE] AS [WIRE_SCHED_DATE],
      x.[WIRE_SCHED_DATE_OVRD] AS [WIRE_SCHED_DATE_OVRD],
      x.[WIRE_SENT_DATE_OVRD] AS [WIRE_SENT_DATE_OVRD],
      x.[WIRE_SENT_DATE] AS [WIRE_SENT_DATE],
      x.[ESCROW_BAL_OVRD] AS [ESCROW_BAL_OVRD],
      x.[LENDER_PD_DISB_OVR] AS [LENDER_PD_DISB_OVR],
      x.[MIP_OVRD] AS [MIP_OVRD],
      x.[INT_PD_DUE_OVRD] AS [INT_PD_DUE_OVRD],
      x.[AM_CURTAILMENT] AS [AM_CURTAILMENT],
      x.[AM_CURT_OVRD] AS [AM_CURT_OVRD],
      x.[TOTAL_PRICE_AMOUNT] AS [TOTAL_PRICE_AMOUNT],
      x.[TOTAL_FEES_ADJS] AS [TOTAL_FEES_ADJS],
      x.[NET_ESCROW_AMT] AS [NET_ESCROW_AMT],
      x.[CORS_INTEREST_PAID] AS [CORS_INTEREST_PAID],
      x.[TOTAL_WIRE_AMOUNT] AS [TOTAL_WIRE_AMOUNT],
      x.[SELWIRE_ACCOUNT] AS [SELWIRE_ACCOUNT]
   FROM [clt_NetO].[WG_CORR_FUNDING] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
