CREATE TABLE [clt_Alkami].[db_form_field]
(
   [form_id]                          varchar(40)          NOT NULL,
   [field_name]                       nvarchar(80)         NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [condition]                        text                 NULL,
   [entry_name]                       text                 NULL,
   [title]                            text                 NULL,
   [tooltip]                          text                 NULL,
   [field_type_enum_id]               varchar(40)          NULL,
   [layout_sequence_num]              numeric(20,0)        NULL,
   [is_required]                      char(1)              NULL,
   [print_page_number]                numeric(20,0)        NULL,
   [print_top]                        varchar(63)          NULL,
   [print_left]                       varchar(63)          NULL,
   [print_bottom]                     varchar(63)          NULL,
   [print_right]                      varchar(63)          NULL,
   [print_width]                      varchar(63)          NULL,
   [print_height]                     varchar(63)          NULL,
   [print_text_align]                 varchar(63)          NULL,
   [print_vertical_align]             varchar(63)          NULL,
   [print_font_size]                  varchar(63)          NULL,
   [print_font_family]                varchar(63)          NULL,
   [is_excluded]                      char(1)              NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([form_id]), CLUSTERED COLUMNSTORE INDEX)
;
