CREATE TABLE [clt_Alkami].[financial_worksheet_account]
(
   [financial_worksheet_id]           varchar(40)          NOT NULL,
   [account_id]                       varchar(255)         NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [status_id]                        varchar(40)          NULL,
   [account_type_enum_id]             varchar(40)          NULL,
   [category_enum_id]                 varchar(40)          NULL,
   [account_number]                   text                 NULL,
   [creditor_party_id]                varchar(40)          NULL,
   [creditor_name]                    text                 NULL,
   [subcode]                          varchar(63)          NULL,
   [open_date]                        date                 NULL,
   [closed_date]                      date                 NULL,
   [remarks]                          text                 NULL,
   [balance]                          numeric(25,5)        NULL,
   [payment]                          numeric(25,5)        NULL,
   [secured]                          char(1)              NULL,
   [include]                          char(1)              NULL,
   [created_by_user_id]               varchar(40)          NULL,
   [created_on]                       datetime             NULL,
   [payment_status_enum_id]           varchar(40)          NULL,
   [payment_frequency_enum_id]        varchar(40)          NULL,
   [creditor_code]                    text                 NULL,
   [last_updated_date]                date                 NULL,
   [credit_limit]                     numeric(25,5)        NULL,
   [highest_amount_owed]              numeric(25,5)        NULL,
   [available_credit]                 numeric(25,5)        NULL,
   [has_bankruptcy]                   char(1)              NULL,
   [number_of_delinquencies]          numeric(20,0)        NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([financial_worksheet_id]), CLUSTERED COLUMNSTORE INDEX)
;
