CREATE TABLE [clt_Alkami].[party_acctg_preference]
(
   [organization_party_id]            varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [fiscal_year_start_month]          numeric(20,0)        NULL,
   [fiscal_year_start_day]            numeric(20,0)        NULL,
   [real_time_gl_summary]             char(1)              NULL,
   [hourly_time_period_type_id]       varchar(40)          NULL,
   [salary_time_period_type_id]       varchar(40)          NULL,
   [tax_form_enum_id]                 varchar(40)          NULL,
   [payroll_tax_form_enum_id]         varchar(40)          NULL,
   [tax_classification_enum_id]       varchar(40)          NULL,
   [employer_class_enum_id]           varchar(40)          NULL,
   [cogs_method_enum_id]              varchar(40)          NULL,
   [base_currency_uom_id]             varchar(40)          NULL,
   [local_currency_uom_id]            varchar(40)          NULL,
   [invoice_sequence_enum_id]         varchar(40)          NULL,
   [invoice_id_prefix]                varchar(63)          NULL,
   [use_invoice_id_for_returns]       char(1)              NULL,
   [order_sequence_enum_id]           varchar(40)          NULL,
   [order_id_prefix]                  varchar(63)          NULL,
   [refund_payment_method_id]         varchar(40)          NULL,
   [error_gl_journal_id]              varchar(40)          NULL,
   [gl_account_code_mask]             varchar(63)          NULL,
   [settlement_term_id]               varchar(40)          NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([organization_party_id]), CLUSTERED COLUMNSTORE INDEX)
;
