CREATE TABLE [clt_Alkami].[payment]
(
   [payment_id]                       varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [payment_type_enum_id]             varchar(40)          NULL,
   [from_party_id]                    varchar(40)          NULL,
   [to_party_id]                      varchar(40)          NULL,
   [payment_instrument_enum_id]       varchar(40)          NULL,
   [payment_method_id]                varchar(40)          NULL,
   [to_payment_method_id]             varchar(40)          NULL,
   [payment_gateway_config_id]        varchar(40)          NULL,
   [order_id]                         varchar(40)          NULL,
   [order_part_seq_id]                varchar(40)          NULL,
   [order_item_seq_id]                varchar(40)          NULL,
   [status_id]                        varchar(40)          NULL,
   [effective_date]                   datetime             NULL,
   [settlement_date]                  datetime             NULL,
   [due_date]                         datetime             NULL,
   [payment_auth_code]                varchar(63)          NULL,
   [payment_ref_num]                  varchar(63)          NULL,
   [comments]                         text                 NULL,
   [memo]                             text                 NULL,
   [dist_group_enum_id]               varchar(40)          NULL,
   [amount]                           numeric(24,4)        NULL,
   [amount_uom_id]                    varchar(40)          NULL,
   [applied_total]                    numeric(24,4)        NULL,
   [unapplied_total]                  numeric(24,4)        NULL,
   [for_invoice_id]                   varchar(40)          NULL,
   [refund_for_payment_id]            varchar(40)          NULL,
   [fin_account_id]                   varchar(40)          NULL,
   [fin_account_auth_id]              varchar(40)          NULL,
   [fin_account_trans_id]             varchar(40)          NULL,
   [override_gl_account_id]           varchar(40)          NULL,
   [override_org_party_id]            varchar(40)          NULL,
   [party_relationship_id]            varchar(40)          NULL,
   [time_period_id]                   varchar(40)          NULL,
   [original_currency_amount]         numeric(24,4)        NULL,
   [original_currency_uom_id]         varchar(40)          NULL,
   [present_flag]                     char(1)              NULL,
   [swiped_flag]                      char(1)              NULL,
   [process_attempt]                  numeric(20,0)        NULL,
   [needs_nsf_retry]                  char(1)              NULL,
   [visit_id]                         varchar(40)          NULL,
   [acctg_trans_result_enum_id]       varchar(40)          NULL,
   [reconcile_status_id]              varchar(40)          NULL,
   [payment_method_file_id]           varchar(40)          NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([payment_id]), CLUSTERED COLUMNSTORE INDEX)
;
