CREATE TABLE [clt_Alkami].[person]
(
   [party_id]                         varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [salutation]                       text                 NULL,
   [first_name]                       nvarchar(50)         NULL,
   [middle_name]                      text                 NULL,
   [last_name]                        nvarchar(50)         NULL,
   [personal_title]                   text                 NULL,
   [suffix]                           text                 NULL,
   [nickname]                         text                 NULL,
   [gender]                           char(1)              NULL,
   [birth_date]                       date                 NULL,
   [deceased_date]                    date                 NULL,
   [height]                           float                NULL,
   [weight]                           float                NULL,
   [mothers_maiden_name]              text                 NULL,
   [marital_status_enum_id]           varchar(40)          NULL,
   [employment_status_enum_id]        varchar(40)          NULL,
   [residence_status_enum_id]         varchar(40)          NULL,
   [occupation]                       text                 NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([party_id]), CLUSTERED COLUMNSTORE INDEX)
;
