CREATE TABLE [clt_Alkami].[postal_address]
(
   [contact_mech_id]                  varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [to_name]                          text                 NULL,
   [attn_name]                        text                 NULL,
   [address1]                         text                 NULL,
   [address2]                         text                 NULL,
   [unit_number]                      text                 NULL,
   [directions]                       text                 NULL,
   [city]                             nvarchar(120)        NULL,
   [city_geo_id]                      varchar(40)          NULL,
   [school_district_geo_id]           varchar(40)          NULL,
   [county_geo_id]                    varchar(40)          NULL,
   [state_province_geo_id]            varchar(40)          NULL,
   [country_geo_id]                   varchar(40)          NULL,
   [postal_code]                      varchar(63)          NULL,
   [postal_code_ext]                  varchar(63)          NULL,
   [postal_code_geo_id]               varchar(40)          NULL,
   [geo_point_id]                     varchar(40)          NULL,
   [commercial]                       char(1)              NULL,
   [access_code]                      varchar(63)          NULL,
   [telecom_contact_mech_id]          varchar(40)          NULL,
   [email_contact_mech_id]            varchar(40)          NULL,
   [ship_gateway_address_id]          text                 NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([contact_mech_id]), CLUSTERED COLUMNSTORE INDEX)
;
