-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_restricted].[VwUWAPPR]
AS
   SELECT
      x.[LNUM],
      x.[CNTR],
      x.[DBID],
      x.[S_PRPTYP],
      x.[UNITNUM],
      x.[PROJNAME],
      x.[APPRAISAL],
      x.[APPRAISER],
      x.[APPRDATE],
      x.[APPRVALUE],
      x.[LANDVALUE],
      x.[ORIGCOST],
      x.[YRPURCH],
      x.[YRBUILT],
      x.[LICENSE],
      x.[ADDR],
      HASHBYTES('SHA2_256', x.[CITY]) AS [CITY],
      x.[STATE],
      HASHBYTES('SHA2_256', x.[ZIP]) AS [ZIP],
      x.[PHONE],
      x.[FAX],
      x.[NET1],
      x.[GROSS1],
      x.[NET2],
      x.[GROSS2],
      x.[NET3],
      x.[GROSS3],
      x.[NET4],
      x.[GROSS4],
      x.[NET5],
      x.[GROSS5],
      x.[NET6],
      x.[GROSS6],
      x.[S_APPRTYPE],
      x.[SUBMFLG],
      x.[LANDTOVALUE],
      x.[APPRVALUEINDICATOR],
      x.[APPRLICENSECODE],
      x.[LOCATION],
      x.[ZONING],
      x.[SQFEET],
      x.[ACREAGE],
      x.[EFFAGE],
      x.[FORSALE],
      x.[LAST12],
      x.[LESS750],
      x.[HVE_EFFECTIVE_DT],
      x.[S_APPRFORMTYPE],
      x.[APPRFORMTYPEOTHDESC],
      x.[S_PRPFORMTYPE],
      x.[PRPFORMTYPEOTHDESC],
      x.[S_PRPMETHODTYPE],
      x.[PRPMETHODTYPEOTHDESC],
      x.[S_LVLPRPRVW],
      x.[APPRLVLPRPRVWTYPEOTHDESC],
      HASHBYTES('SHA2_256', x.[APPR_SUPER_LIC]) AS [APPR_SUPER_LIC],
      x.[DATEORDERED],
      x.[ORDEREDBY],
      x.[DUEDATE],
      x.[QUOTE],
      x.[ACTUALCOST],
      x.[DATERECEIVED],
      x.[S_STATUS],
      x.[REQUESTEDDATE],
      x.[REQUESTEDBY],
      x.[DATEREVIEWED],
      x.[REVIEWEDBY],
      x.[RESPONSIVENESS],
      x.[TURNAROUNDTIME],
      x.[REPORTQUALITY],
      x.[REVISIONREQUIRED],
      x.[ACTUALFEEAMT],
      x.[INVOICENUMB],
      x.[INVOICEDATE],
      x.[REQUISITIONSENTDATE],
      x.[REQ_NOTES_DBID],
      x.[REQ_NOTES_SN],
      x.[REQAPPRCOMPANY],
      x.[REQAPPR],
      x.[SITEVALUE],
      x.[SUBJECTTOREPAIRS],
      x.[S_APPRMETH],
      x.[S_AVM],
      x.[S_AVMOTH],
      HASHBYTES('SHA2_256', x.[APPR_SUPER_FNAME]) AS [APPR_SUPER_FNAME],
      HASHBYTES('SHA2_256', x.[APPR_SUPER_LNAME]) AS [APPR_SUPER_LNAME],
      x.[APPRREINSPFEE],
      x.[APPR_COMMENTS],
      x.[RUSHED],
      x.[SENIORLVLRVW],
      x.[GROSSLIVINGAREA],
      x.[TOTAL_ROOMS],
      x.[BEDROOMS],
      x.[BATHS],
      x.[HOA_FEES],
      x.[FHA_VA_APPRAISER_CHUMSID],
      x.[ADDR2],
      x.[INV_COLL_PROG_ID],
      x.[FORECAST_STD_DEV],
      x.[S_HOA_FEES_PERIOD_TYPE]
   FROM [clt_NetO].[UWAPPR] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
