-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_restricted].[VwWG_BORR_INCOME_SRC_PAYSTUB]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[PS_CTR],
      x.[INC_SRC_CTR],
      HASHBYTES('SHA2_256', CAST(x.[YTD_FROM_DATE] AS NVARCHAR(50))) AS [YTD_FROM_DATE],
      HASHBYTES('SHA2_256', CAST(x.[YTD_TO_DATE] AS NVARCHAR(50))) AS [YTD_TO_DATE],
      x.[PAYSTUB_DATE],
      x.[AVGHOURSPERWEEK],
      x.[MONTHLYBASEPAY],
      x.[MONTHLYRATE],
      HASHBYTES('SHA2_256', CAST(x.[OVERTIME_PAY] AS NVARCHAR(50))) AS [OVERTIME_PAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_BASEPAY] AS NVARCHAR(50))) AS [YTD_BASEPAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_OVERTIMEPAY] AS NVARCHAR(50))) AS [YTD_OVERTIMEPAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_BONUSPAY] AS NVARCHAR(50))) AS [YTD_BONUSPAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_COMMISSIONPAY] AS NVARCHAR(50))) AS [YTD_COMMISSIONPAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_TOTALPAY] AS NVARCHAR(50))) AS [YTD_TOTALPAY],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_PAY] AS NVARCHAR(50))) AS [OTHER_PAY],
      x.[COMMISSION_PAY],
      HASHBYTES('SHA2_256', CAST(x.[DEPENDENT_CARE_BENEFITS] AS NVARCHAR(50))) AS [DEPENDENT_CARE_BENEFITS],
      x.[GARNISHMENTS],
      HASHBYTES('SHA2_256', CAST(x.[YTD_OTHERPAY] AS NVARCHAR(50))) AS [YTD_OTHERPAY],
      x.[LOAN_REPAYMENT],
      x.[PAYS_TOTAL_PAY],
      HASHBYTES('SHA2_256', CAST(x.[CALCULATED_INCOME] AS NVARCHAR(50))) AS [CALCULATED_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[OVR_CALCULATED_INCOME] AS NVARCHAR(50))) AS [OVR_CALCULATED_INCOME],
      HASHBYTES('SHA2_256', CAST(x.[OTHER_DEDUCTION] AS NVARCHAR(50))) AS [OTHER_DEDUCTION],
      x.[AVG_YTD_BASE],
      x.[AVG_YTD_GROSS],
      HASHBYTES('SHA2_256', x.[CHK_AVG_YTD_BASE]) AS [CHK_AVG_YTD_BASE],
      HASHBYTES('SHA2_256', x.[CHK_CURRENT_BASE]) AS [CHK_CURRENT_BASE],
      HASHBYTES('SHA2_256', x.[CHK_AVG_YTD_GROSS]) AS [CHK_AVG_YTD_GROSS],
      HASHBYTES('SHA2_256', CAST(x.[BONUS_PAY] AS NVARCHAR(50))) AS [BONUS_PAY],
      x.[PAYFREQ],
      HASHBYTES('SHA2_256', CAST(x.[BASE_HOURLY_PAY] AS NVARCHAR(50))) AS [BASE_HOURLY_PAY],
      HASHBYTES('SHA2_256', x.[CHK_BASE_HOURLY_PAY]) AS [CHK_BASE_HOURLY_PAY],
      x.[SUMMARY_CURRENT_NETPAY],
      HASHBYTES('SHA2_256', CAST(x.[OVERTIMEHOURS] AS NVARCHAR(50))) AS [OVERTIMEHOURS],
      HASHBYTES('SHA2_256', CAST(x.[OVERTIMERATE] AS NVARCHAR(50))) AS [OVERTIMERATE],
      HASHBYTES('SHA2_256', CAST(x.[BONUSHOURS] AS NVARCHAR(50))) AS [BONUSHOURS],
      HASHBYTES('SHA2_256', CAST(x.[BONUSRATE] AS NVARCHAR(50))) AS [BONUSRATE],
      x.[COMMISSIONHOURS],
      x.[COMMISSIONRATE],
      x.[OTHERHOURS],
      x.[OTHERRATE],
      x.[MILITARYHOURS],
      HASHBYTES('SHA2_256', CAST(x.[MILITARYRATE] AS NVARCHAR(50))) AS [MILITARYRATE],
      HASHBYTES('SHA2_256', CAST(x.[MILITARY_PAY] AS NVARCHAR(50))) AS [MILITARY_PAY],
      HASHBYTES('SHA2_256', CAST(x.[YTD_MILITARYPAY] AS NVARCHAR(50))) AS [YTD_MILITARYPAY],
      HASHBYTES('SHA2_256', CAST(x.[DOC_UPLOADED_DATE] AS NVARCHAR(50))) AS [DOC_UPLOADED_DATE],
      x.[DATA_UPDATED_DATE],
      x.[DATA_UPDATED_BYUSER],
      x.[OCR_DATA_FLAG],
      HASHBYTES('SHA2_256', x.[VALID_CARD]) AS [VALID_CARD]
   FROM [clt_NetO].[WG_BORR_INCOME_SRC_PAYSTUB] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
