-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwGF_TLR_RES_NADA_VAL]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[DBID] AS [DBID],
      x.[RESPONSEID] AS [RESPONSEID],
      x.[NADARESPONSEID] AS [NADARESPONSEID],
      x.[BASE_VALUE_TRADEIN] AS [BASE_VALUE_TRADEIN],
      x.[BASE_VALUE_LOAN] AS [BASE_VALUE_LOAN],
      x.[BASE_VALUE_RETAIL] AS [BASE_VALUE_RETAIL],
      x.[ADJUSTED_VALUE_TRADEIN] AS [ADJUSTED_VALUE_TRADEIN],
      x.[ADJUSTED_VALUE_LOAN] AS [ADJUSTED_VALUE_LOAN],
      x.[ADJUSTED_VALUE_RETAIL] AS [ADJUSTED_VALUE_RETAIL],
      x.[MILEAGE_ADJ] AS [MILEAGE_ADJ],
      x.[MSRP] AS [MSRP],
      x.[VALUE_SELECTED] AS [VALUE_SELECTED],
      x.[BASE_VALUE_LOAN_OVR] AS [BASE_VALUE_LOAN_OVR],
      x.[ACCESS_VALUE_LOAN] AS [ACCESS_VALUE_LOAN],
      x.[ACCESS_VALUE_TRADIN] AS [ACCESS_VALUE_TRADIN],
      x.[ACCESS_VALUE_RETAIL] AS [ACCESS_VALUE_RETAIL],
      x.[MILEAGE] AS [MILEAGE],
      x.[MILEADJLOAN] AS [MILEADJLOAN],
      x.[MILEADJRETAIL] AS [MILEADJRETAIL],
      x.[MILEADJTRADEIN] AS [MILEADJTRADEIN],
      x.[WEIGHT] AS [WEIGHT],
      x.[AVEMILEAGE] AS [AVEMILEAGE],
      x.[TRADEINVINACC] AS [TRADEINVINACC],
      x.[TRADEINVINACCMILE] AS [TRADEINVINACCMILE],
      x.[LOANVINACC] AS [LOANVINACC],
      x.[LOANVINACCMILE] AS [LOANVINACCMILE],
      x.[RETAILVINACC] AS [RETAILVINACC],
      x.[RETAILVINACCMILE] AS [RETAILVINACCMILE],
      x.[AVGTRADEIN] AS [AVGTRADEIN],
      x.[ROUGHTRADEIN] AS [ROUGHTRADEIN],
      x.[BASE_VALUE_ROUGH_TRADEIN] AS [BASE_VALUE_ROUGH_TRADEIN],
      x.[ACCESS_VALUE_ROUGH_TRADEIN] AS [ACCESS_VALUE_ROUGH_TRADEIN],
      x.[TOTAL_VALUE_ROUGH_TRADEIN] AS [TOTAL_VALUE_ROUGH_TRADEIN],
      x.[BASE_VALUE_CLEAN_TRADEIN] AS [BASE_VALUE_CLEAN_TRADEIN],
      x.[ACCESS_VALUE_CLEAN_TRADEIN] AS [ACCESS_VALUE_CLEAN_TRADEIN],
      x.[TOTAL_VALUE_CLEAN_TRADEIN] AS [TOTAL_VALUE_CLEAN_TRADEIN],
      x.[BASE_VALUE_AVG_TRADEIN] AS [BASE_VALUE_AVG_TRADEIN],
      x.[ACCESS_VALUE_AVG_TRADEIN] AS [ACCESS_VALUE_AVG_TRADEIN],
      x.[TOTAL_VALUE_AVG_TRADEIN] AS [TOTAL_VALUE_AVG_TRADEIN],
      x.[TOTAL_VALUE_RETAIL_TRADEIN] AS [TOTAL_VALUE_RETAIL_TRADEIN],
      x.[ASSETID_LINKED_TO_RESP] AS [ASSETID_LINKED_TO_RESP],
      x.[VALUATIONID_LINKED_TO_RESP] AS [VALUATIONID_LINKED_TO_RESP]
   FROM [clt_NetO].[GF_TLR_RES_NADA_VAL] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
