-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwWG_RPT_AMOUNTS]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[AMORT_TERM] AS [AMORT_TERM],
      x.[APPRAISAL_VALUE] AS [APPRAISAL_VALUE],
      x.[CLTV] AS [CLTV],
      x.[DISCOUNT_AMT] AS [DISCOUNT_AMT],
      x.[HLTV] AS [HLTV],
      x.[INTEREST_RATE] AS [INTEREST_RATE],
      x.[LOCK_DAYS] AS [LOCK_DAYS],
      x.[LTV] AS [LTV],
      x.[MARGIN_PCT] AS [MARGIN_PCT],
      x.[ORIG_LOAN_AMOUNT] AS [ORIG_LOAN_AMOUNT],
      x.[ORIGINATION_AMT] AS [ORIGINATION_AMT],
      x.[PROP_MKT_VALUE] AS [PROP_MKT_VALUE],
      x.[INVLK_MARKET_PRICE] AS [INVLK_MARKET_PRICE],
      x.[INVLK_SRP_FACTOR] AS [INVLK_SRP_FACTOR],
      x.[YSP] AS [YSP],
      x.[OVERAGE] AS [OVERAGE],
      x.[APR] AS [APR],
      x.[UNPAID_PRIN_BAL] AS [UNPAID_PRIN_BAL],
      x.[ARM_INDEX] AS [ARM_INDEX],
      x.[BASE_MARKET_PRICE] AS [BASE_MARKET_PRICE],
      x.[BASE_MARKET_PRICE_OVR] AS [BASE_MARKET_PRICE_OVR],
      x.[INVLK_MARKET_PRICE_OVR] AS [INVLK_MARKET_PRICE_OVR],
      x.[SERVICING_FEE] AS [SERVICING_FEE],
      x.[TTL_MKT_PRICE_ADJUSTMENTS] AS [TTL_MKT_PRICE_ADJUSTMENTS],
      x.[DEBT_RATIO] AS [DEBT_RATIO],
      x.[HOUSING_RATIO] AS [HOUSING_RATIO],
      x.[BASE_LOAN_AMOUNT] AS [BASE_LOAN_AMOUNT],
      x.[CONCURRENT_FINANCE_AMT] AS [CONCURRENT_FINANCE_AMT],
      x.[DISCOUNT_POINTS] AS [DISCOUNT_POINTS],
      x.[HELOC_INITIAL_ADVANCE] AS [HELOC_INITIAL_ADVANCE],
      x.[QUALIFYING_RATE] AS [QUALIFYING_RATE]
   FROM [clt_NetO].[WG_RPT_AMOUNTS] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
