-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwWG_RPT_IPG_DETAIL]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[INVESTOR_CODE] AS [INVESTOR_CODE],
      x.[PRODUCT_CODE] AS [PRODUCT_CODE],
      x.[PRODUCT_NAME] AS [PRODUCT_NAME],
      x.[PROGRAM_CODE] AS [PROGRAM_CODE],
      x.[PROGRAM_NAME] AS [PROGRAM_NAME],
      x.[PRICE_GROUP_CODE] AS [PRICE_GROUP_CODE],
      x.[PRICE_GROUP_CODE_NAME] AS [PRICE_GROUP_CODE_NAME],
      x.[IPG_NAME] AS [IPG_NAME],
      x.[SECONDARY_LOAN_TYPE] AS [SECONDARY_LOAN_TYPE],
      x.[SECONDARY_LOAN_TYPE_DESC] AS [SECONDARY_LOAN_TYPE_DESC],
      x.[PREPAY_PENALTY_TYPE] AS [PREPAY_PENALTY_TYPE],
      x.[PREPAY_PENALTY_TYPE_DESC] AS [PREPAY_PENALTY_TYPE_DESC],
      x.[OVER_ALLOW_PCT] AS [OVER_ALLOW_PCT],
      x.[SHORT_ALLOW_PCT] AS [SHORT_ALLOW_PCT],
      x.[OVER_SPLIT_PCT] AS [OVER_SPLIT_PCT],
      x.[SHORT_SPLIT_PCT] AS [SHORT_SPLIT_PCT],
      x.[REQUIRES_MERS] AS [REQUIRES_MERS],
      x.[REQUIRES_MI] AS [REQUIRES_MI],
      x.[ONE_TIMECLOSE_CONST] AS [ONE_TIMECLOSE_CONST],
      x.[INTERIM_CONSTRUCTION] AS [INTERIM_CONSTRUCTION],
      x.[ASSUMABLE] AS [ASSUMABLE],
      x.[CONV_PERIOD_ST] AS [CONV_PERIOD_ST],
      x.[CONV_PERIOD_END] AS [CONV_PERIOD_END],
      x.[EZD_PRODUCT] AS [EZD_PRODUCT],
      x.[HMDA_REPORTABLE] AS [HMDA_REPORTABLE],
      x.[BUYDOWN_ALLOWED] AS [BUYDOWN_ALLOWED],
      x.[HELOC_ALLOW_YN] AS [HELOC_ALLOW_YN],
      x.[PROD_PROF_TRUE] AS [PROD_PROF_TRUE],
      x.[PRICE_NAME] AS [PRICE_NAME],
      x.[ALLOW_DPA] AS [ALLOW_DPA],
      x.[AVAIL_BTOC] AS [AVAIL_BTOC],
      x.[FIRST_LOCK_IND] AS [FIRST_LOCK_IND],
      x.[OLD_AGENCY_NUM_IND] AS [OLD_AGENCY_NUM_IND],
      x.[PRODUCT_IDENTIFIER] AS [PRODUCT_IDENTIFIER],
      x.[SERVICING_INTERFACE_IND] AS [SERVICING_INTERFACE_IND],
      x.[SERVICING_LOCATION] AS [SERVICING_LOCATION],
      x.[SUB_PRIME_IND] AS [SUB_PRIME_IND],
      x.[MI_REQUIRE] AS [MI_REQUIRE]
   FROM [clt_NetO].[WG_RPT_IPG_DETAIL] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
