-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_creditScore].[VwGF_TL_UW_4]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      HASHBYTES('SHA2_256', x.[ADDRESVS]) AS [ADDRESVS],
      x.[ADUTPROD] AS [ADUTPROD],
      HASHBYTES('SHA2_256', CAST(x.[ALTSCORE] AS NVARCHAR(50))) AS [ALTSCORE],
      x.[BADCREDIT] AS [BADCREDIT],
      x.[BADHR] AS [BADHR],
      x.[BADLTV] AS [BADLTV],
      HASHBYTES('SHA2_256', x.[BORROWERDEL]) AS [BORROWERDEL],
      x.[CHGREFI] AS [CHGREFI],
      HASHBYTES('SHA2_256', x.[COBORROWERDEL]) AS [COBORROWERDEL],
      x.[CTROFFYES] AS [CTROFFYES],
      x.[DELETED] AS [DELETED],
      x.[EMPLYUNA] AS [EMPLYUNA],
      x.[FHAYES] AS [FHAYES],
      x.[FRED500YES] AS [FRED500YES],
      x.[LOWERLTV] AS [LOWERLTV],
      x.[MAJCRDGS] AS [MAJCRDGS],
      x.[MANAYES] AS [MANAYES],
      x.[MINCRDGS] AS [MINCRDGS],
      x.[NOSAVE] AS [NOSAVE],
      x.[PMTSHOCK] AS [PMTSHOCK],
      x.[PORTFOUR] AS [PORTFOUR],
      x.[PORTONE] AS [PORTONE],
      x.[PORTPLUS] AS [PORTPLUS],
      x.[PORTTHREE] AS [PORTTHREE],
      x.[PORTTWO] AS [PORTTWO],
      x.[TTL_MONTH_INCOME] AS [TTL_MONTH_INCOME],
      x.[TTL_MONTH_DEBTS] AS [TTL_MONTH_DEBTS],
      HASHBYTES('SHA2_256', x.[CREDIT_SCORE_IMPAIRMENT]) AS [CREDIT_SCORE_IMPAIRMENT],
      A0.[Descript] AS [CREDIT_SCORE_IMPAIRMENT_X],
      HASHBYTES('SHA2_256', x.[CREDIT_SELECTION_METHOD]) AS [CREDIT_SELECTION_METHOD],
      A1.[Descript] AS [CREDIT_SELECTION_METHOD_X],
      x.[CHKAPPENDIXQ] AS [CHKAPPENDIXQ],
      x.[APPQREASON] AS [APPQREASON],
      HASHBYTES('SHA2_256', CAST(x.[OVERALL_FRAUD_SCORE] AS NVARCHAR(50))) AS [OVERALL_FRAUD_SCORE],
      x.[INCL_INVST_PRP_IN_QM_TEST] AS [INCL_INVST_PRP_IN_QM_TEST]
   FROM [clt_NetO].[GF_TL_UW_4] x
      LEFT JOIN [clt_NetO].[SymbolLookup] A0 on x.[CREDIT_SCORE_IMPAIRMENT] = A0.[DBSYMBOL] AND A0.[TableName] = 'GF_TL_UW_4' and A0.[COLUMNNAME] = 'CREDIT_SCORE_IMPAIRMENT'
      LEFT JOIN [clt_NetO].[SymbolLookup] A1 on x.[CREDIT_SELECTION_METHOD] = A1.[DBSYMBOL] AND A1.[TableName] = 'GF_TL_UW_4' and A1.[COLUMNNAME] = 'CREDIT_SELECTION_METHOD'
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
