-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_creditScore].[VwGF_TLBC_EQ_RES_COLLECT]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[BNUM] AS [BNUM],
      x.[DBID] AS [DBID],
      x.[ROWCOUNTER] AS [ROWCOUNTER],
      x.[RESPONSEID] AS [RESPONSEID],
      HASHBYTES('SHA2_256', CAST(x.[CREDITRESPONSEID] AS NVARCHAR(50))) AS [CREDITRESPONSEID],
      x.[ECOA_DESIGNATOR] AS [ECOA_DESIGNATOR],
      x.[ASSIGNED_DT] AS [ASSIGNED_DT],
      HASHBYTES('SHA2_256', CAST(x.[ORIG_AMT] AS NVARCHAR(50))) AS [ORIG_AMT],
      HASHBYTES('SHA2_256', CAST(x.[FIRST_DELINQUENCY_DT] AS NVARCHAR(50))) AS [FIRST_DELINQUENCY_DT],
      HASHBYTES('SHA2_256', x.[AGENCY_CUST_NUM]) AS [AGENCY_CUST_NUM],
      x.[AUTO_UPDATE_IND] AS [AUTO_UPDATE_IND],
      x.[CLIENT_ID] AS [CLIENT_ID],
      x.[REPORTED_DT] AS [REPORTED_DT],
      HASHBYTES('SHA2_256', CAST(x.[BALANCE] AS NVARCHAR(50))) AS [BALANCE],
      HASHBYTES('SHA2_256', x.[ACCT_NUM]) AS [ACCT_NUM],
      x.[STATUS_CODE] AS [STATUS_CODE],
      x.[STATUS_CODE_TEXT] AS [STATUS_CODE_TEXT],
      HASHBYTES('SHA2_256', x.[NARRATIVE_CODE1]) AS [NARRATIVE_CODE1],
      HASHBYTES('SHA2_256', x.[NARRATIVE_TEXT1]) AS [NARRATIVE_TEXT1],
      HASHBYTES('SHA2_256', x.[NARRATIVE_CODE2]) AS [NARRATIVE_CODE2],
      HASHBYTES('SHA2_256', x.[NARRATIVE_TEXT2]) AS [NARRATIVE_TEXT2],
      HASHBYTES('SHA2_256', x.[CREDITOR_CLASS_CODE]) AS [CREDITOR_CLASS_CODE],
      x.[CRECITOR_CLASS_TEXT] AS [CRECITOR_CLASS_TEXT],
      x.[LAST_PMT_DT] AS [LAST_PMT_DT]
   FROM [clt_NetO].[GF_TLBC_EQ_RES_COLLECT] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
