-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_creditScore].[VwGF_TL_PMT_STREAMS]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[PAYMENTCTR] AS [PAYMENTCTR],
      x.[NUMPAYMENTS] AS [NUMPAYMENTS],
      HASHBYTES('SHA2_256', CAST(x.[STARTDATE] AS NVARCHAR(50))) AS [STARTDATE],
      x.[FULLPAYMENT] AS [FULLPAYMENT],
      x.[CONSTINTERESTFLAG] AS [CONSTINTERESTFLAG],
      x.[DEFERODDDAYSFLAG] AS [DEFERODDDAYSFLAG],
      x.[BOUGHTDOWNFLAG] AS [BOUGHTDOWNFLAG],
      x.[INTERESTONLYFLAG] AS [INTERESTONLYFLAG],
      x.[MINPMTSTREAMFLAG] AS [MINPMTSTREAMFLAG],
      x.[DISCLOSEDPMT] AS [DISCLOSEDPMT],
      HASHBYTES('SHA2_256', CAST(x.[PMI] AS NVARCHAR(50))) AS [PMI],
      x.[EFFECTIVERATE] AS [EFFECTIVERATE],
      x.[PAYMENTRATE] AS [PAYMENTRATE],
      x.[ADJUSTEDPAYMENT] AS [ADJUSTEDPAYMENT],
      HASHBYTES('SHA2_256', CAST(x.[BALANCE] AS NVARCHAR(50))) AS [BALANCE],
      x.[PIPAYMENT] AS [PIPAYMENT]
   FROM [clt_NetO].[GF_TL_PMT_STREAMS] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
