-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwCONSREFI]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[ORIGCOST] AS [ORIGCOST],
      x.[AMTEXLN] AS [AMTEXLN],
      x.[PRESVAL] AS [PRESVAL],
      x.[CSTIMPRO] AS [CSTIMPRO],
      x.[IMPDESC] AS [IMPDESC],
      x.[S_REFPRP] AS [S_REFPRP],
      x.[IMPMADE] AS [IMPMADE],
      x.[LOTACQUR] AS [LOTACQUR],
      x.[REFIIMP] AS [REFIIMP],
      x.[CASHAMT] AS [CASHAMT],
      x.[S_GSE_REFINANCE_PURPOSE] AS [S_GSE_REFINANCE_PURPOSE],
      x.[S_CONST_PERM_CLOSING] AS [S_CONST_PERM_CLOSING],
      x.[INTERNREFI] AS [INTERNREFI],
      x.[ORIG_INVESTOR_LOAN_NBR] AS [ORIG_INVESTOR_LOAN_NBR],
      x.[S_ORIG_INVESTOR] AS [S_ORIG_INVESTOR],
      x.[OTHER_INVESTOR_DESC] AS [OTHER_INVESTOR_DESC],
      x.[OTHERGSEREFIPURPTYPEDESC] AS [OTHERGSEREFIPURPTYPEDESC],
      x.[REPLACE_EXIST_CONSTR_LOAN] AS [REPLACE_EXIST_CONSTR_LOAN],
      x.[FIR_MAX_MONTHLY_AMT] AS [FIR_MAX_MONTHLY_AMT],
      x.[PREVIOUS_REFI_MONTHS] AS [PREVIOUS_REFI_MONTHS],
      x.[CO_REFI_PURCH_CONST] AS [CO_REFI_PURCH_CONST],
      x.[S_CONST_PERM_FEATURE] AS [S_CONST_PERM_FEATURE],
      x.[S_FNM_REFI_PGM] AS [S_FNM_REFI_PGM],
      x.[S_FRE_REFI_PGM] AS [S_FRE_REFI_PGM],
      x.[LIMIT_DESC] AS [LIMIT_DESC],
      x.[REFI_LOAN_ACCT_NBR] AS [REFI_LOAN_ACCT_NBR]
   FROM [clt_NetO].[CONSREFI] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
