-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwGF_TLBC_TU_RES_TRADELINE]
AS
   SELECT
      x.[LNUM] AS [LNUM],
      x.[BNUM] AS [BNUM],
      x.[DBID] AS [DBID],
      x.[ROWCOUNTER] AS [ROWCOUNTER],
      x.[RESPONSEID] AS [RESPONSEID],
      x.[CREDITRESPONSEID] AS [CREDITRESPONSEID],
      x.[CUSTOMER_NAME] AS [CUSTOMER_NAME],
      x.[PORTFOLIO_TYPE] AS [PORTFOLIO_TYPE],
      x.[HIGH_CREDIT] AS [HIGH_CREDIT],
      x.[ECOA_DESIGNATOR] AS [ECOA_DESIGNATOR],
      x.[ACCOUNT_NUM] AS [ACCOUNT_NUM],
      x.[REPORTED_DT] AS [REPORTED_DT],
      x.[OPENED_DT] AS [OPENED_DT],
      x.[MONTHS_REVIEWED] AS [MONTHS_REVIEWED],
      x.[ACCT_TYPE_CODE] AS [ACCT_TYPE_CODE],
      x.[CLOSED_DT] AS [CLOSED_DT],
      x.[SCHED_PAYMENT_AMT] AS [SCHED_PAYMENT_AMT],
      x.[TERMS_FREQUENCY] AS [TERMS_FREQUENCY],
      x.[INDUSTRY_CODE] AS [INDUSTRY_CODE],
      x.[MEMBER_CODE] AS [MEMBER_CODE],
      x.[CLOSED_DATE_IND] AS [CLOSED_DATE_IND],
      x.[CURRENCY] AS [CURRENCY],
      x.[CURRENT_BALANCE_AMT] AS [CURRENT_BALANCE_AMT],
      x.[TERMS_PMT_AMT] AS [TERMS_PMT_AMT],
      x.[CUR_ACCT_RATING] AS [CUR_ACCT_RATING],
      x.[PMT_PATTERN_START_DT] AS [PMT_PATTERN_START_DT],
      x.[PMT_PATTERN] AS [PMT_PATTERN],
      x.[TIMES_30_DAYS_LATE] AS [TIMES_30_DAYS_LATE],
      x.[TIMES_60_DAYS_LATE] AS [TIMES_60_DAYS_LATE],
      x.[TIMES_90_DAYS_LATE] AS [TIMES_90_DAYS_LATE],
      x.[HIGH_PAST_DUE_AMT] AS [HIGH_PAST_DUE_AMT],
      x.[HIGH_PAST_DUE_AMT_DT] AS [HIGH_PAST_DUE_AMT_DT],
      x.[HIGH_PAST_DUE_AMT_RT] AS [HIGH_PAST_DUE_AMT_RT],
      x.[MAX_DELINQUENCY_AMT] AS [MAX_DELINQUENCY_AMT],
      x.[MAX_DELINQUENCY_DT] AS [MAX_DELINQUENCY_DT],
      x.[MAX_DELINQUENCY_ACCT_RT] AS [MAX_DELINQUENCY_ACCT_RT],
      x.[PMT_SCHED_TYPE_CODE] AS [PMT_SCHED_TYPE_CODE],
      x.[PMT_SCHED_DT] AS [PMT_SCHED_DT],
      x.[PORTFOLIO_SALE_CODE] AS [PORTFOLIO_SALE_CODE],
      x.[PORTFOLIO_SALE_NAME] AS [PORTFOLIO_SALE_NAME],
      x.[AFFILIATE_REMARK_CODE] AS [AFFILIATE_REMARK_CODE],
      x.[GENERIC_REMARK_CODE] AS [GENERIC_REMARK_CODE],
      x.[RATING_HIST_REMARK_CODE] AS [RATING_HIST_REMARK_CODE],
      x.[COMPLIANCE_REMARK_CODE] AS [COMPLIANCE_REMARK_CODE],
      x.[CONSUMER_STATEMENT_CODE] AS [CONSUMER_STATEMENT_CODE],
      x.[UPDATE_METHOD_CODE] AS [UPDATE_METHOD_CODE],
      x.[LAST_PMT_DT] AS [LAST_PMT_DT],
      x.[TERMS_PMT_SCHED_MNTH_CNT] AS [TERMS_PMT_SCHED_MNTH_CNT],
      x.[PAST_DUE_AMT] AS [PAST_DUE_AMT],
      x.[CREDIT_LIMIT_AMT] AS [CREDIT_LIMIT_AMT]
   FROM [clt_NetO].[GF_TLBC_TU_RES_TRADELINE] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
;
