-- -----------------------------------------------------
-- Auto generated
-- -----------------------------------------------------


CREATE VIEW [NetO_sas_pii].[VwINCOME]
AS
   SELECT
      x.[LNUM],
      x.[BNUM],
      x.[DBID],
      x.[CTR],
      x.[TITLE],
      x.[BUSTYPE],
      x.[SUPERVSR],
      x.[INCMNAME],
      x.[ADDR1],
      x.[ADDR2],
      x.[CITY],
      x.[STATE],
      x.[ZIP],
      x.[PHONE],
      x.[PHONEXT],
      x.[ATTNOF],
      x.[FAXNO],
      x.[ID],
      x.[EMPDFROM],
      x.[EMPDTO],
      x.[YRSATJOB],
      x.[YRSINPRO],
      x.[JEXPDESC],
      x.[JEXPAMT],
      x.[PRIMINC],
      x.[S_INCOME],
      x.[S_PAYPER],
      x.[INCAMT],
      x.[INCDESC],
      x.[MNTEQUIV],
      x.[USEQUAL],
      x.[TYPEFLAG],
      x.[SELFEMPL],
      x.[BENEFIT],
      x.[BEN_TYPE],
      x.[ACCTOF],
      x.[ACCTNUM],
      x.[VERIFY],
      x.[OTHERDSC],
      x.[NONTAXBL],
      x.[INCOME_VERIFIED],
      x.[MILITARY_YN],
      x.[PERCBUSOWN],
      x.[TSWE_INCOME_IND],
      x.[EFFECTIVE_MO_INC],
      x.[S_JOB_TYPE],
      x.[OVRTIME_CONT],
      x.[PROB_CONT_EMPLOY],
      x.[OTHERINCTYPEDESC],
      x.[S_SPECBOREMPRELTYPE],
      x.[OTHERSPECBOREMPRELTYPEDSC],
      x.[RURALHOUSINGCALC],
      x.[COUNTRY],
      x.[VERIFICATION_TYPE],
      x.[VERIF_TYPE_DESC],
      x.[STATED_FLAG],
      x.[RECORD_CREATED],
      x.[S_INCOMECATEGORY],
      x.[OCCUPATION],
      x.[INCSTIND],
      x.[S_SELFEMPTYPE],
      x.[PRE_VERI_GROSS_INC],
      x.[USE_GROSS_INCOME],
      x.[YTD_AMOUNT],
      x.[YTD_AS_OF_DATE],
      x.[INC_SRC_CTR],
      x.[YTD_AVG_INCOME],
      x.[FOREIGNINCOME],
      x.[SEASONALINCOME],
      x.[LIABCTR],
      x.[GROSSUPOVR],
      x.[GROSSUP],
      x.[FROM_INCOME_CALC],
      x.[STATED_INC]
   FROM [clt_NetO].[INCOME] x
   WHERE
      x.[ASAP_DeleteDateTime] IS NULL
      AND NOT EXISTS (SELECT * FROM [clt_NetO].[GF_TS_AUDIT_LOAN_DELETE] i WHERE x.[LNUM] = i.[DELETED_LNUM])
   ;
