CREATE TABLE [clt_Alkami].[asset_type_gl_account]
(
   [asset_type_gl_account_id]           varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]       datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]                nvarchar(10)         NULL,
   [asset_type_enum_id]                 varchar(40)          NULL,
   [class_enum_id]                      varchar(40)          NULL,
   [asset_id]                           varchar(40)          NULL,
   [organization_party_id]              varchar(40)          NULL,
   [asset_gl_account_id]                varchar(40)          NULL,
   [wip_asset_gl_account_id]            varchar(40)          NULL,
   [receipt_gl_account_id]              varchar(40)          NULL,
   [issuance_gl_account_id]             varchar(40)          NULL,
   [transfer_gl_account_id]             varchar(40)          NULL,
   [acc_depreciation_gl_account_id]     varchar(40)          NULL,
   [depreciation_gl_account_id]         varchar(40)          NULL,
   [profit_gl_account_id]               varchar(40)          NULL,
   [loss_gl_account_id]                 varchar(40)          NULL,
   [receipt_trans_type_enum_id]         varchar(40)          NULL,
   [issuance_trans_type_enum_id]        varchar(40)          NULL,
   [shrinkage_gl_account_id]            varchar(40)          NULL,
   [found_gl_account_id]                varchar(40)          NULL,
   [last_updated_stamp]                 datetime             NULL,
   [ASAP_ROW_HASH]                      nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                      nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                  datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                  datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                    nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                   nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                    nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                  nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]                 datetime2(7)         NULL,
   [ASAP_SRC_NAME]                      nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([asset_type_gl_account_id]), CLUSTERED COLUMNSTORE INDEX)
;
