CREATE TABLE [clt_Alkami].[email_message]
(
   [email_message_id]                 varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [root_email_message_id]            varchar(40)          NULL,
   [parent_email_message_id]          varchar(40)          NULL,
   [status_id]                        varchar(40)          NULL,
   [email_type_enum_id]               varchar(40)          NULL,
   [sent_date]                        datetime             NULL,
   [received_date]                    datetime             NULL,
   [subject]                          text                 NULL,
   [body]                             text                 NULL,
   [body_text]                        text                 NULL,
   [headers_string]                   text                 NULL,
   [from_address]                     text                 NULL,
   [from_name]                        text                 NULL,
   [to_addresses]                     text                 NULL,
   [cc_addresses]                     text                 NULL,
   [bcc_addresses]                    text                 NULL,
   [content_type]                     text                 NULL,
   [message_id]                       nvarchar(80)         NULL,
   [from_user_id]                     varchar(40)          NULL,
   [to_user_id]                       varchar(40)          NULL,
   [email_template_id]                varchar(40)          NULL,
   [email_server_id]                  varchar(40)          NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([email_message_id]), CLUSTERED COLUMNSTORE INDEX)
;
