CREATE TABLE [clt_Alkami].[order_item]
(
   [order_id]                         varchar(40)          NOT NULL,
   [order_item_seq_id]                varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [order_part_seq_id]                varchar(40)          NULL,
   [parent_item_seq_id]               varchar(40)          NULL,
   [item_type_enum_id]                varchar(40)          NULL,
   [product_id]                       varchar(40)          NULL,
   [product_feature_id]               varchar(40)          NULL,
   [other_party_product_id]           varchar(63)          NULL,
   [product_parameter_set_id]         varchar(40)          NULL,
   [item_description]                 text                 NULL,
   [comments]                         text                 NULL,
   [quantity]                         numeric(26,6)        NULL,
   [quantity_uom_id]                  varchar(40)          NULL,
   [quantity_cancelled]               numeric(26,6)        NULL,
   [selected_amount]                  numeric(26,6)        NULL,
   [priority]                         numeric(20,0)        NULL,
   [required_by_date]                 datetime             NULL,
   [unit_amount]                      numeric(25,5)        NULL,
   [unit_list_price]                  numeric(25,5)        NULL,
   [is_modified_price]                char(1)              NULL,
   [standard_cost]                    numeric(25,5)        NULL,
   [external_item_seq_id]             varchar(40)          NULL,
   [from_asset_id]                    varchar(40)          NULL,
   [product_price_id]                 varchar(40)          NULL,
   [product_category_id]              varchar(40)          NULL,
   [is_promo]                         char(1)              NULL,
   [promo_quantity]                   numeric(26,6)        NULL,
   [promo_times_used]                 numeric(26,6)        NULL,
   [store_promotion_id]               varchar(40)          NULL,
   [promo_code_id]                    varchar(40)          NULL,
   [promo_code_text]                  text                 NULL,
   [subscription_id]                  varchar(40)          NULL,
   [fin_account_id]                   varchar(40)          NULL,
   [fin_account_trans_id]             varchar(40)          NULL,
   [override_gl_account_id]           varchar(40)          NULL,
   [sales_opportunity_id]             varchar(40)          NULL,
   [source_reference_id]              varchar(63)          NULL,
   [source_percentage]                numeric(26,6)        NULL,
   [amount_already_included]          numeric(25,5)        NULL,
   [exempt_amount]                    numeric(24,4)        NULL,
   [customer_reference_id]            varchar(63)          NULL,
   [tax_authority_id]                 varchar(40)          NULL,
   [opt_in_rewards]                   char(1)              NULL,
   [opt_in_secured_business]          char(1)              NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([order_id]), CLUSTERED COLUMNSTORE INDEX)
;
