CREATE TABLE [clt_Alkami].[payment_method]
(
   [payment_method_id]                varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [payment_method_type_enum_id]      varchar(40)          NULL,
   [purpose_enum_id]                  varchar(40)          NULL,
   [owner_party_id]                   varchar(40)          NULL,
   [description]                      text                 NULL,
   [from_date]                        datetime             NULL,
   [thru_date]                        datetime             NULL,
   [thru_date_set_auto]               char(1)              NULL,
   [opened_date]                      datetime             NULL,
   [title_on_account]                 text                 NULL,
   [first_name_on_account]            text                 NULL,
   [middle_name_on_account]           text                 NULL,
   [last_name_on_account]             text                 NULL,
   [suffix_on_account]                text                 NULL,
   [company_name_on_account]          text                 NULL,
   [ledger_balance]                   numeric(24,4)        NULL,
   [available_balance]                numeric(24,4)        NULL,
   [balance_date]                     datetime             NULL,
   [loan_payment_amount]              numeric(24,4)        NULL,
   [loan_payment_period_uom_id]       varchar(40)          NULL,
   [currency_uom_id]                  varchar(40)          NULL,
   [postal_contact_mech_id]           varchar(40)          NULL,
   [telecom_contact_mech_id]          varchar(40)          NULL,
   [email_contact_mech_id]            varchar(40)          NULL,
   [gateway_cim_id]                   varchar(63)          NULL,
   [payment_gateway_config_id]        varchar(40)          NULL,
   [image_url]                        text                 NULL,
   [trust_level_enum_id]              varchar(40)          NULL,
   [payment_fraud_evidence_id]        varchar(40)          NULL,
   [gl_account_id]                    varchar(40)          NULL,
   [fin_account_id]                   varchar(40)          NULL,
   [original_payment_method_id]       varchar(40)          NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([payment_method_id]), CLUSTERED COLUMNSTORE INDEX)
;
