CREATE TABLE [clt_Alkami].[visit]
(
   [visit_id]                         varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [visitor_id]                       varchar(40)          NULL,
   [user_id]                          varchar(40)          NULL,
   [user_created]                     char(1)              NULL,
   [session_id]                       text                 NULL,
   [server_ip_address]                varchar(40)          NULL,
   [server_host_name]                 text                 NULL,
   [webapp_name]                      text                 NULL,
   [initial_locale]                   varchar(63)          NULL,
   [initial_request]                  text                 NULL,
   [initial_referrer]                 text                 NULL,
   [initial_user_agent]               text                 NULL,
   [client_ip_address]                varchar(63)          NULL,
   [client_host_name]                 text                 NULL,
   [client_user]                      text                 NULL,
   [client_ip_isp_name]               varchar(63)          NULL,
   [client_ip_postal_code]            varchar(63)          NULL,
   [client_ip_city]                   varchar(63)          NULL,
   [client_ip_metro_code]             varchar(63)          NULL,
   [client_ip_region_code]            varchar(63)          NULL,
   [client_ip_region_name]            varchar(63)          NULL,
   [client_ip_state_prov_geo_id]      varchar(40)          NULL,
   [client_ip_country_geo_id]         varchar(40)          NULL,
   [client_ip_latitude]               varchar(63)          NULL,
   [client_ip_longitude]              varchar(63)          NULL,
   [client_ip_time_zone]              varchar(63)          NULL,
   [from_date]                        datetime             NULL,
   [thru_date]                        datetime             NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([visit_id]), CLUSTERED COLUMNSTORE INDEX)
;
