CREATE TABLE [clt_Alkami].[work_effort]
(
   [work_effort_id]                   varchar(40)          NOT NULL,
   [ASAP_RecordEffectiveDateTime]     datetime2(7)         NOT NULL,
   [ASAP_DeleteDateTime]              nvarchar(10)         NULL,
   [universal_id]                     text                 NULL,
   [source_reference_id]              varchar(63)          NULL,
   [parent_work_effort_id]            varchar(40)          NULL,
   [root_work_effort_id]              varchar(40)          NULL,
   [work_effort_type_enum_id]         varchar(40)          NULL,
   [purpose_enum_id]                  varchar(40)          NULL,
   [visibility_enum_id]               varchar(40)          NULL,
   [resolution_enum_id]               varchar(40)          NULL,
   [work_type_enum_id]                varchar(40)          NULL,
   [owner_party_id]                   varchar(40)          NULL,
   [product_store_id]                 varchar(40)          NULL,
   [status_id]                        varchar(40)          NULL,
   [status_flow_id]                   varchar(40)          NULL,
   [priority]                         numeric(20,0)        NULL,
   [send_notification_email]          char(1)              NULL,
   [percent_complete]                 numeric(20,0)        NULL,
   [revision_number]                  numeric(20,0)        NULL,
   [work_effort_name]                 text                 NULL,
   [description]                      text                 NULL,
   [location]                         text                 NULL,
   [facility_id]                      varchar(40)          NULL,
   [info_url]                         text                 NULL,
   [shipment_method_enum_id]          varchar(40)          NULL,
   [estimated_start_date]             datetime             NULL,
   [estimated_completion_date]        datetime             NULL,
   [actual_start_date]                datetime             NULL,
   [actual_completion_date]           datetime             NULL,
   [recur_start_cron]                 text                 NULL,
   [recur_limit]                      numeric(20,0)        NULL,
   [recur_end_date]                   datetime             NULL,
   [all_day_start]                    date                 NULL,
   [all_day_end]                      date                 NULL,
   [estimated_work_time]              numeric(26,6)        NULL,
   [estimated_setup_time]             numeric(26,6)        NULL,
   [remaining_work_time]              numeric(26,6)        NULL,
   [actual_work_time]                 numeric(26,6)        NULL,
   [actual_setup_time]                numeric(26,6)        NULL,
   [total_time_allowed]               numeric(26,6)        NULL,
   [estimated_work_duration]          numeric(26,6)        NULL,
   [actual_work_duration]             numeric(26,6)        NULL,
   [actual_break_duration]            numeric(26,6)        NULL,
   [time_uom_id]                      varchar(40)          NULL,
   [actual_cost]                      numeric(24,4)        NULL,
   [actual_client_cost]               numeric(24,4)        NULL,
   [total_client_cost_allowed]        numeric(24,4)        NULL,
   [cost_uom_id]                      varchar(40)          NULL,
   [last_updated_stamp]               datetime             NULL,
   [ASAP_ROW_HASH]                    nvarchar(64)         NULL,
   [ASAP_DML_FLAG]                    nvarchar(2)          NULL,
   [ASAP_CREATED_DATE]                datetime2(7)         NULL,
   [ASAP_UPDATED_DATE]                datetime2(7)         NULL,
   [ASAP_LINEAGE_ID]                  nvarchar(36)         NULL,
   [ASAP_ACTIVITY_ID]                 nvarchar(36)         NULL,
   [ASAP_TRIGGER_ID]                  nvarchar(36)         NULL,
   [ASAP_SRC_FILEPATH]                nvarchar(1000)       NULL,
   [ASAP_SRC_FILE_DATE]               datetime2(7)         NULL,
   [ASAP_SRC_NAME]                    nvarchar(36)         NULL
)
WITH (DISTRIBUTION = HASH ([work_effort_id]), CLUSTERED COLUMNSTORE INDEX)
;
